/** @type {import('tailwindcss').Config} */
/* Every colour is a CSS custom property from src/tokens.css (generated by
   scripts/design_tokens_contrast_phase8b.py, where the contrast ratios are measured). Nothing is
   hard-coded here or in components. */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: "var(--ink)",
        muted: "var(--muted)",
        faint: "var(--faint)",
        paper: "var(--bg-0)",
        panel: "var(--bg-1)",
        card: "var(--bg-2)",
        raised: "var(--bg-3)",
        rule: "var(--rule)",
        "rule-strong": "var(--rule-strong)",
        "ui-border": "var(--ui-border)",
        accent: "var(--accent)",
        "accent-dim": "var(--accent-dim)",
        fail: "var(--fail)",
        insufficient: "var(--insufficient)",
        pass: "var(--pass)",
        hbo2: "var(--hbo2)",
        hb: "var(--hb)",
      },
      fontFamily: {
        serif: ["Iowan Old Style", "Palatino Linotype", "Book Antiqua", "Georgia", "serif"],
        sans: ["Inter", "Segoe UI", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Consolas", "monospace"],
      },
      maxWidth: { measure: "68ch" },
      boxShadow: {
        glow: "0 0 0 1px var(--rule-strong), 0 12px 40px -18px rgba(111, 227, 208, 0.35)",
        "glow-strong": "0 0 0 1px var(--accent-dim), 0 20px 60px -20px rgba(111, 227, 208, 0.55)",
      },
    },
  },
  plugins: [],
};
