"""Phase 8A - reports/content_review.md: every check, plain and technical side by side.

Two sources, both real:
  1. the content model itself (`hemosight.audit.content`), rendered for PASS, FAIL and
     INSUFFICIENT with representative measured values, so the plain headline for each
     verdict shape can be read against the caveats it must carry;
  2. the harness run on the synthetic sample submissions shipped with the app, so the
     plain and technical statements are compared on genuinely produced results.
Anything the plain version overstates or understates should be visible here.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))

from hemosight.audit import ALL_IDS, load_predictions, run_audit          # noqa: E402
from hemosight.audit.content import CATEGORY_PLAIN, CONTENT, GLOSSARY, enrich  # noqa: E402
from hemosight.audit.verdict import FAIL, INSUFFICIENT, PASS                # noqa: E402
from hemosight.io import paths                                              # noqa: E402
from test_phase8a import MEASURED, _res                                      # noqa: E402

BADGE = {PASS: "PASS", FAIL: "FAIL", INSUFFICIENT: "INSUFFICIENT DATA"}


def main() -> int:
    L: list[str] = []
    A = L.append
    A("# Content review - plain and technical layers, side by side\n\n")
    A("Generated by `scripts/audit_content_review_phase8a.py` from `hemosight.audit.content`. The "
      "rule under review: **simplify the sentence, never the claim.** For each check the "
      "plain layer is shown beside the technical layer; a reviewer should look for any "
      "plain sentence that claims more or less certainty than its technical counterpart.\n\n")
    A("## 1. Static content per check\n\n")
    for cid in ALL_IDS:
        c = CONTENT[cid]
        A(f"### {c.title_plain}  (`{cid}`)\n\n")
        A(f"*Question:* {c.question_plain}\n\n")
        A("| layer | text |\n| --- | --- |\n")
        A(f"| what it means (plain) | {c.what_it_means_plain} |\n")
        A(f"| mechanism (plain) | {c.mechanism_plain} |\n")
        A(f"| mechanism (technical) | {c.mechanism_technical} |\n")
        A(f"| provenance | {c.provenance} |\n")
        A(f"| glossary terms | {', '.join(c.glossary_terms)} |\n\n")
        A("**Headlines by verdict, with representative measured values:**\n\n")
        A("| verdict | plain headline | what to do |\n| --- | --- | --- |\n")
        for v in (FAIL, PASS, INSUFFICIENT):
            r = enrich(_res(cid, v, MEASURED[cid].get(v), ["a split column"] if v == INSUFFICIENT else None))
            pl = r["plain"]
            A(f"| {BADGE[v]} | {pl['headline']} | **{pl['what_to_do']['category']}** - {pl['what_to_do']['text']} |\n")
        A("\n")

    A("## 2. Real outputs on the shipped sample submissions\n\n")
    A("The harness run on the synthetic samples in `app/backend/sample_data/`. Each row pairs the "
      "technical headline the check produced with the plain headline rendered from the same "
      "measured values.\n\n")
    samples = sorted((ROOT / "app" / "backend" / "sample_data").glob("*.csv"))[:4]
    for s in samples:
        df = pd.read_csv(s)
        inp = load_predictions(df)
        rep = run_audit(inp, checks=[c for c in ALL_IDS if c != "duplicates"],
                        options={"permutation": {"n_permutations": 200}})
        A(f"### `{s.name}`\n\n| check | verdict | technical headline | plain headline |\n| --- | --- | --- | --- |\n")
        for r in rep.results:
            A(f"| {r['check_id']} | {BADGE[r['verdict']]} | {r['headline'].replace('|', '/')} | "
              f"{r['plain']['headline'].replace('|', '/')} |\n")
        A("\n")

    A("## 3. The three what-to-do categories\n\n")
    for k, v in CATEGORY_PLAIN.items():
        A(f"* **{k}** - {v}\n")
    A("\n## 4. Glossary\n\n")
    for k, v in sorted(GLOSSARY.items(), key=lambda kv: kv[0].lower()):
        A(f"* **{k}** - {v}\n")
    A("\n## 5. Review notes\n\n")
    A("* INSUFFICIENT DATA: every plain headline begins \"We could not check this\" and names "
      "the missing input; the what-to-do text says it must not be read as a pass. Enforced by "
      "`tests/test_phase8a.py`.\n")
    A("* Permutation at the floor: the plain headline states the floor in words and that the "
      "true value may be smaller; whether the null re-ran the model selection is stated either "
      "way. Enforced by test.\n")
    A("* Narrow margins (demographic baseline) and near-threshold retained fractions (subgroup "
      "robustness) are carried into the plain headline. Enforced by test.\n")
    A("* No what-to-do text is phrased as a way to make a failing check pass; FAIL is FIXABLE "
      "only for the two split-construction checks. Enforced by test.\n")
    A("* Known limit: plain headlines are templates over measured values; a check that gains a "
      "new measured key or a new caveat must extend the template, and the test's MEASURED "
      "table, at the same time.\n")
    (paths.REPORTS / "content_review.md").write_text("".join(L), encoding="utf-8")
    print(f"wrote {paths.REPORTS / 'content_review.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
