"""Phase 1, Task 1 + Task 5: generate reports/phase1_data_audit.md and
reports/phase1_summary.md from the manifests and overlap results.

Regenerates deterministically from data/interim/. Narrative conclusions are written
inline here so the report and the evidence live in one place.

    .\\.venv\\Scripts\\python.exe scripts\\data_audit_report_phase1.py
"""

from __future__ import annotations

import json
from collections import Counter

import numpy as np
import pandas as pd

from hemosight.io import paths

RAW_DIRS = {
    "nus8": paths.NUS8,
    "SBVPI": paths.RAW / "SBVPI",
    "MOBIUS": paths.MOBIUS,
    "CP-AnemiC dataset": paths.CP_ANEMIC,
    "Ghana conjunctiva": paths.GHANA_CONJ,
    "Ghana fingernails": paths.RAW / "Detection of Anemia using Colour of the Fingernails Image Datasets from Ghana",
    "dataset anemia (Eyes-Defy-Anemia)": paths.EYES_DEFY,
    "Hb_PPG_Dataset": paths.HB_PPG,
}


def scan_dir(root) -> dict:
    ext, total, n = Counter(), 0, 0
    for p in root.rglob("*"):
        if p.is_file():
            ext[p.suffix.lower() or "(none)"] += 1
            try:
                total += p.stat().st_size
            except OSError:
                pass
            n += 1
    return {"files": n, "bytes": total, "ext": dict(ext.most_common(8))}


def human(b: int) -> str:
    for u in ("B", "KB", "MB", "GB"):
        if b < 1024 or u == "GB":
            return f"{b:.1f} {u}"
        b /= 1024
    return f"{b:.1f} GB"


def md_table(df: pd.DataFrame, floatfmt: str = "{:.2f}") -> str:
    d = df.copy()
    for c in d.columns:
        if pd.api.types.is_float_dtype(d[c]):
            d[c] = d[c].map(lambda v: "" if pd.isna(v) else floatfmt.format(v))
    d = d.astype(str)
    head = "| " + " | ".join([d.index.name or ""] + list(d.columns)) + " |"
    sep = "| " + " | ".join(["---"] * (len(d.columns) + 1)) + " |"
    rows = ["| " + " | ".join([str(i)] + list(r)) + " |" for i, r in zip(d.index, d.values)]
    return "\n".join([head, sep] + rows)


def main() -> int:
    paths.ensure_dirs()
    master = pd.read_csv(paths.MANIFESTS / "master.csv")
    nus = pd.read_csv(paths.MANIFESTS / "nus8.csv")
    ov = json.loads((paths.OVERLAP / "overlap_results.json").read_text(encoding="utf-8"))
    splits = json.loads((paths.SPLITS / "split_summary.json").read_text(encoding="utf-8"))
    hashes = {s: pd.read_csv(paths.OVERLAP / f"hashes_{s}.csv")
              for s in ("cp_anemic", "ghana_conj", "ghana_nail")}
    cp = pd.read_csv(paths.MANIFESTS / "cp_anemic.csv")

    print("scanning raw directories ...")
    scans = {k: scan_dir(v) for k, v in RAW_DIRS.items()}

    # ---------------------------------------------------------------- overview
    ov_rows = []
    for k, s in scans.items():
        ov_rows.append({"dataset": k, "files": s["files"], "size": human(s["bytes"]),
                        "extensions": ", ".join(f"{e}:{n}" for e, n in s["ext"].items())})
    overview = pd.DataFrame(ov_rows).set_index("dataset")

    # ------------------------------------------------------------- per dataset
    per = master.groupby("dataset").agg(
        images=("image_id", "count"),
        subjects=("subject_id", "nunique"),
        with_hb=("hb_g_dl", lambda s: int(s.notna().sum())),
        hb_min=("hb_g_dl", "min"), hb_max=("hb_g_dl", "max"), hb_mean=("hb_g_dl", "mean"),
        age_min=("age", "min"), age_max=("age", "max"),
        devices=("device_model", "nunique"),
    )
    per["imgs_per_subject"] = (per.images / per.subjects).round(2)
    per.index.name = "dataset"

    # severity / dedup
    dedup = pd.DataFrame([
        {"dataset": k, "files": len(v), "unique_md5": int(v.md5.nunique()),
         "redundant": len(v) - int(v.md5.nunique()),
         "pct_redundant": round(100 * (1 - v.md5.nunique() / len(v)), 1)}
        for k, v in hashes.items()]).set_index("dataset")

    sev = cp.severity.value_counts()

    # CP-AnemiC duplicate label conflicts
    h = hashes["cp_anemic"].merge(cp[["image_id", "hb_g_dl"]], on="image_id")
    grp = h.groupby("md5").agg(n=("image_id", "size"), nhb=("hb_g_dl", "nunique"),
                               hbmin=("hb_g_dl", "min"), hbmax=("hb_g_dl", "max"))
    dupg = grp[grp.n > 1]
    conflict = dupg[dupg.nhb > 1]

    # resolution
    res = master.dropna(subset=["width"]).groupby("dataset").agg(
        w_min=("width", "min"), w_max=("width", "max"), w_med=("width", "median"),
        h_min=("height", "min"), h_max=("height", "max"), h_med=("height", "median"))

    lines: list[str] = []
    A = lines.append

    A("# Phase 1 - Data Audit\n")
    A("Generated by `scripts/data_audit_report_phase1.py` from `data/interim/manifests/` and ")
    A("`data/interim/overlap/`. `data/raw/` was read only.\n")
    A("> **Headline:** three findings below change what this project can claim. ")
    A("CP-AnemiC is largely *contained inside* the Ghana conjunctiva set; CP-AnemiC's ")
    A("haemoglobin labels are internally inconsistent on its duplicated images; and the ")
    A("two largest conjunctiva sets are pre-segmented crops with **no sclera**, which is ")
    A("the input N1 requires.\n")

    A("\n## 1. Raw inventory\n")
    A(md_table(overview))

    A("\n\n## 2. Per-dataset characterisation\n")
    A(md_table(per))
    A("\n\n`imgs_per_subject` > 1 means image-level splitting would leak. It does for ")
    A("every image dataset here except Eyes-Defy.\n")

    A("\n### 2.1 Resolution\n")
    A(md_table(res, "{:.0f}"))
    A("\n\nThe Ghana pool and CP-AnemiC are small crops (median 144x144 and 228x88). ")
    A("Eyes-Defy, SBVPI and MOBIUS are full-resolution photographs.\n")

    A("\n### 2.2 Where labels live\n")
    A("""
| Dataset | Label location | Hb present | Units | Subject id |
| --- | --- | --- | --- | --- |
| CP-AnemiC | `Anemia_Data_Collection_Sheet.xlsx`, one row per IMAGE_ID | yes | g/dL | **absent** - no participant column |
| Ghana conjunctiva | filename prefix only (`Anemic-` / `Non-Anemic-`) | no | - | filename (`Anemic-042`) |
| Ghana fingernails | filename prefix only | no | - | filename (`Anemic-Fin-042`) |
| Eyes-Defy-Anemia | `India.xlsx` / `Italy.xlsx`, joined on folder number | yes | g/dL | folder name |
| Hb_PPG_Dataset | `subject information.xlsx` | yes | **g/L -> converted** | `ID` |
| SBVPI | `SBVPI_Gender_Age_Colour.txt` | no | - | folder name |
| MOBIUS | `data.csv` | no | - | folder name |
| nus8 | per-camera `groundtruth.mat` | n/a | n/a | n/a (not human subjects) |
""")

    A("\n### 2.3 Haemoglobin distribution and severe anemia\n")
    A("Severe anemia **does exist** in this collection, contrary to the assumption ")
    A("recorded in novelty claim N2.\n\n")
    hb = master.dropna(subset=["hb_g_dl"])
    sevtab = pd.DataFrame({
        "n_with_hb": hb.groupby("dataset").hb_g_dl.size(),
        "hb_min": hb.groupby("dataset").hb_g_dl.min(),
        "hb_max": hb.groupby("dataset").hb_g_dl.max(),
        "n_lt_7 (severe)": hb[hb.hb_g_dl < 7].groupby("dataset").hb_g_dl.size(),
        "n_lt_5 (very severe)": hb[hb.hb_g_dl < 5].groupby("dataset").hb_g_dl.size(),
    }).fillna(0)
    A(md_table(sevtab))
    A("\n\nCP-AnemiC severity labels: " + ", ".join(f"{k}={v}" for k, v in sev.items()) + ".\n")
    A("\n**Consequence for N2.** The claim that \"no public dataset contains severe ")
    A("anemia\" is too strong as written and must be narrowed. CP-AnemiC contains ")
    A(f"{int((hb.hb_g_dl < 7).sum())} images below 7 g/dL (minimum {hb.hb_g_dl.min():.1f} g/dL). ")
    A("The defensible version of N2 is that severe cases are *rare and concentrated in a ")
    A("single site* - and, per section 3, those very images carry unreliable labels.\n")

    A("\n### 2.4 Image content: are these photographs, or crops?\n")
    A("Fraction of near-black pixels (max channel < 12), sampled 60 images per dataset, ")
    A("seed 0. A high value means the image is a segmented cutout on a black field ")
    A("rather than a photograph of a scene.\n\n")
    from PIL import Image
    seg_rows = []
    for name in ("cp_anemic", "ghana_conj", "ghana_nail", "eyes_defy", "sbvpi", "mobius"):
        d = pd.read_csv(paths.MANIFESTS / f"{name}.csv")
        s = d.sample(min(60, len(d)), random_state=0)
        fr = []
        for p in s.file_path:
            try:
                with Image.open(p) as im:
                    a = np.asarray(im.convert("RGB").resize((128, 128)))
                fr.append(float((a.max(axis=2) < 12).mean()))
            except Exception:
                pass
        fr = np.array(fr)
        seg_rows.append({"dataset": name, "n_sampled": len(fr),
                         "black_mean": fr.mean(), "black_median": float(np.median(fr)),
                         "pct_images_over_30pct_black": 100 * float((fr > 0.30).mean())})
    A(md_table(pd.DataFrame(seg_rows).set_index("dataset"), "{:.3f}"))
    A("""

**This is the most consequential finding for N1.** CP-AnemiC and the Ghana conjunctiva
set are *pre-segmented conjunctiva cutouts*: every sampled image is more than half
black, and the eye surrounding the conjunctiva - including the sclera - has been
removed. N1 estimates the scene illuminant from the sclera as an endogenous white
reference. **That input does not exist in these two datasets.**

What N1 can still be built and validated on:

* `nus8` - illuminant estimation accuracy against ground truth, 6 cameras. Intact.
* `SBVPI` / `MOBIUS` - sclera segmentation, full periocular images. Intact. No Hb.
* `eyes_defy` - the only dataset with full photographs **and** haemoglobin, so the
  only end-to-end test of "sclera white reference -> Hb". **218 subjects, 2 sites,
  2 near-identical phone models, no severe cases (minimum 7.0 g/dL).**

So the headline claim rests on 218 subjects, not on the ~9,000 images the collection
appears to offer. This should be stated in the paper rather than discovered by a
reviewer.
""")

    A("\n### 2.5 Devices\n")
    dev = master.dropna(subset=["device_model"]).groupby(["dataset", "device_model"]).size()
    A(md_table(dev.to_frame("images")))
    A("\n\nEXIF is **absent entirely** from CP-AnemiC and both Ghana sets - stripped by ")
    A("whatever cropping produced them. Eyes-Defy carries exactly two device models, ")
    A("`SM-G920F` (Italy) and `SM-G920I` (India): both are regional variants of the same ")
    A("Samsung Galaxy S6. Device diversity across this entire collection is therefore ")
    A("close to nil, and per-device stratification for N5 is impossible on the Ghana pool.\n")

    # ------------------------------------------------------------ overlap
    A("\n\n## 3. Overlap check (Task 2)\n")
    A(md_table(dedup))
    A("\n\n### 3.1 CP-AnemiC is contained inside the Ghana conjunctiva set\n")
    p0 = next(p for p in ov["pairs"] if p["pair"] == "cp_anemic|ghana_conj")
    cpm, gcm = set(hashes["cp_anemic"].md5), set(hashes["ghana_conj"].md5)
    inter = cpm & gcm
    A(f"""
| Signal | Result |
| --- | --- |
| MD5 distinct hashes shared | **{len(inter)}** of {len(cpm)} CP-AnemiC unique images (**{100*len(inter)/len(cpm):.1f}%**) |
| CP-AnemiC files byte-identical to a Ghana file | **{int(hashes['cp_anemic'].md5.isin(inter).sum())} / {len(hashes['cp_anemic'])}** ({100*hashes['cp_anemic'].md5.isin(inter).mean():.1f}%) |
| pHash Hamming = 0 | {p0['phash_pct_le']['0']} / {p0['n_a']} |
| pHash Hamming <= 10 | **{p0['phash_n_below_thresh']} / {p0['n_a']} ({100*p0['phash_frac_below_thresh']:.2f}%)** |
| dHash Hamming <= 10 | {p0['dhash_n_below_thresh']} / {p0['n_a']} ({100*p0['dhash_frac_below_thresh']:.2f}%) |
| Embedding cosine >= 0.92 | {p0['embed_n_above']} / {p0['n_a']} ({100*p0['embed_frac_above']:.2f}%) |

All four independent signals agree. See
`reports/figures/phase1_overlap_cp_anemic__ghana_conj.png` for side-by-side pairs at
Hamming distance 0.

**Verdict: these are not two sites. CP-AnemiC is a labelled subset of the same
collection.** Only {100*hashes['ghana_conj'].md5.isin(inter).mean():.1f}% of the Ghana conjunctiva files are covered, so the
Ghana set is the superset.
""")

    A("\n### 3.2 Cross body site: an N6 opportunity, not contamination\n")
    p1 = next(p for p in ov["pairs"] if p["pair"] == "ghana_conj|ghana_nail")
    A(f"""
Image content does **not** overlap between conjunctiva and fingernail images
(MD5 shared = {p1['md5_distinct_hashes_shared']}, minimum pHash distance = {p1['phash_min']},
maximum embedding cosine = {p1['embed_max']:.3f}) - as expected for photographs of
different body parts. Image hashing cannot answer the participant question here.

The participant evidence is the numbering. Subject numbers parsed from filenames:

| Class | Conjunctiva subjects | Nail subjects | Shared numbers | Jaccard |
| --- | --- | --- | --- | --- |
| non-anemic | 204 (1-204) | 204 (1-204) | **204** | **1.000** |
| anemic | 251 (1-272) | 271 (1-272) | 250 | 0.919 |

A perfect 204/204 correspondence over a contiguous range is not plausible by chance.
**Roughly 454 participants appear at both body sites.** Flagged as an **N6
opportunity**: genuine per-subject conjunctiva+nail pairs, which is what multimodal
fusion needs and what an ensemble over unrelated subjects cannot provide.

Caveat: this is inferred from a shared numbering scheme, not from a participant ID
column. It is strong but not proof, and these subjects have **no Hb values** - only a
binary class - so the pairs support fusion architecture work, not calibrated
regression.
""")

    A("\n### 3.3 CP-AnemiC haemoglobin labels are internally inconsistent\n")
    A(f"""
CP-AnemiC has {len(hashes['cp_anemic'])} files but only **{int(hashes['cp_anemic'].md5.nunique())} unique images**.
Of the {len(dupg)} groups of byte-identical images, **{len(conflict)} carry more than one
distinct haemoglobin value**. The worst group is one image appearing 10 times with
haemoglobin recorded as 4.6, 5.1, 8.0, 8.7, 8.8, 8.9, 9.5, 9.7, 10.5 and 10.93 g/dL,
attributed to 8 different hospitals.

{int(dupg.n.sum())} of {len(hashes['cp_anemic'])} files ({100*dupg.n.sum()/len(hashes['cp_anemic']):.1f}%) sit in a conflicted group.

Either the same photograph was reused across participant records, or the
image-to-record linkage is broken. Either way **the per-image Hb target cannot be
trusted on the duplicated subset**, and this is the subset containing most of the
severe cases. This is a labelling-integrity problem, independent of the overlap
finding, and it constrains every Hb regression result this project can report.
""")

    A("\n### 3.4 Signal that could not be computed\n")
    A(ov["metadata_note"] + "\n")

    # ------------------------------------------------------------ nus8
    A("\n\n## 4. nus8\n")
    ncam = nus.groupby("camera").agg(images=("image_id", "count"),
                                     darklevel=("darklevel", "first"),
                                     saturation=("saturation_level", "first"))
    A(md_table(ncam, "{:.0f}"))
    A(f"\n\nAll **{nus.camera.nunique()} extracted cameras** parsed; {len(nus)} images, ")
    A("zero missing PNGs, zero missing colorchecker masks, all ground-truth illuminants ")
    A("unit-normalised. Black and saturation levels differ per camera (12-bit and 14-bit ")
    A("sensors both present), which is exactly the sensor diversity N1 needs.\n")
    A("\n`SamsungNX2000/groundtruth.mat/` is **empty** on this machine; its ground truth is ")
    A("read from `raw_downloads/SamsungNX2000_gt.mat` by `paths.resolve_nus8_gt()`. ")
    A("Two of the benchmark's eight cameras (SonyA57, PanasonicGX1) are not extracted.\n")

    # ------------------------------------------------------------ scin
    A("\n\n## 5. SCIN: removed from the project\n")
    A("`data/raw/scin-main/` held **no data** - 5 documentation files (README, ")
    A("schema, licence, contributing guide, demo notebook). SCIN images and its ")
    A("skin-tone labels live in a Google Cloud Storage bucket, never downloaded.\n")
    A("\nEven if downloaded it could not have served N5: SCIN is **dermatology** ")
    A("imagery with no conjunctiva photographs, no haemoglobin, and no participant ")
    A("correspondence to any anemia dataset here, so its Fitzpatrick and Monk ")
    A("labels cannot be attached to these subjects. Using it would have required ")
    A("an unvalidated cross-domain transfer.\n")
    A("\n**Phase 1.5 deleted it and rebuilt N5 without it** - skin tone is now ")
    A("estimated by Individual Typology Angle on N1-calibrated periocular skin. ")
    A("See `reports/phase1_5_remediation.md`.\n")

    # ------------------------------------------------------------ splits
    A("\n\n## 6. Splits (Task 4)\n")
    A(f"Seed `{splits['seed']}` (`configs/phase1_splits.yaml`). ")
    A("Grouping is the connected components of (subject_id, md5), so identical images ")
    A("cannot straddle a boundary even when filed under different subject ids.\n\n")
    A(f"""
Ghana pool: {splits['ghana_pool']['images']} images, {splits['ghana_pool']['nominal_subject_ids']}
nominal subject ids, collapsing to **{splits['ghana_pool']['leakproof_groups']} leak-proof groups**.
The gap between those last two numbers is the leakage a subject-level split would
have permitted.

| Split | Images | Groups |
| --- | --- | --- |
""")
    for k in ("train", "calibration", "test"):
        A(f"| {k} | {splits['ghana_pool']['by_split'].get(k, 0)} | "
          f"{splits['ghana_pool']['groups_by_split'].get(k, 0)} |\n")
    A(f"\nLeak check: **{splits['leak_check']}**\n")

    (paths.REPORTS / "phase1_data_audit.md").write_text("".join(lines), encoding="utf-8")
    print(f"wrote {paths.REPORTS / 'phase1_data_audit.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
