"""Phase 8B - the palette and its measured WCAG contrast ratios.

The tokens below are the single source of truth: this script writes them into
app/frontend/src/tokens.css (CSS custom properties) and measures every text/ground pair
the interface uses, so the report's contrast table is computed, not asserted.
WCAG 2.1: normal text >= 4.5:1 for AA, large text (>= 24px or >= 19px bold) >= 3:1;
non-text UI components >= 3:1.
"""
from __future__ import annotations

import json

from hemosight.io import paths

TOKENS = {
    # ground and elevations: deep near-black, cool, never pure black
    "bg-0": "#0a0d12",
    "bg-1": "#10141b",
    "bg-2": "#161b24",
    "bg-3": "#1e2530",
    # text
    "ink": "#e8edf3",
    "muted": "#aab4c2",
    "faint": "#8290a2",
    # lines
    "rule": "#242c38",
    "rule-strong": "#3a4657",
    # borders that carry meaning (inputs, focusable controls) must reach 3:1 as UI components;
    # hairline rules are decorative and use `rule`
    "ui-border": "#5b6e88",
    # the instrument accent: one cyan, used for focus, links, the live trace
    "accent": "#6fe3d0",
    "accent-dim": "#2d8f82",
    # verdicts: three hues, three shapes, three labels - never colour alone
    "fail": "#ff7d6e",
    "insufficient": "#f4c453",
    "pass": "#7de0a3",
    # spectra
    "hbo2": "#ff5f6d",
    "hb": "#4c8dff",
}

# (foreground token, background token, role, size class)
PAIRS = [
    ("ink", "bg-0", "body text", "normal"), ("ink", "bg-2", "body text on card", "normal"),
    ("muted", "bg-0", "secondary text", "normal"), ("muted", "bg-2", "secondary on card", "normal"),
    ("faint", "bg-0", "labels, captions", "normal"), ("faint", "bg-2", "labels on card", "normal"),
    ("faint", "bg-3", "labels on raised", "normal"),
    ("accent", "bg-0", "links, focus ring", "normal"), ("accent", "bg-2", "links on card", "normal"),
    ("fail", "bg-0", "FAIL label", "normal"), ("fail", "bg-2", "FAIL label on card", "normal"),
    ("insufficient", "bg-0", "INSUFFICIENT DATA label", "normal"), ("insufficient", "bg-2", "INSUFFICIENT on card", "normal"),
    ("pass", "bg-0", "PASS label", "normal"), ("pass", "bg-2", "PASS on card", "normal"),
    ("hbo2", "bg-0", "HbO2 trace legend", "normal"), ("hb", "bg-0", "Hb trace legend", "normal"),
    ("bg-0", "accent", "button text on accent", "normal"),
    ("rule-strong", "bg-0", "decorative rule vs ground (no requirement; recorded)", "ui"),
    ("ui-border", "bg-0", "non-text: input and control borders vs ground", "ui"),
    ("ui-border", "bg-2", "non-text: control borders on card", "ui"),
    ("bg-0", "ink", "button text on ink", "normal"),
]


def _lin(c: float) -> float:
    c /= 255
    return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4


def luminance(hexs: str) -> float:
    r, g, b = (int(hexs[i:i + 2], 16) for i in (1, 3, 5))
    return 0.2126 * _lin(r) + 0.7152 * _lin(g) + 0.0722 * _lin(b)


def ratio(fg: str, bg: str) -> float:
    a, b = luminance(fg), luminance(bg)
    hi, lo = max(a, b), min(a, b)
    return (hi + 0.05) / (lo + 0.05)


def main() -> int:
    rows = []
    for fg, bg, role, size in PAIRS:
        r = ratio(TOKENS[fg], TOKENS[bg])
        need = 3.0 if size in ("large", "ui") else 4.5
        rows.append({"fg": fg, "bg": bg, "role": role, "ratio": round(r, 2), "required": need,
                     "aa": r >= need, "aaa": r >= (4.5 if size in ("large", "ui") else 7.0)})
    css = [":root {"] + [f"  --{k}: {v};" for k, v in TOKENS.items()] + ["}"]
    front = paths.ROOT / "app" / "frontend" / "src"
    (front / "tokens.css").write_text(
        "/* Generated by scripts/design_tokens_contrast_phase8b.py - the ONLY place colours are defined.\n"
        "   Contrast ratios for every pair the interface uses are measured by the same\n"
        "   script and recorded in reports/phase8b_design.md. */\n" + "\n".join(css) + "\n",
        encoding="utf-8")
    out = {"tokens": TOKENS, "pairs": rows,
           "all_aa": all(r["aa"] for r in rows if not r["role"].startswith("decorative"))}
    (paths.INTERIM / "phase8b").mkdir(parents=True, exist_ok=True)
    (paths.INTERIM / "phase8b" / "contrast.json").write_text(json.dumps(out, indent=2), encoding="utf-8")
    for r in rows:
        print(f"{'AA ' if r['aa'] else 'FAIL'} {r['ratio']:5.2f}  {r['fg']:>13s} on {r['bg']:<6s} {r['role']}")
    print("all AA:", out["all_aa"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
