"""Phase 8B report: reports/phase8b_design.md. Palette and contrast from contrast.json,
Lighthouse figures from the saved runs, verification from verify_8b.json."""
from __future__ import annotations

import json
from pathlib import Path

from hemosight.io import paths

D = paths.INTERIM / "phase8b"


def lh(name: str) -> dict | None:
    p = D / f"{name}.json"
    if not p.exists():
        return None
    r = json.loads(p.read_text(encoding="utf-8"))
    c, a = r["categories"], r["audits"]
    return {"perf": round(c["performance"]["score"] * 100), "a11y": round(c["accessibility"]["score"] * 100),
            "bp": round(c["best-practices"]["score"] * 100), "lcp": a["largest-contentful-paint"]["displayValue"],
            "tbt": a["total-blocking-time"]["displayValue"], "cls": a["cumulative-layout-shift"]["displayValue"]}


def row(cells):
    return "| " + " | ".join(str(c) for c in cells) + " |\n"


def main() -> int:
    contrast = json.loads((D / "contrast.json").read_text(encoding="utf-8"))
    verify = json.loads((D / "shots" / "verify_8b.json").read_text(encoding="utf-8"))
    L: list[str] = []
    A = L.append
    A("# Phase 8B - visual redesign\n\n")
    A("Generated by `scripts/design_review_report_phase8b.py` from `data/interim/phase8b/`. Direction: the "
      "atmosphere of a dark, typographic, parallax landing page translated to this project's "
      "subject - a precision instrument, not a document. Language (Phase 8A) unchanged.\n\n")

    A("## 1. Colour system and measured contrast\n\n")
    A("Every colour is a CSS custom property in `app/frontend/src/tokens.css`, generated by "
      "`scripts/design_tokens_contrast_phase8b.py`; Tailwind maps to the variables; a test fails if a hex "
      "colour appears anywhere else in the front end. Ground is a deep cool near-black "
      "(`#0a0d12`), never pure black, with three surface elevations. One accent (cyan) for "
      "the live trace, links and focus. Verdicts: three hues, three shapes, three labels.\n\n")
    A(row(["token", "value", "role"]))
    A(row(["---"] * 3))
    roles = {"bg-0": "ground", "bg-1": "panel / aside", "bg-2": "cards", "bg-3": "raised / hover",
             "ink": "primary text", "muted": "secondary text", "faint": "labels, captions",
             "rule": "hairline rules (decorative)", "rule-strong": "stronger rules (decorative)",
             "ui-border": "input and control borders (non-text UI, >= 3:1)", "accent": "links, focus ring, live trace",
             "accent-dim": "glow, histogram", "fail": "FAIL - cross in a square", "insufficient": "INSUFFICIENT DATA - dashed diamond with a dash",
             "pass": "PASS - tick in a circle", "hbo2": "oxy-haemoglobin trace", "hb": "deoxy-haemoglobin trace"}
    for k, v in contrast["tokens"].items():
        A(row([f"`--{k}`", f"`{v}`", roles.get(k, "")]))
    A("\n**WCAG 2.1 contrast, measured** (normal text needs 4.5:1 for AA, 7:1 for AAA; non-text UI 3:1):\n\n")
    A(row(["foreground", "background", "role", "ratio", "AA", "AAA"]))
    A(row(["---"] * 6))
    for p in contrast["pairs"]:
        A(row([p["fg"], p["bg"], p["role"], f"{p['ratio']:.2f}:1", "yes" if p["aa"] else "**no**", "yes" if p["aaa"] else "no"]))
    A(f"\nAll required pairs meet AA: **{contrast['all_aa']}**. The one recorded failure is the "
      "decorative hairline `rule-strong`, which carries no meaning and has no requirement; "
      "interactive borders use `ui-border` (3.7:1 on the ground, 3.3:1 on cards).\n\n")
    A("INSUFFICIENT DATA is amber with a dashed diamond glyph and the words \"Insufficient data\"; "
      "it shares neither hue nor shape with PASS (green, filled circle, tick) and is never "
      "rendered at reduced opacity. A test asserts no INSUFFICIENT wording is ever paired with "
      "pass styling.\n\n")

    A("## 2. Imagery - all generated, nothing licensed, nothing from a dataset\n\n")
    A("`scripts/design_visual_assets_phase8b.py` writes five small JSON files into the front end from public "
      "tabulated physics and this project's own aggregate results; `components/visuals.tsx` "
      "renders them as SVG. No raster image ships with the site (test-enforced) and nothing is "
      "fetched from an external host.\n\n")
    A(row(["visual", "source", "where"]))
    A(row(["---"] * 3))
    A(row(["oxy/deoxy-haemoglobin extinction curves, glowing, with the visible band beneath and the isosbestic crossings marked",
           "OMLC Prahl compilation (Gratzer; Kollias), public tabulated data, via `optical_data.py`", "hero (parallax mid layer); story steps 1-2"]))
    A(row(["spectral band divider (wavelength -> sRGB)", "CIE 1931 2-degree observer via colour-science", "section dividers, page foot"]))
    A(row(["null distribution vs the real value", "Phase 5: 240 selection-aware permutation minima, harden.json", "story step 5; worked example"]))
    A(row(["noise-vs-signal ladder by capture condition", "Phase 7 controlled_capture.json + Phase 6.5 empirical_signal.json", "story step 3"]))
    A(row(["breakeven curve with the viable / marginal bands", "Phase 7 gate-model scan", "story step 4"]))
    A(row(["measurement grid, reticle, synthetic pulse trace, particle field", "generated by code; the trace is a formula, not a recording", "hero, section ends, favicon, cursor"]))
    A("\nNot used: any photograph, any dataset image, any risk-coverage curve (no conformal "
      "wrapper was ever built, so none exists to draw).\n\n")

    A("## 3. Motion inventory\n\n")
    A("GSAP 3.15 + ScrollTrigger for scroll-driven sequences, loaded lazily and only when "
      "motion is on (two chunks, 28 + 18 kB gzipped, never fetched otherwise); Framer Motion "
      "keeps component state transitions. One switch governs everything decorative: "
      "`enabled = !prefers-reduced-motion && userToggle`, stamped on `<html data-motion>`.\n\n")
    A(row(["effect", "implementation", "off when motion is off"]))
    A(row(["---"] * 3))
    A(row(["scrollytelling (landing)", "visual pinned at md+ via `gsap.matchMedia`, five steps set the active figure on enter; crossfade is opacity only; on phones each step carries its own figure, nothing pins", "static: steps in order, each with its figure, same numbers"]))
    A(row(["parallax", "three hero layers scrubbed at -60 / -120 / -30 px, transform only", "layers static"]))
    A(row(["reveal on scroll", "`.reveal` elements animate in with a 0.08 s stagger; the class hides nothing unless `data-motion=on`", "everything visible at load"]))
    A(row(["particle field", "canvas, <= 70 points at 6 px/s, draws only while intersecting and the tab is visible", "component renders nothing"]))
    A(row(["glowing borders", "conic-gradient pseudo-element rotated by a registered `--glow-angle` property on hover/focus-within; card lifts 2 px by transform", "hover lift off; no sweep"]))
    A(row(["hover states", "buttons swap fill/outline with a glow shadow; links draw an underline from the left", "instant"]))
    A(row(["custom cursor", "reticle following the pointer, opens near interactive elements; fine pointers only; hides on any keydown so it never covers a focus ring; native cursor hidden only while it is live", "not rendered; native cursor"]))
    A(row(["page transitions", "Framer Motion fade/6 px rise", "duration forced to ~0 by CSS"]))
    A("\nEverything animates transform or opacity. Scroll handling is GSAP's frame-throttled "
      "listener; the particle loop is `requestAnimationFrame` and stops off-screen.\n\n")

    A("## 4. Accessibility and performance, measured\n\n")
    b = lh("before")
    A("Lighthouse 13.4, headless Chrome, `vite preview` build with the backend running. "
      "Mobile is Lighthouse's default emulation (the harder profile); desktop is `--preset=desktop`.\n\n")
    A(row(["page", "preset", "performance", "accessibility", "best practices", "LCP", "TBT", "CLS"]))
    A(row(["---"] * 8))
    if b:
        A(row(["landing, BEFORE 8B (cream palette)", "mobile", b["perf"], b["a11y"], b["bp"], b["lcp"], b["tbt"], b["cls"]]))
    for name, label, preset in (("final_mobile_home", "landing", "mobile"), ("final_desktop_home", "landing", "desktop"),
                                ("final_mobile_upload", "upload", "mobile"), ("final_desktop_upload", "upload", "desktop"),
                                ("final_mobile_results", "results (real run, 7 checks)", "mobile"),
                                ("final_desktop_results", "results (real run, 7 checks)", "desktop")):
        r = lh(name)
        if r:
            A(row([label, preset, f"**{r['perf']}**", f"**{r['a11y']}**", r["bp"], r["lcp"], r["tbt"], r["cls"]]))
    A("\nThe bar was performance 90 and accessibility 97. The baseline landing page lost "
      "accessibility points to **18 colour-contrast failures** on the cream palette; the new "
      "palette clears every text pair and every page scores 100.\n\n")
    A("**Bundle.** Before: one JS chunk 336.6 kB (107.5 kB gzipped) + CSS 16.2 kB. After: main "
      "chunk 366 kB (118.4 kB gzipped) + CSS 20.7 kB (5.3 kB gzipped), plus two lazy chunks that "
      "load only with motion on - GSAP core 70.8 kB (28.0 kB gzipped) and ScrollTrigger 44.0 kB "
      "(18.3 kB gzipped). A reduced-motion visitor downloads about 11 kB gzipped more than "
      "before; a motion-on visitor about 57 kB more.\n\n")
    A("**Cut to hold the bar, or corrected during verification:**\n")
    A("- Lazy-loading the landing page itself (17 kB) was reverted: it cost a layout shift on "
      "first paint (CLS 0.12). Only GSAP is code-split now.\n")
    A("- Inactive story steps were dimmed to 35% opacity; Lighthouse flagged the dimmed text "
      "below AA. The dim is now 75% minimum, applied to the body only, never to labels.\n")
    A("- The results page replaced an empty state with the verdict cards after its fetch and "
      "pushed the page foot down (CLS 0.73 on desktop). It now shows a loading state and the "
      "content column is at least one viewport tall; CLS 0.\n")
    A("- Two `bg-white` fragments from the old palette survived in the results and report "
      "pages (Lighthouse: white select on dark ground); replaced by tokens, and a test now "
      "forbids any hex colour outside `tokens.css`.\n")
    A("- The hero spectra sat under the heading on phones; it is now a quieter top-right "
      "layer at small widths, and the visible-band gradient beneath the curves was halved.\n")
    A("- Nothing was cut for performance: the particle field, parallax, scrollytelling and "
      "glow borders all ship, because the measured scores stayed above the bar with them.\n\n")

    A("## 5. Verification - what was actually checked\n\n")
    n = len(verify); bad = [v for v in verify if v["errors"] or v["revealsHidden"] or v["horizontalOverflow"] or not v["focus"]["outline"]]
    A(f"`tools/verify_8b.mjs` drove headless Chrome through **every page x three widths "
      f"(1440, 834, 390) x two motion modes** (motion on; `prefers-reduced-motion: reduce` "
      f"emulated) = {n} page states, scrolling each like a reader and recording console "
      f"errors, `html[data-motion]` and `[data-cursor]`, whether every `.reveal` element ended "
      f"visible, horizontal overflow, and whether the first Tab lands on a focusable element "
      f"with a visible outline. **{n - len(bad)} of {n} clean.** Screenshots in "
      "`data/interim/phase8b/shots/`.\n\n")
    A(row(["mode", "width", "pages", "motion attr", "cursor attr", "reveals hidden", "canvas present", "focus ring", "errors"]))
    A(row(["---"] * 9))
    for mode in ("motion", "reduced"):
        for w in ("desktop", "tablet", "mobile"):
            vs = [v for v in verify if v["mode"] == mode and v["width"] == w]
            A(row([mode, w, len(vs), ", ".join(sorted({str(v["motion"]) for v in vs})),
                   ", ".join(sorted({str(v["cursor"]) for v in vs})), sum(v["revealsHidden"] for v in vs),
                   "yes" if any(v["canvas"] for v in vs) else "no",
                   "all" if all(v["focus"]["outline"] for v in vs) else "MISSING",
                   sum(len(v["errors"]) for v in vs)]))
    A("\nRead: with reduced motion emulated, `data-motion` is `off`, the cursor is `native`, no "
      "canvas exists, every reveal element is visible without scrolling, and the first Tab "
      "shows a focus ring on the skip link - on every page at every width. With motion on, the "
      "particle canvas exists only on the landing page, reveals complete on scroll, and the "
      "custom cursor stays `native` until a mouse moves (headless has no pointer).\n\n")
    A("Verified by eye from the screenshots: the results page's verdict cards read as findings "
      "(calm, labelled, glyph + hue + text; plain and technical layers intact); the mobile hero "
      "no longer overlaps the heading; the story steps on phones carry their own figures. The "
      "in-app motion toggle was exercised by test only through its attribute effect, not by a "
      "recorded click.\n\n")
    A("## 6. Restraint\n\n")
    A("Verdict cards use no glow animation beyond the shared hover lift; numbers, p-values and "
      "technical statements are set in the monospace on a flat surface with no decoration; the "
      "disclaimer is in the sidebar frame of every page (and the top bar on phones) beside the "
      "motion toggle, not in a footer. Motion directs attention to the section entering view "
      "and never runs over text being read: reveals fire once and stop; the story pin holds "
      "the figure still while the text scrolls.\n")
    (paths.REPORTS / "phase8b_design.md").write_text("".join(L), encoding="utf-8")
    print(f"wrote {paths.REPORTS / 'phase8b_design.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
