"""Phase 9C, Task 5: generate reports/phase9c_uncertainty.md.

Reads data/interim/phase9c/uncertainty.json directly, so no number in the report can
drift from the run that produced it.

    .\\.venv\\Scripts\\python.exe scripts\\parameter_uncertainty_report_phase9c.py
"""

from __future__ import annotations

import json

from hemosight.io import paths
from hemosight.simulation import uncertainty as U

IN = paths.INTERIM / "phase9c" / "uncertainty.json"
LABELS = {str(U.RESIDUAL_3935): "3.935 dE2000 - grey-world @25% FOV (the Phase 3 gate)",
          str(U.RESIDUAL_3456): "3.456 dE2000 - MOBIUS, 3 phones x 3 lighting (uncontrolled)",
          str(U.RESIDUAL_1062): "1.062 dE2000 - SBVPI studio (controlled)"}
SHORT = {str(U.RESIDUAL_3935): "3.935 (Phase 3 gate)",
         str(U.RESIDUAL_3456): "3.456 (uncontrolled)",
         str(U.RESIDUAL_1062): "1.062 (studio)"}


def row(cells) -> str:
    return "| " + " | ".join(str(c) for c in cells) + " |\n"


def main() -> int:
    if not IN.exists():
        print(f"missing {IN}; run scripts/parameter_uncertainty_propagation_phase9c.py first")
        return 1
    d = json.loads(IN.read_text(encoding="utf-8"))
    if not d.get("valid"):
        print("the run is marked invalid; not writing a report")
        return 1
    R = d["residuals"]
    L: list[str] = []
    A = L.append

    A("# Phase 9C - parameter uncertainty propagated into the gate result\n\n")
    A("Generated by `scripts/parameter_uncertainty_report_phase9c.py` from `data/interim/phase9c/uncertainty.json`.\n")
    A("Thresholds, prior, design size and the interpretation rule were **pre-declared in "
      "CLAUDE.md on 2026-09-20 before this ran**.\n\n")

    # ---------------------------------------------------------------- headline
    g = R[str(U.RESIDUAL_3935)]
    st = R[str(U.RESIDUAL_1062)]
    A("> ## THE RESULT\n>\n")
    A(f"> **The gate result is not a point. At the Phase 3 residual of 3.935 dE2000 the "
      f"haemoglobin MAE over the declared parameter prior is median **{g['median']:.2f} g/dL**, "
      f"95% interval **[{g['p2.5']:.2f}, {g['p97.5']:.2f}]**.** The recorded point estimate "
      f"**{g['point_estimate']:.3f} g/dL** sits at percentile {g['point_estimate_percentile']:.0f} "
      "percentile of that distribution and is retained everywhere it appears.\n>\n")
    A(f"> **{g['fraction_above_2.0'] * 100:.1f}% of the parameter space** exceeds the "
      f"pre-declared 2.0 g/dL NOT RECOVERABLE threshold. By the pre-declared rule - robust if "
      f"the entire 95% interval falls on one side - the imaging verdict is "
      f"**{'ROBUST' if g['robust_at_2.0'] else 'FRAGILE'}** to parameter uncertainty.\n>\n")
    A(f"> **The studio condition is the fragile one, as anticipated.** Median "
      f"{st['median']:.2f} g/dL, 95% [{st['p2.5']:.2f}, {st['p97.5']:.2f}] - the interval "
      f"spans **both** the 1.0 VIABLE boundary and the 2.0 NOT RECOVERABLE boundary, so its "
      f"MARGINAL verdict is **FRAGILE**: the parameter prior alone moves it across two bands.\n\n")

    # ---------------------------------------------------------------- 0. validity
    A("---\n\n## 0. Validity: the nominal parameters reproduce the record exactly\n\n")
    A("Pre-declared condition: if theta = nominal does not return the recorded point "
      "estimates, the run is invalid and reports nothing. The perturbation banks are "
      "regenerated in the original RNG order (seed 20260911) for this reason.\n\n")
    A(row(["residual", "source", "recorded g/dL", "reproduced g/dL", "|difference|"]))
    A(row(["---"] * 5))
    for k, v in d["reproduction"].items():
        A(row([f"{float(k):.3f}", v["label"], f"{v['recorded']:.6f}",
               f"{v['reproduced']:.6f}", f"{v['abs_diff']:.1e}"]))
    A("\nThe propagation therefore moves only the tissue parameters; the forward model, the "
      "inversion, the Hb grid, the trial count and the illuminant perturbation are the gate's "
      "own. A test asserts the parameterised forward equals `forward.layered_reflectance` at "
      "nominal to 1e-12.\n\n")

    # ---------------------------------------------------------------- 1. prior
    A("---\n\n## 1. The parameter prior\n\n")
    A("Each parameter is labelled by whether a downloaded file or an independent measurement "
      "backs it. Where none does, the range is deliberately generous rather than convenient, "
      "and is at least as wide as the Phase 3 Task 4 tolerance envelope (BVF +/-30%, thickness "
      "0.8-2.0x, oxygenation across its whole range).\n\n")
    A(row(["parameter", "nominal", "prior", "status", "justification"]))
    A(row(["---"] * 5))
    for p in d["params"]:
        rng = (f"log-U[{p['lo']:g}, {p['hi']:g}]" if p["log_uniform"]
               else f"U[{p['lo']:g}, {p['hi']:g}]")
        A(row([p["label"], f"{p['nominal']:g}", rng, p["status"], p["justification"]]))
    n_uns = sum(1 for p in d["params"] if p["status"] == "UNSOURCED")
    A(f"\n**{n_uns} of {len(d['params'])} parameters are UNSOURCED.** Held fixed and out of "
      "scope, stated: the D65 illuminant and the CIE 1931 observer as camera proxy (a "
      "capture-side limitation, already logged, and the thing the measured residuals stand in "
      "for), and the haemoglobin and water spectra (file-backed since Phase 3.5 Task 0).\n\n")

    # ---------------------------------------------------------------- 2. distributions
    A("---\n\n## 2. The gate result as a distribution\n\n")
    A(f"Sobol/Saltelli design, base N = {d['n_base']}, {d['n_eval']} model evaluations per "
      f"residual; the distribution below is the {d['n_mc']}-row A+B Monte Carlo sample. "
      "Percentile 95% intervals.\n\n")
    A(row(["residual", "point estimate", "median", "95% interval", "fraction > 2.0",
           "fraction < 1.0", "verdict under the rule"]))
    A(row(["---"] * 7))
    for k in (str(U.RESIDUAL_3935), str(U.RESIDUAL_3456), str(U.RESIDUAL_1062)):
        s = R[k]
        A(row([LABELS[k], f"{s['point_estimate']:.3f}", f"{s['median']:.2f}",
               f"[{s['p2.5']:.2f}, {s['p97.5']:.2f}]", f"{s['fraction_above_2.0']:.3f}",
               f"{s['fraction_below_1.0']:.3f}", s["rule"]]))
    A("\n**Conditional on a sparsely pigmented conjunctiva (melanin volume fraction <= 0.005), "
      "which is the physiologically expected case for this tissue:**\n\n")
    A(row(["residual", "median", "95% interval", "fraction > 2.0", "n draws"]))
    A(row(["---"] * 5))
    for k in (str(U.RESIDUAL_3935), str(U.RESIDUAL_3456), str(U.RESIDUAL_1062)):
        c = R[k]["conditional_melanin_le_0.005"]
        A(row([SHORT[k], f"{c['median']:.2f}", f"[{c['p2.5']:.2f}, {c['p97.5']:.2f}]",
               f"{c['fraction_above_2.0']:.3f}", c["n"]]))
    if d.get("figure"):
        A("\nHistograms: `reports/figures/phase9c/gate_mae_histograms.png` (regenerated by the "
          "script; figures are gitignored).\n")
    A("\n")

    # ---------------------------------------------------------------- 3. Task 2
    A("---\n\n## 3. The question that decides the verdict\n\n")
    for k in (str(U.RESIDUAL_3935), str(U.RESIDUAL_3456)):
        s = R[k]
        A(f"**{LABELS[k]}.** {s['fraction_above_2.0'] * 100:.1f}% of the prior is above "
          f"2.0 g/dL. The 95% interval [{s['p2.5']:.2f}, {s['p97.5']:.2f}] lies "
          f"{'entirely above' if s['p2.5'] > 2.0 else 'across'} the threshold, so the verdict is "
          f"**{'ROBUST' if s['robust_at_2.0'] else 'FRAGILE'}**. ")
        b = s["below_2.0"]
        if b["n"] == 0:
            A("**No draw in the sample falls below 2.0 g/dL.**\n\n")
        else:
            A(f"{b['n']} of {s['n']} draws ({b['fraction'] * 100:.2f}%) fall below 2.0. "
              f"The most favourable single draw gives {s['min_draw']['mae']:.2f} g/dL "
              f"({s['min_draw']['band']}); where it sits in each prior is listed below.\n\n")
            A(row(["parameter", "value at the most favourable draw", "position in its prior",
                   f"mean position across the {b['n']} sub-2.0 draws"]))
            A(row(["---"] * 4))
            mq = b.get("mean_quantile_in_prior", {})
            for p in d["params"]:
                v = s["min_draw"]["theta"][p["key"]]
                q = s["min_draw"]["quantile_in_prior"][p["key"]]
                A(row([p["label"], f"{v:.4g}", f"{q:.2f}",
                       f"{mq.get(p['key'], float('nan')):.2f}" if mq else "-"]))
            extreme = [p["label"] for p in d["params"]
                       if mq and (mq[p["key"]] > 0.75 or mq[p["key"]] < 0.25)]
            A(f"\n**How plausible is that?** Not very. Reaching below 2.0 g/dL takes "
              f"{len(extreme)} of {len(d['params'])} parameters sitting simultaneously in the "
              f"outer quarter of their own generous ranges ({', '.join(extreme)}), and even the "
              f"single most favourable draw in {s['n']} lands at "
              f"{s['min_draw']['mae']:.2f} g/dL - **MARGINAL, never VIABLE**. The prior was "
              f"chosen to be generous; no draw anywhere in it makes uncontrolled capture "
              f"viable, and the best it can do is a corner of parameter space that would itself "
              f"need justifying.\n\n")

    s = R[str(U.RESIDUAL_1062)]
    A(f"**{LABELS[str(U.RESIDUAL_1062)]} - the fragile one.** The recorded point estimate "
      f"{s['point_estimate']:.3f} g/dL sat 0.04 above the VIABLE boundary, and it is the "
      "result most exposed to parameter uncertainty. It is: median "
      f"{s['median']:.2f}, 95% [{s['p2.5']:.2f}, {s['p97.5']:.2f}]. "
      f"**{s['fraction_below_1.0'] * 100:.1f}% of the prior is VIABLE (< 1.0), "
      f"{s['fraction_in_1_2'] * 100:.1f}% is MARGINAL, and {s['fraction_above_2.0'] * 100:.1f}% "
      "is NOT RECOVERABLE.** The honest reading is that under parameter uncertainty the studio "
      "condition does not have a band: it has a distribution across all three. Its MARGINAL "
      "label is a property of the nominal parameter choice as much as of the capture "
      "condition.\n\n")

    # ---------------------------------------------------------------- 4. sensitivity
    A("---\n\n## 4. Which assumptions drive the result\n\n")
    A("Sobol total-effect indices (Jansen estimator, 200-resample bootstrap CIs), ranked, at "
      "the Phase 3 residual. The total index includes every interaction a parameter takes part "
      "in, which is the right quantity here because the forward model is strongly "
      "non-additive.\n\n")
    si = d["sobol"][str(U.RESIDUAL_3935)]
    A(row(["rank", "parameter", "status", "total index ST", "95% CI", "first-order S1"]))
    A(row(["---"] * 6))
    for i, r in enumerate(si["ranked"], 1):
        A(row([i, r["label"], r["status"], f"{r['ST']:.3f}",
               f"[{r['ST_ci'][0]:.3f}, {r['ST_ci'][1]:.3f}]", f"{r['S1']:.3f}"]))
    A("\n**One-at-a-time swing** (each parameter alone across its prior, others at nominal), "
      "at the Phase 3 residual - the same ranking question asked without interactions:\n\n")
    oat = d["oat"][str(U.RESIDUAL_3935)]
    names = {p["key"]: p["label"] for p in d["params"]}
    A(row(["parameter", "swing g/dL", "min", "max"]))
    A(row(["---"] * 4))
    for k, v in sorted(oat.items(), key=lambda kv: -kv[1]["swing"]):
        A(row([names.get(k, k), f"{v['swing']:.2f}", f"{min(v['values']):.2f}",
               f"{max(v['values']):.2f}"]))
    A("\n**Why five parameters swing by exactly zero, so the table is not misread.** The two "
      "melanin *shape* parameters (exponent k, amplitude scale) multiply the melanin volume "
      "fraction, and the gate's nominal melanin fraction is **0** - so at nominal they have "
      "nothing to act on. Their small Sobol totals say the same thing: they matter only where "
      "melanin is present, and then only through it. Epithelium thickness and the water "
      "fraction are genuinely negligible (a 32 um layer contributes almost no double-pass "
      "attenuation, and water is nearly transparent across 450-700 nm), and the tarsal plate "
      "sits below an attenuation floor that its thickness cannot change. **The one-at-a-time "
      "and Sobol rankings disagree on the leader** - epithelium BVF one-at-a-time, deep-layer "
      "weight by total index - because the one-at-a-time sweep passes through the degenerate "
      "point bvf_epi = 0, where the modelled colour stops depending on haemoglobin at all "
      "(MAE 10.7 g/dL) and which the joint sample almost never visits. The total index is the "
      "quantity to trust; the swing column is shown because it is the form Phase 3 Task 4 "
      "used.\n\n")

    # ---------------------------------------------------------------- 4b. mechanism + recommendation
    m = d["mechanism"]
    A("### 4b. What the ranking means, and the mechanism behind it\n\n")
    A(f"The gate MAE is, to a very good approximation, **colour noise divided by colour signal "
      f"per g/dL**: across {m['n_probe']} sampled parameter vectors the rank correlation between "
      f"the gate MAE and the chromaticity distance the model puts between Hb 4 and Hb 18 g/dL is "
      f"**{m['spearman_mae_vs_chroma_span']:+.2f}**. That span itself varies by an order of "
      f"magnitude over the prior (median {m['chroma_span_median']:.4f}, 95% "
      f"[{m['chroma_span_p2.5']:.4f}, {m['chroma_span_p97.5']:.4f}]). So the ranking is not "
      "mysterious: a parameter matters here exactly to the extent that it changes how much the "
      "modelled colour moves per g/dL. This is the same mechanism Phase 3 recorded - "
      "signal-to-noise - now measured across the prior instead of at one point.\n\n")
    A("**On the expectation that melanin dominates: the analysis only partly supports it, and "
      "the honest ranking is different.**\n\n")
    mel = next(r for r in si["ranked"] if r["key"] == "melanin")
    mel_rank = [r["key"] for r in si["ranked"]].index("melanin") + 1
    top = si["ranked"][0]
    st_si = d["sobol"][str(U.RESIDUAL_1062)]
    mel_st_rank = [r["key"] for r in st_si["ranked"]].index("melanin") + 1
    A(f"* At the Phase 3 residual melanin volume fraction ranks **{mel_rank} of "
      f"{len(si['ranked'])}** by total index (ST {mel['ST']:.3f}), behind "
      f"**{top['label']}** (ST {top['ST']:.3f}) and epithelium blood volume fraction. At the "
      f"studio residual it ranks **{mel_st_rank}**, the largest single contributor "
      f"(ST {st_si['ranked'][0]['ST']:.3f}) - melanin matters most precisely where the capture "
      "noise is smallest, which is where a real deployment would want to operate.\n")
    A(f"* Phase 3's finding that melanin is the most consequential assumption was measured in "
      "the **mismatch** setting (section 5), where a model calibrated at zero melanin meets a "
      "pigmented subject. That result stands and is reproduced here. What this phase adds is "
      "that in the **self-consistent** setting - which is the one the gate reports - melanin is "
      "one of three or four comparable drivers, not the dominant one.\n")
    A(f"* The single largest driver at the gate residual is **{top['label']}**, a "
      f"**{top['status']}** modelling constant with no citation at all: the factor 0.6 by which "
      "deeper layers are down-weighted in `forward.layered_reflectance`. The second is the "
      "epithelial blood volume fraction, also unsourced. **The result is therefore most "
      "sensitive to the parts of the model that were never sourced, which is the finding this "
      "phase exists to expose.**\n\n")
    A("**The recommendation the analysis does support.** For anyone continuing this line of "
      "work, a measured melanin absorption curve for conjunctival tissue - amplitude and "
      "exponent, with inter-individual spread, replacing the fitted power law - is the single "
      "most valuable *spectroscopic* measurement, because melanin leads the ranking in the "
      "controlled-capture regime and is the mechanism by which the method would be biased by "
      "skin tone (N5). But it is **not** the most valuable measurement overall at the "
      "uncontrolled residual: there, two unsourced structural quantities - the deep-layer "
      "weighting and the epithelial blood volume fraction - matter as much or more, and the "
      "first of them is not a tissue property at all but an artefact of how this model "
      "combines layers. Fixing a modelling convention costs nothing and would remove the "
      "largest single term.\n\n")
    A(f"**A limitation that belongs with these numbers.** At the nominal parameters "
      f"{m['saturated_fraction_at_nominal'] * 100:.0f}% of the modelled (Hb, wavelength) grid is "
      f"saturated at reflectance >= 0.999, and across the prior the median is "
      f"{m['saturated_fraction_median'] * 100:.0f}%. Saturation compresses the colour signal and "
      "is part of why the span varies so widely. This is a property of the diffusion "
      "approximation as the gate already used it, not something the prior introduced - but it "
      "means the absolute MAE values inherit a known model deficiency, and the interval should "
      "be read as the spread this model produces, not as the spread of the physical truth.\n\n")

    # ---------------------------------------------------------------- 5. mismatch
    A("---\n\n## 5. The mismatch variant, reported separately and never pooled\n\n")
    A("Section 2 is **self-consistent**: the inversion knows the tissue it is inverting. That "
      "isolates the question this phase asks - does the gate's conclusion survive not knowing "
      "the tissue parameters. A second question, which Phase 3 Task 4 asked, is what happens "
      "when the inversion assumes nominal tissue and the truth is elsewhere. Those numbers are "
      "far larger and are kept apart so the two are never confused.\n\n")
    A(row(["variant", "median", "95% interval", "fraction > 2.0", "median | melanin <= 0.005"]))
    A(row(["---"] * 5))
    for k, v in d["mismatch"].items():
        A(row([f"LUT at nominal, truth at theta, residual {k}", f"{v['median']:.2f}",
               f"[{v['p2.5']:.2f}, {v['p97.5']:.2f}]", f"{v['fraction_above_2.0']:.3f}",
               f"{v['conditional_melanin_le_0.005']['median']:.2f}"]))
    A("\nThis reproduces the Phase 3 Task 4 finding in distributional form: a model calibrated "
      "on assumed tissue parameters and applied to a real subject whose parameters differ is "
      "wrong by very much more than the capture noise contributes. **It is not evidence about "
      "the gate**, which is why it is not pooled with section 2.\n\n")
    return finish(L, d)


def finish(L: list[str], d: dict) -> int:
    A = L.append
    # ---------------------------------------------------------------- 6. Task 4
    A("---\n\n## 6. Task 4 - the outstanding verification item\n\n")
    A("The VERIFICATION REQUIRED banner on layer thicknesses and blood volume fractions has "
      "stood since Phase 3 because Efron 2009 [5] and Zhivov 2006 [6] were never obtained. "
      "With network access both were sought on 2026-09-20.\n\n")
    A("**Efron 2009 - OBTAINED, and it does not contain the numbers attributed to it.** The "
      "paper itself is subscription-only (Optom Vis Sci 86(11):E1303-8, PMID 19770809; Europe "
      "PMC `isOpenAccess: N`). The same study - same 11 healthy participants, same instrument, "
      "same tissue, abstract matching the published one - is a chapter of the open-access QUT "
      "master's thesis it came from (Al Dossari M, *Confocal microscopic examination of the "
      "conjunctiva*, QUT ePrints 18316), which was downloaded and read in full. Its palpebral "
      "chapter reports **no thickness in micrometres for any layer**: the epithelium \"appears "
      "to be only two or three cell-layers deep\", the stroma is described as \"thin\" and the "
      "tarsal plate as \"dark and amorphous\", all qualitative. The thesis's only thickness "
      "measurement, **32.9 +/- 1.1 um, is of the BULBAR conjunctival epithelium** - a different "
      "tissue, in a different chapter, from the companion bulbar study. It also states "
      "plainly that \"it is therefore not possible to determine the overall thickness of the "
      "conjunctiva using this (or any other) technique with any degree of certainty\". No "
      "blood volume fraction appears anywhere in it.\n\n")
    A("**Zhivov 2006 - NOT OBTAINED.** The Ocular Surface 4(2):81-93, PMID 16681079, DOI "
      "10.1016/s1542-0124(12)70030-7. Europe PMC: not open access, not in EPMC, no PDF. "
      "OpenAlex: `oa_status: closed`, `any_repository_has_fulltext: false`. No author manuscript "
      "or repository copy was found. It is a review of confocal microscopy of the ocular "
      "surface; its abstract contains no numeric thickness.\n\n")
    A("**Consequence: the banner is KEPT, and strengthened.** It previously said the values "
      "\"could not be verified against the source\". It can now say something more exact and "
      "worse: **for Efron 2009 the source was read and does not contain them.** The stromal "
      "thickness (200 um), tarsal-plate thickness (800 um) and all three blood volume fractions "
      "have no identified source, and the 32 um epithelial thickness is corroborated by Li et "
      "al. 2015 (OCT, 34.0 +/- 5.8 um, palpebral) - which remains the only sourced thickness in "
      "the model and is why it is the only parameter here labelled SOURCED. A correction is "
      "logged; the citation is not removed, because the paper is still the source of the "
      "*qualitative* layer structure the model uses.\n\n")
    A("Because no value was replaced, there is **no narrowed-prior re-run to report beside the "
      "assumed-range one**. The assumed ranges in section 1 are the result. Had Efron 2009 "
      "contained the thicknesses, the stroma and tarsal priors would have narrowed - and "
      "section 4 shows what that would have been worth: stroma thickness ranks mid-table and "
      "tarsal-plate thickness near the bottom, so narrowing them would have moved the interval "
      "very little. The parameters that dominate are not the ones the banner is about.\n\n")

    # ---------------------------------------------------------------- 7. consequences
    R = d["residuals"]
    g = R[str(U.RESIDUAL_3935)]
    u = R[str(U.RESIDUAL_3456)]
    st = R[str(U.RESIDUAL_1062)]
    A("---\n\n## 7. What changes on the record\n\n")
    A("**The imaging refutation is strengthened, and should be restated as robust to parameter "
      "uncertainty.** At both uncontrolled residuals the entire 95% interval lies above the "
      f"pre-declared 2.0 g/dL threshold ({g['p2.5']:.2f} and {u['p2.5']:.2f} at the lower bound), "
      f"and {g['fraction_above_2.0'] * 100:.1f}% / {u['fraction_above_2.0'] * 100:.1f}% of the "
      "prior is NOT RECOVERABLE. No physically plausible combination of the unsourced "
      "parameters rescues uncontrolled capture. The verdict did not depend on the fixed "
      "parameter values.\n\n")
    A("**The controlled-capture result is fragile and must be reported as such.** Phase 7 "
      f"recorded {st['point_estimate']:.3f} g/dL, MARGINAL, sitting 0.04 g/dL above the VIABLE "
      f"boundary. Under the prior it is median {st['median']:.2f}, 95% "
      f"[{st['p2.5']:.2f}, {st['p97.5']:.2f}] - spanning VIABLE, MARGINAL and NOT RECOVERABLE. "
      "**This is a limitation on a result the project already called MARGINAL, not on the "
      "central refutation**, but it is a real weakening of the one imaging number that was "
      "close to a favourable band, and the write-up must say so plainly rather than quoting "
      "1.04 alone.\n\n")
    A("**Every appearance of the gate number now carries its interval**, with the point "
      "estimate retained and a pointer to this report: `CLAUDE.md` (CURRENT STATE, the section 2 "
      "status table rows 3 and 8, and the Phase 3 row of the phase table), "
      "`reports/final_results.md` (master table row 3), `reports/phase3_simulation.md` (the "
      "headline gate box), `reports/phase7.md` (the gate table and the outcome-B boundary "
      "reading), and the front end's case study (`Landing.tsx`) and pre-registration worked "
      "example (`PreReg.tsx`). **Nothing was deleted.**\n\n")
    A("**One target named in the brief turned out not to exist, and is recorded rather than "
      "glossed.** The gate number does not appear anywhere in the audit package: the eight "
      "checks in `src/hemosight/audit/` carry provenance strings citing Phases 1, 4, 4.5 and 5 "
      "(demographic baselines, MI ceilings, duplicate overlap, permutation, seeds, subgroups), "
      "because the harness audits a claimed model's predictions and has no simulation stage. "
      "There was therefore nothing to update there, and no provenance string was edited to "
      "manufacture a mention.\n\n")
    A("**What this does not establish.** The interval is the spread this forward model produces "
      "under a declared prior over its own parameters. It is not a confidence interval on a "
      "measurement, it does not cover structural error in the diffusion approximation or the "
      "three-layer decomposition, and it holds the illuminant and camera proxy fixed. A wider "
      "model class would widen it further; nothing here suggests it would narrow it.\n\n")
    return write_out(L, d)


def write_out(L: list[str], d: dict) -> int:
    (paths.REPORTS / "phase9c_uncertainty.md").write_text("".join(L), encoding="utf-8")
    print(f"wrote {paths.REPORTS / 'phase9c_uncertainty.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
