"""Generate `reports/phase9e_boundaries.md` from the Phase 9E artefacts.

Every number is read from `data/interim/phase9e/` (and from Phase 9C/9D where the
report restates them), never retyped, so the report cannot drift from the evidence.

    .\\.venv\\Scripts\\python.exe scripts\\phase9e_report.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from hemosight.io import paths   # noqa: E402

I = paths.INTERIM
DST = paths.REPORTS / "phase9e_boundaries.md"


def load(rel):
    p = I / rel
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def row(cells):
    return "| " + " | ".join(str(c) for c in cells) + " |\n"


def direction_label(k: str) -> str:
    return k.replace("cross_site_", "").replace("_to_", " -> ")


def pct(x):
    return f"{100 * x:.0f}%"


REQ_LABEL = {
    "imaging_screening_specificity": "imaging screening, within site - specificity at matched sensitivity",
    "imaging_screening_sensitivity": "imaging screening, within site - sensitivity at matched specificity",
    "cross_site_italy_to_india": "cross-site **italy -> india** - specificity at matched sensitivity",
    "cross_site_india_to_italy": "cross-site **india -> italy** - specificity at matched sensitivity",
    "ppg_auroc": "PPG screening - AUROC vs the best demographic baseline",
}
REQ_ORDER = ["cross_site_italy_to_india", "cross_site_india_to_italy",
             "imaging_screening_specificity", "imaging_screening_sensitivity",
             "ppg_auroc"]


def main() -> int:
    g = load("phase9e/guided_capture.json")
    q = load("phase9e/required_n.json")
    xi = load("phase9e/cross_site_intervals.json")
    pw = (load("phase9d/power.json") or {}).get("arms", {})
    if not (g and q and xi):
        print("missing Phase 9E artefacts - run the three phase9e_*.py scripts first")
        return 1
    L: list[str] = []
    A = L.append

    A("# Phase 9E - the project's boundaries, stated precisely\n\n")
    A("Generated by `scripts/phase9e_report.py` from `data/interim/phase9e/`. "
      "**Everything this phase was allowed and not allowed to do was declared in "
      "CLAUDE.md and committed (`f4a3fc0`) before any script here ran** - the "
      "pre-declaration is verbatim in `docs/archive/phase9e_predeclaration.md`.\n\n")
    A("This phase builds no model, collects no data and **changes no verdict**. It "
      "names three things the record left implicit: the capture regime a real product "
      "uses and this project never measured; the sample a confirmatory study would "
      "need; and the statements that claimed more precision, or more absoluteness, "
      "than the evidence behind them.\n\n")

    # ------------------------------------------------------------------ headline
    u = g["headline_uncertainty"]
    lo = g["bracketing_measurements"]["lower"]["residual_dE2000"]
    hi = g["bracketing_measurements"]["upper"]["residual_dE2000"]
    it = q["required"]["cross_site_italy_to_india"]
    A("> ## The three boundaries, in one screen\n>\n"
      "> **A. The guided-capture gap.** A deployed screening app captures with one "
      "phone in one session behind a framing overlay and a quality gate. That regime "
      f"sits between two measured conditions - {hi:.3f} and {lo:.3f} dE2000 - **and is "
      "the one regime this project did not measure.** It is also exactly the interval "
      "in which the gate crosses out of NOT RECOVERABLE, and exactly where Phase 9C "
      "found the verdict fragile. It cannot be closed here. It is recorded as a named "
      "boundary and the **primary future-work item**.\n>\n"
      f"> **B. What a confirmatory study would need.** The cross-site failure is a "
      f"**composition** problem, not a sample-size one. `italy_to_india` estimates "
      f"specificity on **{it['n_carrier_observed']} non-anaemic subjects** and needs "
      f"about **{it['headline_required_carrier_80']:.0f}** - a ~"
      f"{it['headline_required_total_at_observed_prevalence_80']:.0f}-person test site "
      f"at that direction's prevalence, against {it['n_test_observed']} here.\n>\n"
      "> **C. What the record claimed too precisely.** Cross-site rates were quoted "
      "bare; underpowered nulls were written as absences; the studio gate figure was "
      "quoted without its interval. All three are corrected. **The two regression arms "
      "are ADEQUATELY POWERED and keep their full strength** - calibration runs in both "
      "directions.\n\n")

    # ================================================================ PART A
    A("---\n\n## Part A - the guided-capture gap\n\n")
    A("### What was measured, and what a product actually does\n\n")
    A("Phase 7 measured the within-subject residual colour error under three capture "
      "conditions. A deployed app operates in none of them:\n\n")
    A(row(["capture condition", "residual dE2000", "measured?",
           "what it corresponds to"]))
    A(row(["---"] * 4))
    A(row(["MOBIUS, 3 phones x 3 lighting", "3.456", "**yes**",
           "photographs taken however they happen to be taken"]))
    A(row(["MOBIUS, one phone + one lighting cell, gaze varying", f"{hi:.3f}", "**yes**",
           "the same device and light, but nothing controlling how the shot is framed"]))
    A(row(["**guided capture**", f"*{g['headline_point']['residual_dE2000']:.3f} "
           "(interpolated)*", "**NO**",
           "*one phone, one session, a live overlay enforcing framing and distance, and "
           "a quality gate rejecting blurred or badly exposed frames before the "
           "shutter*"]))
    A(row(["SBVPI studio rig", f"{lo:.3f}", "**yes**",
           "a fixed rig, which no screening deployment has"]))
    A("\n**Why this gap is the uncomfortable one.** It is not merely an untested "
      "condition; it is the condition where the answer is closest to changing. The gate "
      "crosses from NOT RECOVERABLE into MARGINAL inside this interval, and Phase 9C "
      "measured the studio verdict at its lower end as FRAGILE - "
      f"{pct(0.271)} of the parameter prior VIABLE, {pct(0.359)} MARGINAL, "
      f"{pct(0.370)} NOT RECOVERABLE. **The regime where real products operate is the "
      "one regime this project did not measure, and it is the one where the answer is "
      "closest to changing.**\n\n")

    A("### It is not closed here, and it cannot be\n\n")
    why = g["boundary_statement"]["why_it_cannot_be_closed_here"]
    A(f"{why[0].upper()}{why[1:]}. "
      "This is stated as a permanent boundary of the claim, not as a task deferred to a "
      "later phase of this project. There is no later phase in which it becomes "
      "possible.\n\n")

    A("### The interpolation, and what it is not\n\n")
    A("**It is an interpolation between two measured points. It is not a measurement of "
      "guided capture, and nothing in this repository should ever read as though it "
      f"were.** The headline point is the geometric mean of the bracketing pair, "
      f"**{g['headline_point']['residual_dE2000']:.3f} dE2000**, fixed in the "
      "pre-declaration before the gate was run at it. Fresh perturbation banks were "
      "drawn (seed "
      f"{g['bank_seed']}) because no original RNG order exists at a residual nobody "
      "measured, and **the two measured anchors were re-run on those same fresh banks**: "
      f"they land within **{g['bank_draw_check']['max_abs_difference_from_recorded']:.3f} "
      "g/dL** of their recorded values, so the interpolated points are not an artefact "
      "of a different random draw.\n\n")
    A(row(["residual dE2000", "status", "gate MAE g/dL (nominal theta)", "band"]))
    A(row(["---"] * 4))
    for r in g["gate_curve"]:
        st = ("**MEASURED anchor**" if r["is_measured_anchor"]
              else "*interpolated (headline)*" if r["is_headline"] else "*interpolated*")
        A(row([f"{r['residual_dE2000']:.3f}", st, f"{r['mae_g_dl']:.3f}", r["band"]]))
    A("\n**The interval, not just the point.** The Phase 9C prior over the forward "
      "model's 14 fixed tissue parameters was propagated at the headline point using "
      "**Phase 9C's own 2,048 prior draws**, so the interval is directly comparable to "
      "the recorded ones. The upper bracket, which had no interval on record, was "
      "propagated too:\n\n")
    A(row(["residual", "status", "point (nominal)", "median", "95% interval",
           "VIABLE / MARGINAL / NOT RECOVERABLE", "rule"]))
    A(row(["---"] * 7))
    for k, s in g["uncertainty"].items():
        A(row([f"{float(k):.3f}",
               "measured" if s["is_measured_residual"] else "*interpolated*",
               f"{s['point_estimate_at_nominal']:.3f}", f"{s['median']:.2f}",
               f"[{s['p2.5']:.2f}, {s['p97.5']:.2f}]",
               f"{pct(s['fraction_below_1.0'])} / {pct(s['fraction_in_1_2'])} / "
               f"{pct(s['fraction_above_2.0'])}", s["rule"]]))
    A("\n**What the interpolation says, honestly.** At nominal parameters the whole "
      "bracketing interval is MARGINAL and tips into NOT RECOVERABLE at its "
      f"uncontrolled end. Under the prior the headline point is median {u['median']:.2f} "
      f"g/dL - **above the 2.0 line** - with {pct(u['fraction_above_2.0'])} of the prior "
      f"NOT RECOVERABLE and only {pct(u['fraction_below_1.0'])} VIABLE; it is "
      f"{u['rule']}. And the ceiling is hard: **VIABLE requires a residual below "
      f"{g['interval_verdict']['residual_required_for_VIABLE']:.3f} dE2000, which is "
      "below the best measured condition in the entire project - a studio rig. No point "
      "in the guided-capture interval reaches VIABLE, including its most favourable "
      "end.** Guided capture plausibly lands MARGINAL at nominal parameters; it does not "
      "plausibly land VIABLE.\n\n")

    A("### What evidence would settle it\n\n")
    A("Stated so that someone who *can* collect data knows exactly what to collect, and "
      "so that the result would move the verdict in **either** direction rather than "
      "only the favourable one.\n\n")
    A(row(["", "specification"]))
    A(row(["---", "---"]))
    A(row(["**capture protocol**",
           "One phone model. One session per subject. A live on-screen overlay "
           "enforcing framing and camera-to-eye distance, and an automatic quality gate "
           "rejecting blurred or badly exposed frames before the shutter - i.e. the "
           "protocol a deployed app would ship, not a laboratory approximation of it. "
           "Ambient illumination left uncontrolled, because deployment cannot control "
           "it."]))
    A(row(["**the measurement**",
           "The same quantity Phase 7 measured, computed the same way: the "
           "**within-subject spread (mean pairwise CIEDE2000) of segmented scleral "
           "colour across repeat captures of the same person**, under the best of {no "
           "correction, grey-world full frame, grey-world 25% crop}. Repeat captures "
           "within one session are required - a single image per subject yields no "
           "within-subject residual, which is why Eyes-Defy could not supply this."]))
    A(row(["**sample**",
           "At least 3 repeat captures for each of >= 30 subjects, so the per-subject "
           "spread is estimated on more than a pair; subjects spanning the skin-tone "
           "range, because melanin is the 1st-ranked sensitivity at the studio residual "
           "(Phase 9C). This is a measurement of capture variability, not of "
           "haemoglobin, so **no blood draw is needed** - which is what makes it far "
           "cheaper than the confirmatory study in Part B."]))
    A(row(["**result that WEAKENS the refutation**",
           f"A residual **below {g['interval_verdict']['residual_required_for_VIABLE']:.3f} "
           "dE2000**, which would put the gate in VIABLE at nominal parameters and make "
           "the refutation specific to uncontrolled and semi-controlled capture. Note "
           "this is below the studio rig's measured residual, so it would be a genuinely "
           "surprising result."]))
    A(row(["**result that STRENGTHENS it**",
           f"A residual **at or above {hi:.3f} dE2000** - i.e. guided capture buying "
           "nothing over the same phone and lighting with gaze varying - which would put "
           "the gate in NOT RECOVERABLE and make the refutation general to photographs."]))
    A(row(["**result that leaves it where it is**",
           "Anything in between, i.e. MARGINAL, which the interpolation says is the "
           "likeliest outcome. **This is the expected result and it would still not make "
           "the arm deployable**, because MARGINAL does not beat site + sex + age and "
           "because the binding failure is cross-site transfer (Part B), which a "
           "single-site capture study does not address."]))
    A("\n**And the honest caveat on all of the above.** Even a VIABLE calibration "
      "residual would not settle the arm. Phase 6.5 measured a **between-subject** "
      "conjunctival colour term of ~4.5 dE2000 at fixed haemoglobin, sex, age and site - "
      "a second noise source the gate model never contained and that no amount of "
      "capture control removes. Capture control addresses one of the two terms.\n\n")

    # ================================================================ PART B
    A("---\n\n## Part B - what a confirmatory study would need\n\n")
    A("Phase 9D found three comparisons UNDERPOWERED and stopped there. An UNDERPOWERED "
      "verdict without a required n is a complaint; with one it is a specification. "
      "Phase 9D's MDEs were **reproduced before any new number was computed** "
      "(`scripts/phase9e_required_n.py` asserts it), exactly as Phase 9D reproduced "
      "Phase 9A's.\n\n")

    A("### The method, and the assumption it does not make\n\n")
    A("Required group size = observed group size x (observed MDE / 0.10) ** (1 / slope), "
      "targeting the **0.10 margin pre-declared in Phase 9A**. That rests on the SE "
      "scaling as n to the power -slope. **The slope was measured, not assumed:** this "
      "project's own data was subsampled at "
      f"{', '.join(str(x) for x in q['method']['subsample_fractions'])} of each carrier "
      "group, stratified on the anaemia label so prevalence stays fixed, the entire "
      "nested-operating-point and paired-bootstrap pipeline was re-run at each, and log "
      "SE was fitted against log n.\n\n")
    A(row(["comparison", "carrier group", "n range probed", "measured slope", "fit R2",
           "trusted?"]))
    A(row(["---"] * 6))
    for k in REQ_ORDER:
        s, v = q["scaling"][k], q["required"][k]
        ns = [pt_["n_carrier"] for pt_ in s["points"]]
        A(row([REQ_LABEL[k].replace("**", ""), s["carrier_group"].replace("_", "-"),
               f"{min(ns)}-{max(ns)}", f"{s['slope']:.3f}", f"{s['r2']:.2f}",
               "**yes**" if v["slope_fit_is_trustworthy"] else "no"]))
    A("\n**The scaling assumption holds where it can be checked, and fails where the "
      "data is thinnest - which is itself informative.** On the two comparisons with a "
      "reasonably sized carrier group the measured slopes are 0.538 and 0.480, "
      "bracketing the textbook 0.5. On the two smallest - `italy_to_india`'s 27 "
      "non-anaemic subjects and the PPG arm's 18 anaemic ones - the fit collapses "
      "(R2 0.25 and 0.23), because there is not enough range to fit a slope over. "
      "**That is the same composition problem showing up a second time: these groups "
      "are too small even to measure how their own precision scales.** Where the fit is "
      "not trustworthy the ordinary 1/sqrt(n) rate is used for the headline and the "
      "measured figure is reported beside it. The rule is applied by R2, not by which "
      "answer is preferred.\n\n")

    A("### Required sample size at the 0.10 margin\n\n")
    A(row(["comparison", "carrier group", "n now", "**needed, 80%**", "needed, 90%",
           "multiple", "cohort @ observed prevalence", "cohort @ 50%"]))
    A(row(["---"] * 8))
    for k in REQ_ORDER:
        v = q["required"][k]
        A(row([REQ_LABEL[k], v["carrier_group"].replace("_", "-"),
               v["n_carrier_observed"],
               f"**{v['headline_required_carrier_80']:.0f}**",
               f"{v['headline_required_carrier_90']:.0f}",
               f"{v['headline_required_carrier_80'] / v['n_carrier_observed']:.1f}x",
               f"{v['headline_required_total_at_observed_prevalence_80']:.0f}",
               f"{v['headline_required_total_at_balanced_prevalence_80']:.0f}"]))
    A("\nWhere the measured slope was not trusted, the figure above is the 1/sqrt(n) "
      "reference. Both are on the record:\n\n")
    for k in REQ_ORDER:
        v = q["required"][k]
        if not v["slope_fit_is_trustworthy"]:
            A(f"* {REQ_LABEL[k].replace('**', '')} - headline "
              f"{v['headline_required_carrier_80']:.0f} (1/sqrt(n) reference); "
              f"measured-slope figure {v['measured_required_carrier_80']:.0f}. "
              f"Basis: {v['headline_basis']}.\n")
    A("\n### The composition point, which matters more than any total here\n\n")
    A("**Phase 9D established that `italy_to_india`'s 14% power comes from composition, "
      "not raw n.** Its test site had 95 subjects, which is not tiny - but 68 of them "
      "were anaemic, so **specificity rested on 27 people**. A study designer who reads "
      "only the total will build the wrong study.\n\n")
    A(row(["direction", "test n", "anaemic", "**non-anaemic now**",
           "**minimum non-anaemic required, 80%**", "at 90%",
           "implied test-site size at that prevalence"]))
    A(row(["---"] * 7))
    for k in ("cross_site_italy_to_india", "cross_site_india_to_italy"):
        v = q["required"][k]
        A(row([direction_label(k), v["n_test_observed"],
               v["n_anaemic_observed"], v["n_carrier_observed"],
               f"**{v['headline_required_carrier_80']:.0f}**",
               f"{v['headline_required_carrier_90']:.0f}",
               f"{v['headline_required_total_at_observed_prevalence_80']:.0f}"]))
    A("\n**The minimum non-anaemic count per direction is the number to design "
      "against**: "
      f"**{q['required']['cross_site_italy_to_india']['headline_required_carrier_80']:.0f}** "
      "for italy -> india and "
      f"**{q['required']['cross_site_india_to_italy']['headline_required_carrier_80']:.0f}** "
      "for india -> italy. The two land close together, which is the expected result if "
      "the per-subject variance is similar in both directions and the difference really "
      "is composition - a consistency check the analysis passes. Recruiting to a "
      "balanced prevalence rather than accepting each site's natural one cuts "
      "italy -> india's cohort from "
      f"{it['headline_required_total_at_observed_prevalence_80']:.0f} to about "
      f"{it['headline_required_total_at_balanced_prevalence_80']:.0f}.\n\n")

    A("### Caveats, carried rather than buried\n\n")
    for c in q["method"]["caveats"]:
        A(f"* {c[0].upper()}{c[1:]}.\n")
    A("* The Phase 9D caveat travels with these figures unchanged: the SE is estimated "
      "from this sample and carries its own sampling uncertainty.\n")
    A("\n**Read these as lower bounds.** The subsampling holds the per-subject model "
      "scores fixed; a real smaller study would also have retrained on less data and "
      "produced a worse model. A real larger study drawn from more sites would face a "
      "different, probably larger, per-subject variance than this cohort's.\n\n")

    # ================================================================ PART C
    A("---\n\n## Part C - bounding the conclusions to the evidence\n\n")
    A("Three specific overstatements, corrected wherever they appeared. **Generating "
      "scripts were edited and the reports regenerated; no report was hand-patched.**\n\n")

    A("### 1. Cross-site numbers quoted as precise estimates\n\n")
    A("Phase 9D established that the magnitude of the cross-site penalty is poorly "
      "pinned down. The record nonetheless quoted rates bare. **Observed counts carry no "
      "estimation uncertainty and now lead; every rate carries its interval.** Phase 9A "
      "had stored a CI for the cross-site *sensitivity* only, so "
      "`scripts/phase9e_intervals.py` computed the rest, reproducing Phase 9A's "
      "confusion matrices and sensitivity intervals exactly before adding anything.\n\n")
    A(row(["direction", "the count (preferred)", "sensitivity (95% CI)",
           "specificity (95% CI)", "estimated on"]))
    A(row(["---"] * 5))
    for k, d in xi["directions"].items():
        A(row([direction_label(k), f"**{d['observed_counts_statement']}**",
               f"{d['sensitivity']['point']:.3f} [{d['sensitivity']['lo']:.3f}, "
               f"{d['sensitivity']['hi']:.3f}]",
               f"{d['specificity']['point']:.3f} [{d['specificity']['lo']:.3f}, "
               f"{d['specificity']['hi']:.3f}]",
               f"{d['n_anaemic']} anaemic / {d['n_non_anaemic']} non-anaemic"]))
    A("\n**The verdict does not change and was never in question.** Sensitivity 0.397 "
      "[0.278, 0.514] - 27 of 68 anaemic subjects flagged, 41 missed - "
      "was *observed*; a power analysis constrains what can be concluded from *null* "
      "comparisons, not from an observed collapse. What changes is only the precision "
      "claimed for the magnitude. `italy_to_india` specificity 0.963 looks decisive "
      "until one notices it rests on 27 subjects and its interval reaches 1.000.\n\n")

    A("### 2. Underpowered nulls stated as absence\n\n")
    A("A null from an underpowered comparison is a **bound**, not an absence, and is now "
      "written as one.\n\n")
    A(row(["comparison", "was written as", "now written as"]))
    A(row(["---"] * 3))
    sc = pw["imaging_screening"]["image_cnn"]["specificity_at_matched_sensitivity"]
    A(row(["imaging screening within site (CNN)", "\"no gain was found\"",
           f"\"no specificity gain of 0.10 or larger was detected; this design could "
           f"have detected {sc['mde_80']:.3f}\" ({pct(sc['power_at_the_yardstick'])} "
           "power at the margin)"]))
    A(row(["imaging screening within site, sensitivity direction", "same",
           f"\"...could have detected "
           f"{pw['imaging_screening']['image_cnn']['sensitivity_at_matched_specificity']['mde_80']:.3f}\""]))
    A(row(["PPG screening AUROC",
           "\"AUROC diff -0.001, CI spans zero\" - used as confirmation",
           f"uninformative on its own: MDE {pw['ppg']['auroc']['mde_80']:.2f} on "
           f"{pw['ppg']['n_anaemic']} anaemic subjects. **The PPG verdict rests on its "
           "MAE and NNS figures, and nothing leans on its AUROC.**"]))
    A("\n**What was NOT weakened, deliberately.** The two regression arms are "
      "ADEQUATELY POWERED - MDE "
      f"{pw['imaging_regression']['mde_80']:.3f} g/dL for imaging and "
      f"{pw['ppg']['mae_vs_sex_alone']['mde_80']:.3f} for PPG, against a narrowest WHO "
      "band of 1.0 g/dL. Those negative results are informative evidence of absence, and "
      "the effects too small for this design to detect are also far too small to matter "
      "clinically. **Hedging them would be the same error in the opposite direction, and "
      "it was checked for.** The PPG *specificity* comparison (MDE "
      f"{pw['ppg']['specificity_at_matched_sensitivity']['mde_80']:.3f}) is likewise "
      "adequately powered.\n\n")

    A("### 3. The studio result quoted without its interval\n\n")
    A("Phase 7's studio gate figure of **1.040 g/dL** sits 0.04 above the VIABLE line - "
      "a residual 1.08x what VIABLE needs, which reads as *within 8% of viable*. **That "
      "reading survives only at the nominal parameter choice.** Over the Phase 9C prior "
      "the same residual gives median 1.52, 95% [0.60, 4.90] - 27.1% VIABLE, 35.9% "
      "MARGINAL, 37.0% NOT RECOVERABLE. Its band is a property of the parameter choice "
      "as much as of the capture condition. `reports/phase7.md` now carries the interval "
      "in the gate table itself, on every measured and interpolated row, and the "
      "*within 8% of viable* sentence carries the interval in the same breath.\n\n")

    A("### What the pass found that was not on the list\n\n")
    A("* **A correction that had not propagated.** `reports/phase7.md` still carried the "
      "clause \"and moves no clinical threshold\", which Phase 9A retired on 2026-09-17 "
      "(`docs/archive/corrections.md` section 8). The correction had been recorded in "
      "the archive and in CLAUDE.md but never applied to the Phase 7 generator. It is "
      "now removed, with a note in its place saying what stood there and why it went.\n")
    A("* **The audit package carried none of the three overstatements.** Neither "
      "`hemosight.audit.content` nor `/api/case-study` quotes a cross-site rate, an "
      "underpowered null or the studio figure, so there was nothing to correct. What "
      "they lacked was any statement of the boundaries at all - a worked example that "
      "shows only what a project found, and never what it could not have found, teaches "
      "half the lesson - so `/api/case-study` now serves a `boundaries` block read from "
      "the Phase 9D and 9E artefacts.\n")
    A("* **The landing page's noise-versus-signal ladder** now shows the guided-capture "
      "regime as a dashed outline labelled *interpolated*, beside the three measured "
      "bars. Leaving it out is what let the gap go unnoticed.\n\n")

    # ================================================ consolidated specification
    A("---\n\n## What a confirmatory study would need - Parts A and B together\n\n")
    A("**These are two different studies, and conflating them is how the project's own "
      "record came to leave both implicit.** One is cheap and answers a physics "
      "question. The other is expensive and answers the deployment question. **The "
      "second is the one that decides the arm**, and doing only the first would repeat "
      "this project's mistake of measuring a single site well.\n\n")
    A(row(["", "**Study 1 - the capture-residual study (Part A)**",
           "**Study 2 - the cross-site screening study (Part B)**"]))
    A(row(["---"] * 3))
    A(row(["**question it answers**",
           "What residual does guided capture actually leave? I.e. is the imaging "
           "refutation about photographs or about uncontrolled photographs?",
           "Does a within-site screening advantage survive transfer to another site? "
           "I.e. is the arm deployable?"]))
    A(row(["**protocol**",
           "One phone, one session, live framing/distance overlay, automatic quality "
           "gate, ambient light uncontrolled. Repeat captures per subject.",
           "The same guided protocol, applied at **two or more sites with different "
           "populations**, with the operating point chosen on one site and applied to "
           "the other - the construction Phase 9A used."]))
    A(row(["**measurement**",
           "Within-subject mean pairwise CIEDE2000 of segmented scleral colour, best of "
           "{none, grey-world full, grey-world 25% crop}. Then the Phase 3 gate re-run "
           "at that measured residual.",
           "Specificity at matched sensitivity against a **site + sex + age** baseline "
           "on identical folds, with a subject-level paired bootstrap CI, against the "
           "0.10 margin. Venous haemoglobin reference required."]))
    A(row(["**sample**",
           ">= 3 repeat captures for each of >= 30 subjects, spanning the skin-tone "
           "range. **No blood draw needed.**",
           f"**Per direction: at least "
           f"{q['required']['cross_site_italy_to_india']['headline_required_carrier_80']:.0f} "
           "non-anaemic subjects in the test site** (and >= "
           f"{q['required']['imaging_screening_sensitivity']['headline_required_carrier_80']:.0f} "
           "anaemic for the sensitivity direction). At a natural high-prevalence site "
           f"that is a ~{it['headline_required_total_at_observed_prevalence_80']:.0f}-"
           "person cohort; recruited to a balanced prevalence, about "
           f"{it['headline_required_total_at_balanced_prevalence_80']:.0f}. **Both sites "
           "must meet the non-anaemic floor, because transfer is tested in both "
           "directions.**"]))
    A(row(["**cost driver**", "Number of repeat captures, not subjects.",
           "**The non-anaemic count, not the total.** This is the specific thing this "
           "project got wrong: 95 test subjects of which 68 were anaemic."]))
    A(row(["**what would change the verdict**",
           f"A residual below {g['interval_verdict']['residual_required_for_VIABLE']:.3f} "
           "dE2000 would move the gate to VIABLE and narrow the refutation to "
           "uncontrolled capture. Anything above leaves it where it is.",
           "A specificity gain >= 0.10 with a CI lower bound above zero, **holding in "
           "both directions**, at sensitivity >= 0.90 and specificity >= 0.50. Anything "
           "less leaves the arm not deployable."]))
    A(row(["**what it would still not settle**",
           "The ~4.5 dE2000 between-subject conjunctival colour term at fixed Hb, sex, "
           "age and site (Phase 6.5), which capture control does not touch.",
           "Severe anaemia, which no trusted dataset in this project contains "
           "(minimum 7.0 g/dL), and pregnancy status, which neither dataset records."]))
    A("\n**And the finding that should govern how either study is read.** This project's "
      "best-powered comparisons are its regression ones, and they are unambiguous: no "
      "method in six attempts across two modalities beat **sex alone, MAE 0.831 g/dL**. "
      "A confirmatory study that does not carry a demographic baseline on identical "
      "folds will not be able to tell a haemoglobin estimator from a sex classifier - "
      "which is the failure mode this project measured directly, and which "
      "**0 of the 7 papers read in Phase 9B report a baseline against**.\n\n")

    A("---\n\n## What did not change\n\n")
    A("**No verdict, anywhere.** The imaging arm remains CLOSED, FINAL; the PPG arm "
      "remains NOT VIABLE; the Phase 3 gate remains NOT RECOVERABLE and ROBUST to "
      "parameter uncertainty; the studio condition remains MARGINAL and FRAGILE; the one "
      "positive claim remains real and clinically useless. Phase 9E was pre-declared as "
      "forbidden to change a verdict, and it did not.\n\n")

    DST.write_text("".join(L), encoding="utf-8")
    print(f"wrote {DST} ({len(''.join(L)):,} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
