"""Phase 2, Task 5: generate reports/phase2_calibration.md.

Reads every Phase 2 artefact and states plainly whether N1a and N1b are SUPPORTED,
PARTIALLY SUPPORTED or REFUTED. The verdict is computed from thresholds declared up
front, not chosen after seeing the numbers.

    .\\.venv\\Scripts\\python.exe scripts\\phase2_report.py
"""

from __future__ import annotations

import json

import numpy as np

from hemosight.io import paths

IN = paths.INTERIM / "phase2"

# Verdict thresholds, declared BEFORE looking at results so the verdict is not
# reverse-engineered from them.
N1A_SUPPORTED_IF = "reference-patch mean angular error beats every classical baseline"
N1B_SUPPORTED_IF = (
    "sclera-referenced correction reduces within-subject dE2000 spread on the "
    "held-out iris versus BOTH no-correction AND every classical baseline"
)


def load(name):
    f = IN / name
    return json.loads(f.read_text(encoding="utf-8")) if f.exists() else None


def md_row(cells):
    return "| " + " | ".join(str(c) for c in cells) + " |"


def main() -> int:
    n1a = load("n1a_nus8_results.json")
    n1b = load("n1b_selfconsistency.json")
    seg = load("segmentation_eval.json")
    hist = load("segmentation_history.json")
    sens = load("sensitivity.json")

    L: list[str] = []
    A = L.append
    A("# Phase 2 - Sclera segmentation and sclera-referenced illuminant estimation\n\n")
    A("Generated by `scripts/phase2_report.py`. Tests **N1a** and **N1b**, which after ")
    A("the Phase 1.5 restructure are the project's strongest claims.\n\n")
    A("> **Scientific premise.** The sclera is not a neutral white reference: it is ")
    A("slightly yellowish, varies with age, and carries red, spatially non-uniform ")
    A("vasculature. Every method here estimates the illuminant *given a surface with a ")
    A("known non-neutral reflectance prior*. Assuming neutrality is treated as one ")
    A("prior among several and is measured, not assumed away.\n")

    # ------------------------------------------------------------------ N1a
    A("\n---\n\n## 1. N1a - illuminant estimation accuracy across sensors (nus8)\n\n")
    verdict_a = "NOT RUN"
    if n1a:
        pooled = n1a["pooled_all_methods"]
        abl = n1a["ablation"]
        A("nus8 has no eyes, so it isolates ESTIMATION error from SEGMENTATION error. ")
        A("The ColorChecker's neutral patches stand in for the reference surface: like ")
        A("the sclera they are *near*-neutral but not exactly neutral, so the prior ")
        A("ablation here predicts how well a sclera prior must be known.\n\n")
        A("Two protocol details are not optional:\n\n")
        A("* **Dark level subtraction.** Skipping it inflates Canon600D's mean angular ")
        A("error from ~0.9 to ~12 degrees. The `color.txt` values are raw sensor counts.\n")
        A("* **16-bit reading.** These PNGs are 16-bit; PIL silently truncates them to ")
        A("8-bit, collapsing ~1800 distinct values to ~11. `cv2.IMREAD_UNCHANGED` is used.\n")
        A("* **Leakage control.** The ColorChecker is masked out of every classical ")
        A("baseline's input. It is the answer key.\n\n")
        A(md_row(["method", "mean", "median", "trimean", "best 25%", "worst 25%"]) + "\n")
        A(md_row(["---"] * 6) + "\n")
        for k, v in sorted(pooled.items(), key=lambda kv: kv[1]["mean"]):
            nm = k.replace("reference_patch/", "**reference-patch: ").replace(
                "classical/", "")
            nm = nm + "**" if k.startswith("reference_patch") else nm
            A(md_row([nm, f"{v['mean']:.3f}", f"{v['median']:.3f}",
                      f"{v.get('trimean', float('nan')):.3f}",
                      f"{v.get('best25', float('nan')):.3f}",
                      f"{v['worst25']:.3f}"]) + "\n")
        A("\nAngular error in degrees, pooled over 6 cameras, per-camera 3-fold CV.\n")

        A("\n### 1.1 The prior ablation - the number that predicts the sclera requirement\n\n")
        A(md_row(["prior on the reference surface", "mean angular error"]) + "\n")
        A(md_row(["---", "---"]) + "\n")
        A(md_row(["assumed neutral (naive white reference)",
                  f"{abl['neutral_prior_mean_deg']:.3f} deg"]) + "\n")
        A(md_row(["fixed population-average prior",
                  f"**{abl['fixed_population_prior_mean_deg']:.3f} deg**"]) + "\n")
        A(md_row(["oracle per-image prior (not deployable)",
                  f"{abl['oracle_per_image_prior_mean_deg']:.3f} deg"]) + "\n")
        gain = abl["prior_gain_deg"]
        pct = abl["prior_gain_pct"]
        A(f"\n**Knowing the reference surface's true reflectance halves the error** "
          f"({gain:.3f} deg, {pct:.0f}%). The oracle reaching exactly 0.000 is not a "
          f"meaningful achievable number - it is fitted per test image and is reported "
          f"only to prove the measurement model inverts exactly, which means **all "
          f"residual error is prior error, not model error**.\n")
        A("\n**This is the quantitative warning for N1b:** on a surface only mildly "
          "non-neutral, assuming neutrality doubles the error. The sclera is more "
          "non-neutral than a ColorChecker grey patch, so its prior matters at least "
          "this much.\n")

        A("\n### 1.2 Cross-sensor transfer\n\n")
        lo = n1a["protocols"].get("leave_one_camera_out_pooled", {})
        cv = n1a["protocols"].get("per_camera_3fold_pooled", {})
        A(md_row(["method", "per-camera 3-fold", "leave-one-camera-out", "degradation"]) + "\n")
        A(md_row(["---"] * 4) + "\n")
        for k in sorted(set(cv) & set(lo)):
            a, b = cv[k]["mean"], lo[k]["mean"]
            A(md_row([k.replace("reference_patch/", ""), f"{a:.3f}", f"{b:.3f}",
                      f"{b - a:+.3f}"]) + "\n")
        A("\nA prior fitted on five cameras and applied to a sixth barely degrades, so "
          "**the reflectance prior transfers across sensors** rather than encoding a "
          "camera-specific correction. That is the property calibration-free operation "
          "needs.\n")

        best_cls = abl["best_classical_mean_deg"]
        best_ref = abl["fixed_population_prior_mean_deg"]
        verdict_a = "SUPPORTED" if best_ref < best_cls else "REFUTED"
        A(f"\n### VERDICT N1a: **{verdict_a}**\n\n")
        A(f"Criterion declared in advance: *{N1A_SUPPORTED_IF}*.\n\n")
        A(f"Reference-patch estimation with a fitted prior reaches "
          f"**{best_ref:.3f} deg** against the best classical baseline's "
          f"**{best_cls:.3f} deg** - a {best_cls/best_ref:.1f}x reduction. It holds "
          f"across all six sensors and survives leave-one-camera-out.\n")
        A("\n**Scope of this verdict.** N1a establishes that *given a correctly "
          "segmented reference patch of known reflectance*, illuminant estimation is "
          "accurate and transfers across sensors. It says nothing about whether the "
          "sclera can BE that patch - that is N1b.\n")

    # ------------------------------------------------------- segmentation
    A("\n---\n\n## 2. Sclera segmentation (Task 1)\n\n")
    if hist:
        A(f"U-Net with an ImageNet ResNet-18 encoder, 384x384, "
          f"{hist['args']['epochs']} epochs, batch {hist['args']['batch']}, AMP. "
          f"Train {hist['n_train']} / val {hist['n_val']} images, **split by subject**.\n\n")
    if seg:
        A("### 2.1 Held-out IoU and Dice\n\n")
        A(md_row(["subset", "n", "sclera IoU", "sclera Dice", "iris IoU", "pupil IoU",
                  "periocular IoU"]) + "\n")
        A(md_row(["---"] * 7) + "\n")
        for name, v in seg.get("by_dataset", {}).items():
            def _iou(k, row=v):
                x = row["iou"].get(k)
                return "-" if x is None else f"{x:.3f}"

            dsc = v["dice"].get("sclera")
            dsc = "-" if dsc is None else f"{dsc:.3f}"
            A(md_row([name, v["n"], _iou("sclera"), dsc, _iou("iris"), _iou("pupil"),
                      _iou("periocular")]) + "\n")
        A("\n`periocular` is supervised by SBVPI only: MOBIUS marks skin as black, "
          "identical to background. Training naively on both would teach the model that "
          "skin is simultaneously class 0 and class 4, so the loss merges the background "
          "and periocular logits for MOBIUS frames (see `merged_bg_cross_entropy`).\n")

        A("\n### 2.2 Does segmentation quality depend on the device? (confounder check)\n\n")
        for key, label in (("by_phone", "device"), ("by_lighting", "lighting")):
            d = seg.get(key, {})
            if not d:
                continue
            A(f"**By {label}:**\n\n")
            A(md_row([label, "n", "sclera IoU", "sclera Dice", "iris IoU"]) + "\n")
            A(md_row(["---"] * 5) + "\n")
            for g, v in sorted(d.items()):
                A(md_row([g, v["n"], f"{v['sclera_iou']:.4f}", f"{v['sclera_dice']:.4f}",
                          f"{v['iris_iou']:.4f}"]) + "\n")
            A(f"\nSclera IoU spread across {label}: "
              f"**{seg.get(key + '_spread', float('nan')):.4f}**\n\n")

        q = seg.get("quality_score")
        if q:
            A("### 2.3 Per-image quality score (feeds N4 abstention)\n\n")
            A(f"MOBIUS ships frames deliberately marked `_bad` for quality control - a "
              f"free labelled negative set. The quality score separates them from normal "
              f"frames with **AUROC {q['auroc_good_vs_bad']:.3f}** "
              f"(good mean {q['good_mean']:.3f}, bad mean {q['bad_mean']:.3f}, "
              f"n={q['n_good']}/{q['n_bad']}).\n")

        v = seg.get("vasculature")
        if v:
            A("\n### 2.4 Vasculature exclusion\n\n")
            A(f"Redness R/(G+B) above the {75}th percentile *of each sclera* is dropped; "
              f"a fixed absolute threshold would behave differently under each lighting "
              f"condition.\n\n")
            A(f"* Sclera area removed: **{v['mean_area_removed']*100:.1f}%**\n")
            A(f"* True vessels occupy {v['mean_true_vessel_frac_of_sclera']*100:.1f}% of "
              f"the sclera (SBVPI ground truth, n={v['n']})\n")
            A(f"* Recall of true vessel pixels: {v['mean_recall_of_true_vessels']:.3f}; "
              f"precision {v['mean_precision']:.3f}\n")
            A("\nPrecision is modest by design: the goal is a clean reference patch, so "
              "over-removing sclera costs little while retaining a vessel costs a "
              "haemoglobin-tinted reference - exactly the contamination this project "
              "cannot tolerate.\n")

    # ------------------------------------------------------------------ N1b
    A("\n---\n\n## 3. N1b - sclera self-consistency across devices and lighting\n\n")
    verdict_b = "NOT RUN"
    if n1b:
        A("MOBIUS: 3 phones x 3 lighting conditions x 100 subjects, no haemoglobin "
          "needed. A subject's tissue has fixed reflectance, so after a correct "
          "illuminant correction the recovered colour should agree across conditions. "
          "Residual disagreement is the calibration error.\n\n")
        A("### 3.1 The circularity trap\n\n")
        A("Estimating the illuminant from the sclera and then measuring consistency ON "
          "the sclera is circular: `corrected = measured / (measured / prior) = prior`, "
          "a constant, so the spread collapses to exactly zero for every subject. That "
          "would look like a triumphant confirmation and would mean nothing.\n\n")
        A("**The primary evaluation region is therefore the IRIS** - a different surface "
          "with its own fixed per-subject reflectance, never used to estimate the "
          "illuminant. A secondary sclera figure uses a spatial holdout (estimate from "
          "one half, evaluate on the other) and is reported as partially circular.\n")

        for region in ("iris", "sclera_holdout"):
            d = n1b["spread"].get(region)
            if not d:
                continue
            tag = ("**PRIMARY, non-circular**" if region == "iris"
                   else "secondary, partially circular")
            A(f"\n### 3.2 Within-subject dE2000 spread - region: `{region}` ({tag})\n\n")
            A(md_row(["method", "mean dE2000", "median", "to-centroid", "n subjects"]) + "\n")
            A(md_row(["---"] * 5) + "\n")
            for m, v in sorted(d.items(), key=lambda kv: kv[1]["mean_pairwise_dE"]):
                A(md_row([m, f"{v['mean_pairwise_dE']:.3f}",
                          f"{v['median_pairwise_dE']:.3f}",
                          f"{v['mean_to_centroid_dE']:.3f}", v["n_subjects"]]) + "\n")

        var = n1b["variance"].get("iris", {})
        if var:
            A("\n### 3.3 Variance decomposition on the iris\n\n")
            A("A **phone effect that survives correction** is the failure mode that "
              "matters most: it means the method does not transfer across devices, "
              "which is exactly what calibration-free operation requires.\n\n")
            A(md_row(["method", "phone", "lighting", "residual", "between-subject"]) + "\n")
            A(md_row(["---"] * 5) + "\n")
            for m, v in sorted(var.items(), key=lambda kv: kv[1]["frac_within_phone"]):
                A(md_row([m, f"{v['frac_within_phone']:.3f}",
                          f"{v['frac_within_lighting']:.3f}",
                          f"{v['frac_within_residual']:.3f}",
                          f"{v['frac_between_subject']:.3f}"]) + "\n")
            A("\nFractions of total variance. `between-subject` is signal, not error: it "
              "is genuine biological difference between people. Everything else is "
              "capture-condition variance the correction failed to remove.\n")

        iris = n1b["spread"].get("iris", {})
        if iris:
            sclera_methods = {m: v for m, v in iris.items() if m.startswith("sclera")}
            other = {m: v for m, v in iris.items() if not m.startswith("sclera")}
            best_sclera = min(sclera_methods.values(),
                              key=lambda v: v["mean_pairwise_dE"], default=None)
            best_other = min(other.values(), key=lambda v: v["mean_pairwise_dE"],
                             default=None)
            none_v = other.get("none")
            if best_sclera and best_other and none_v:
                beats_all = (best_sclera["mean_pairwise_dE"] < best_other["mean_pairwise_dE"])
                beats_none = (best_sclera["mean_pairwise_dE"] < none_v["mean_pairwise_dE"])
                verdict_b = ("SUPPORTED" if beats_all and beats_none
                             else "PARTIALLY SUPPORTED" if beats_none else "REFUTED")
                A(f"\n### VERDICT N1b: **{verdict_b}**\n\n")
                A(f"Criterion declared in advance: *{N1B_SUPPORTED_IF}*.\n\n")
                A(md_row(["comparison", "mean dE2000"]) + "\n")
                A(md_row(["---", "---"]) + "\n")
                A(md_row(["no correction", f"{none_v['mean_pairwise_dE']:.3f}"]) + "\n")
                A(md_row(["best classical baseline",
                          f"{best_other['mean_pairwise_dE']:.3f}"]) + "\n")
                A(md_row(["best sclera-referenced",
                          f"{best_sclera['mean_pairwise_dE']:.3f}"]) + "\n")

            # The prior question, answered honestly.
            A("\n### 3.4 The prior question - and why this experiment cannot answer it\n\n")
            pri = {m: v["mean_pairwise_dE"] for m, v in iris.items()
                   if m.startswith("sclera_prior_")}
            if pri:
                A(md_row(["sclera prior", "mean dE2000 spread"]) + "\n")
                A(md_row(["---", "---"]) + "\n")
                for m, v in sorted(pri.items()):
                    A(md_row([m.replace("sclera_prior_", ""), f"{v:.4f}"]) + "\n")
                spread_of_priors = max(pri.values()) - min(pri.values())
                A(f"\nThe three priors differ by only **{spread_of_priors:.4f} dE2000**, "
                  f"and that is not a weak result - it is a mathematical necessity that "
                  f"this protocol cannot escape.\n\n")
                A("A prior is a constant for a given subject, so it multiplies every one "
                  "of that subject's captures by the same factor. It therefore *shifts* "
                  "the subject's colour cluster without changing its *spread*. "
                  "**Self-consistency is blind to the reflectance prior.** It measures "
                  "whether sclera-referencing removes capture-condition variation; it "
                  "cannot measure whether the recovered colour is correct.\n\n")
                A("The prior question is answerable only where absolute ground truth "
                  "exists: **N1a answers it on nus8** (halving the error, section 1.1), "
                  "and **N1c will answer it against haemoglobin**. This is a limitation "
                  "of the N1b protocol as designed, recorded rather than glossed.\n")
                A("\nA second, separate limitation: `per_subject` and "
                  "`fixed_population` came out **bit-identical** (maximum per-subject "
                  "difference 0.0). A per-subject prior can only be fitted from that "
                  "subject's own ground truth, which held-out subjects by definition do "
                  "not have, so the estimator falls back to the population value. "
                  "**A per-subject prior is not evaluable in any deployable setting** - "
                  "which is itself the answer to whether one could be shipped: it could "
                  "not.\n")

    if n1b and n1b["spread"].get("iris"):
        from scipy import stats

        iris_d = n1b["spread"]["iris"]
        subs = sorted(iris_d["none"]["per_subject_mean_pairwise"])

        def _arr(m):
            d = iris_d[m]["per_subject_mean_pairwise"]
            return np.array([d[s] for s in subs])

        A("\n### 3.4b Is the difference real? Paired tests over subjects\n\n")
        A(f"The per-subject distributions overlap heavily, so the ranking is tested "
          f"rather than eyeballed. Paired over the same n={len(subs)} held-out "
          f"subjects; positive difference means the sclera method is WORSE.\n\n")
        A(md_row(["sclera (fixed prior) vs", "mean diff dE2000", "Wilcoxon p",
                  "sclera better in"]) + "\n")
        A(md_row(["---"] * 4) + "\n")
        base = _arr("sclera_prior_fixed_population")
        for m in ("none", "grey_world", "shades_of_grey_p6", "max_rgb_p99",
                  "sclera_prior_neutral"):
            if m not in iris_d:
                continue
            o = _arr(m)
            p = stats.wilcoxon(base, o).pvalue
            diff = float((base - o).mean())
            sig = "**significant**" if p < 0.05 else "not significant"
            A(md_row([m, f"{diff:+.3f}", f"{p:.1e} ({sig})",
                      f"{int((base - o < 0).sum())}/{len(subs)}"]) + "\n")
        A("\nRead precisely, the sclera reference:\n\n")
        A("* **beats no correction** (p ~ 1e-8, better in 35/40 subjects) - it genuinely "
          "removes capture-condition variation;\n")
        A("* **beats max-RGB** (p ~ 5e-6);\n")
        A("* **ties shades-of-grey** (p = 0.44, indistinguishable);\n")
        A("* **loses to grey-world** (p ~ 3e-8, better in only **6 of 40 subjects**) - "
          "this is a real, consistent deficit, not sampling noise;\n")
        A("* and the fitted prior is **not significantly different from assuming "
          "neutrality** (p = 0.25), the empirical confirmation of the mathematical "
          "argument in 3.4.\n")

    if n1b:
        A("\n### 3.5 Why the sclera reference underperformed a whole-image statistic\n\n")
        A("Three explanations are consistent with the evidence and are not mutually "
          "exclusive:\n\n")
        A("1. **Sample size of the reference.** Grey-world integrates millions of "
          "pixels; the sclera reference is a few thousand after vasculature exclusion, "
          "and is measured through a segmentation with IoU 0.875 rather than a perfect "
          "mask. A noisier reference gives a noisier illuminant.\n")
        A("2. **The fitted prior absorbed grey-world's bias, not sclera physics.** "
          "MOBIUS ships no ground-truth illuminant, so the prior had to be fitted "
          "against grey-world under a stated assumption. The recovered value is ")
        A(f"`{n1b['population_prior']}` - **more blue than red**, which is the opposite "
          "of a yellowish sclera. MOBIUS frames are skin-dominated, so grey-world leans "
          "red, and the 'reflectance' inherited the inverse of that bias. This is a "
          "defect of fitting a prior without ground truth, and it is why the fitted "
          "prior scores marginally WORSE than assuming neutrality here.\n")
        A("3. **The iris is not a perfectly stable target either.** It is segmented at "
          "IoU 0.815 on MOBIUS and is partly specular, so some residual spread is "
          "measurement noise shared by all methods - which compresses the differences "
          "between them rather than favouring any one.\n")
        A("\nNone of these rescues the claim. They say the experiment was fair and the "
          "result is informative, not that the result should be discounted.\n")

    if sens:
        A("\n### 3.6 Sensitivity of the sclera estimate (plan item 6)\n\n")
        A("How far each failure mode moves the illuminant estimate, in the same "
          "angular-error units as N1a. For scale: the entire N1a gap between a naive "
          "and an informed prior was 0.60 deg.\n\n")
        A(md_row(["perturbation", "mean shift (deg)", "median", "p90"]) + "\n")
        A(md_row(["---"] * 4) + "\n")
        for k, v in sorted(sens.items(), key=lambda kv: -kv[1]["mean_deg"]):
            A(md_row([k, f"{v['mean_deg']:.3f}", f"{v['median_deg']:.3f}",
                      f"{v['p90_deg']:.3f}"]) + "\n")
        A("\n`yellowing_*` simulates an ageing sclera. Under a neutral prior the "
          "estimate absorbs that change entirely as if it were illuminant colour - the "
          "exact error mode the reflectance prior exists to prevent, and direct "
          "quantitative support for the Phase 2 premise that the sclera must not be "
          "assumed white.\n")

    # --------------------------------------------------------------- Task 4
    A("\n---\n\n## 4. Cross-dataset sanity: Eyes-Defy-Anemia (Task 4)\n\n")
    if seg and seg.get("eyes_defy"):
        e = seg["eyes_defy"]
        A("Eyes-Defy has no sclera masks, so confidence and failure rate are reported "
          "rather than IoU. This decides whether the Phase 2 pipeline will function at "
          "all on the Phase 4 data.\n\n")
        A(f"* n = {e['n']} images\n")
        A(f"* mean quality {e['quality_mean']:.3f}, median {e['quality_median']:.3f}\n")
        A(f"* mean predicted sclera area fraction {e['sclera_area_fraction_mean']:.4f}\n")
        A(f"* **failure rate (quality < 0.3): {e['failure_rate_q_lt_0.3']*100:.1f}%**\n\n")
        A(md_row(["site", "n", "mean quality", "failure rate"]) + "\n")
        A(md_row(["---"] * 4) + "\n")
        for s, v in e["by_site"].items():
            A(md_row([s, v["n"], f"{v['quality_mean']:.3f}",
                      f"{v['failure_rate']*100:.1f}%"]) + "\n")

    # -------------------------------------------------------------- summary
    A("\n---\n\n## 5. Synthesis: the three results explain each other\n\n")
    if n1a and n1b and sens:
        yel = sens.get("yellowing_10pct", {}).get("mean_deg")
        ves = sens.get("vessels_included_shift", {}).get("mean_deg")
        msk = sens.get("mask_dilate31", {}).get("mean_deg")
        A("Read together, N1a, the sensitivity analysis and N1b tell one coherent "
          "story, and it locates the bottleneck precisely.\n\n")
        A(f"1. **The estimation mathematics is not the problem.** Given a reference "
          f"surface whose reflectance is known, illuminant estimation reaches "
          f"{n1a['ablation']['fixed_population_prior_mean_deg']:.2f} deg and transfers "
          f"across six sensors (N1a).\n")
        A(f"2. **Segmentation accuracy is not the problem either.** Dilating or eroding "
          f"the sclera mask by 31 pixels moves the estimate only {msk:.2f} deg - smaller "
          f"than the N1a prior gain.\n")
        A(f"3. **Knowledge of the sclera's own reflectance IS the problem.** A 10% "
          f"yellowing shift - well inside normal inter-subject and age variation - moves "
          f"the estimate by **{yel:.2f} deg**, larger than grey-world's entire error. "
          f"Leaving vasculature in costs a further {ves:.2f} deg.\n\n")
        A("So the sclera fails as a white reference not because it is hard to find or "
          "hard to measure, but because **its reflectance varies between people by more "
          "than the illuminant signal being estimated**, and that variation cannot be "
          "recovered per subject without ground truth the deployment setting will never "
          "have. A fixed population prior cannot absorb a per-subject quantity.\n\n")
        A("This is the most useful thing Phase 2 produced. It is a mechanistic "
          "explanation of a negative result, it was predicted by the phase's stated "
          "premise that the sclera is not neutral, and it says exactly where effort "
          "should go next.\n")

    A("\n### Constraints this places on later phases\n\n")
    if seg:
        lsp = seg.get("by_lighting_spread")
        psp = seg.get("by_phone_spread")
        A(f"* **Lighting, not device, degrades segmentation.** Sclera IoU spread across "
          f"phones is only {psp:.4f}, but across lighting it is {lsp:.4f}: "
          f"{seg['by_lighting']['indoor']['sclera_iou']:.3f} indoor versus "
          f"**{seg['by_lighting']['poor']['sclera_iou']:.3f} in poor light**. The "
          f"pipeline degrades exactly where field deployment would operate, and any N1b "
          f"or N5 result stratified by lighting inherits this confound.\n")
        q = seg.get("quality_score")
        if q:
            A(f"* **The quality score is too weak for N4 as it stands.** It ranks "
              f"deliberately-bad frames below good ones (AUROC "
              f"{q['auroc_good_vs_bad']:.3f}) but their means differ by only "
              f"{q['good_mean'] - q['bad_mean']:.3f}, and **no bad frame falls below the "
              f"0.3 threshold**. As an abstention signal it currently rejects nothing. "
              f"N4 will need a better non-conformity signal than this - the spectral "
              f"reconstruction residual, as N4 already specifies.\n")
        v = seg.get("vasculature")
        if v:
            A(f"* **Vasculature exclusion is crude.** Removing "
              f"{v['mean_area_removed']*100:.0f}% of sclera area recovers only "
              f"{v['mean_recall_of_true_vessels']*100:.0f}% of true vessel pixels at "
              f"{v['mean_precision']*100:.0f}% precision, against vessels that occupy "
              f"just {v['mean_true_vessel_frac_of_sclera']*100:.1f}% of the sclera. It "
              f"is a blunt redness threshold, and SBVPI's 128 vessel masks are enough to "
              f"train a proper vessel segmenter if Phase 4 needs one.\n")
        byd = seg.get("by_dataset", {}).get("sbvpi", {})
        if byd and byd.get("iou", {}).get("iris") == 0.0:
            A("* **Iris segmentation does not transfer to SBVPI** (IoU 0.000 there "
              "versus 0.815 on MOBIUS): SBVPI annotates iris on only ~128 of 1,840 "
              "images, so the class is barely supervised in that domain. N1b is "
              "unaffected because it runs on MOBIUS, but any later use of the iris on "
              "another dataset must not assume this transfers.\n")
    if seg and seg.get("eyes_defy"):
        e = seg["eyes_defy"]
        A(f"* **The pipeline does run on Eyes-Defy** - mean quality "
          f"{e['quality_mean']:.3f}, **{e['failure_rate_q_lt_0.3']*100:.1f}% failures**, "
          f"and the two sites agree ({e['by_site']['eyes_defy:India']['quality_mean']:.3f} "
          f"India versus {e['by_site']['eyes_defy:Italy']['quality_mean']:.3f} Italy). "
          f"Phase 4 has a working front end. Note this is a confidence measure, not "
          f"accuracy: Eyes-Defy ships no masks, so correctness there is unverified.\n")

    A("\n### Verdicts\n\n")
    A(md_row(["claim", "verdict"]) + "\n")
    A(md_row(["---", "---"]) + "\n")
    A(md_row(["**N1a** - illuminant accuracy across sensors", f"**{verdict_a}**"]) + "\n")
    A(md_row(["**N1b** - sclera as endogenous white reference", f"**{verdict_b}**"]) + "\n")
    A("\n**N1b is not softened and will not be retried until it passes.** The sclera "
      "does remove real capture-condition variation, but it does not beat a whole-image "
      "grey-world statistic on a held-out region, and the device effect survives "
      "correction. Under the criterion declared before the experiment ran, that is "
      "partial support, and the headline claim as originally written - that the sclera "
      "is a *sufficient* endogenous white reference - is **not** supported by this "
      "evidence.\n")

    (paths.REPORTS / "phase2_calibration.md").write_text("".join(L), encoding="utf-8")
    print(f"wrote {paths.REPORTS / 'phase2_calibration.md'}")
    print(f"  N1a: {verdict_a}   N1b: {verdict_b}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
