"""Phase 7 Task 3B reports: reports/external_audit_availability.md (the primary result)
and reports/external_audit.md. Everything is read from the register
(`configs/external_audit_register.json`) and the run record
(`data/interim/phase7/external/anemia-detection/run_results.json`).
"""
from __future__ import annotations

import json

from hemosight.io import paths

REG = paths.ROOT / "configs" / "external_audit_register.json"
# The run record is committed beside the register (it holds error strings and paths,
# no data); the data/ copy is the runner's live output.
RUN = paths.ROOT / "configs" / "external_audit_run_record.json"

SCOPE = ("> **Scope, stated first.** `mbedmutha/anemia-detection` is a three-person student "
         "project with 18 commits, zero stars, self-described as \"initial experiments\". It "
         "is **not** a published paper and is **not** evidence about the published literature. "
         "Its role here is solely to demonstrate that the harness can ingest and audit "
         "external code. Nothing about it generalises.\n\n")

CODE_OBSERVATIONS = [
    ("baselines/hue_score_svm.ipynb, baselines/mean_ann.ipynb",
     "`train_test_split(..., test_size=test_split)` with **no `random_state`**: the split is "
     "different on every run, so no reported number could be reproduced even with the arrays."),
    ("experiments/xgboost_linreg.ipynb",
     "Positional slices: linear regression fit on `X[:200]`, evaluated on `X[200:]` (11 rows); the "
     "XGBoost cell fits on `X[:110]` and evaluates on `X[:20]` - **20 rows drawn from the training "
     "rows**. Labels are scaled by an undocumented constant (`*20` on both sides of the MSE)."),
    ("experiments/vanilla_cnn.ipynb",
     "The `DataLoader.sample()` method computes a positional 80/10/10 slice of the augmented "
     "folder and then draws `random.choice(os.listdir(path))` from the **whole** folder, so the "
     "'train' and 'validation' draws come from the same pool; augmented copies (Flip/Rotate/Scale/"
     "Translation) of one photograph can appear in both. `wandb` is used without being imported."),
    ("experiments/transfer-learning/*.ipynb",
     "`random_state=101` is set. The notebooks depend on the PH2 and HAM10000 archives and on "
     "`Italy_new.xlsx`, none released, and on the Keras 2 API (`ImageDataGenerator`, `adam_v2`) "
     "with no pinned versions."),
]


def row(cells):
    return "| " + " | ".join(str(c) for c in cells) + " |\n"


def main() -> int:
    reg = json.loads(REG.read_text(encoding="utf-8"))
    run = json.loads(RUN.read_text(encoding="utf-8"))
    entries = reg["entries"]
    n = len(entries)
    k = sum(1 for e in entries if e["auditable"] in ("full", "partial"))
    by = {e["slug"]: e for e in entries}

    # ------------------------------------------------------------ availability report
    L: list[str] = []
    A = L.append
    A("# External audit - artefact availability (the primary result)\n\n")
    A("Generated by `scripts/phase7_external_report.py` from `configs/external_audit_register.json` "
      "and the run record. **Primary finding: of the "
      f"{n} external candidates examined, {k} released artefacts sufficient for an independent "
      "audit.** The harness therefore ran on none of them; what follows records exactly what "
      "each released, in its own words, and what happened when the one released codebase was "
      "executed.\n\n")
    A("Categories. *released* / *partial* / **upon request** / *none* / *not stated*. "
      "\"Available upon request\" is recorded as its own category because it is neither released "
      "nor unavailable. That phrasing is widely documented as rarely resulting in an actual data "
      "transfer; **nothing is claimed here about these specific authors, because no request was "
      "made.**\n\n")
    A("## Availability by candidate\n\n")
    A(row(["candidate", "kind", "code", "weights", "per-subject predictions", "subject ids",
           "splits documented", "demographics", "auditable"]))
    A(row(["---"] * 9))
    for e in entries:
        A(row([e["slug"], e["kind"], e["code_released"], e["weights_released"], e["predictions_released"],
               e["subject_ids"], e["splits"], e["demographics"], f"**{e['auditable']}**"]))
    A("\n## Availability statements, verbatim\n\n")
    for e in entries:
        A(f"### {e['slug']}\n\n")
        A(f"- **What:** {e['paper']}\n- **Where:** {e['links']}\n")
        A(f"- **Data availability statement:** {e['data_availability_statement'] or 'not stated'}\n")
        A(f"- **Code availability statement:** {e['code_availability_statement'] or 'not stated'}\n")
        A(f"- **Checks possible:** {e['checks_possible']}\n")
        if e.get("notes"):
            A(f"- **Notes:** {e['notes']}\n")
        A("\n")

    A("## The one released codebase, executed\n\n")
    A(SCOPE)
    env = run["environment"]
    A(f"- Isolated environment: `{env['python']}` (not the HemoSight venv). `requirements.txt` "
      f"installs as written: **{env['requirements_txt_installs_as_written']}** - {env['requirements_txt_failure']}. "
      f"An installable subset plus the imports the notebooks use but the file omits was installed; "
      f"{env['note']}.\n")
    A("- Rules: " + "; ".join(run["rules"]) + ".\n\n")
    A(row(["notebook", "cells run before failure", "first error", "what was missing"]))
    A(row(["---"] * 4))
    for r in run["notebooks"]:
        fc = r.get("failed_cell") or {}
        ev = (fc.get("evalue") or r.get("error") or "")[:160].replace("|", "\\|")
        missing = ("an unreleased preprocessed array" if "npy" in ev else
                   "the unreleased augmented-image folder" if "Augmented" in ev else
                   "a cleaned Italy sheet the authors did not release (the dataset's own Italy.xlsx has decimal commas and an `_` row)" if "Hgb" in ev else
                   "a pinned Keras 2 environment (and the PH2 / HAM10000 archives)" if "keras" in ev.lower() or "Import" in (fc.get("ename") or "") else "-")
        A(row([r["notebook"], r["cells_run"], f"`{fc.get('ename') or 'runner'}`: {ev}", missing]))
    s = run["summary"]
    A(f"\n**{s['ran_to_completion']} of {s['notebooks']} notebooks ran to completion; per-subject "
      "predictions produced: 0.** Whether a released artefact runs is part of the availability "
      "finding, and here the released code depends on intermediates that were never released.\n\n")
    A("### Observations from the code text - NOT harness verdicts\n\n")
    A("The harness ran on nothing, so it returned no verdict. The following are readings of the "
      "released code, offered with the scope caveat above and with no generalisation:\n\n")
    for where, obs in CODE_OBSERVATIONS:
        A(f"- **{where}** - {obs}\n")
    A("\nNo demographic or population baseline appears in any notebook (one notebook plots Hgb "
      "against age and gender without fitting a baseline); India and Italy are pooled; no duplicate "
      "check appears; no notebook carries saved outputs, so there is no reported number to compare "
      "against.\n\n")
    A("## What this establishes\n\n")
    A(f"- **{k} of {n}** candidates could be audited by the harness. The reasons differ and are "
      "recorded separately: one released code whose inputs were not released; one released a paper "
      "with data \"upon reasonable request\" and no code statement; one could not be located as a "
      "primary source.\n")
    A("- \"Not auditable\" and \"audited and failed\" are different findings. No candidate is "
      "recorded as failing any check, because no check ran.\n")
    A("- The sample is three candidates chosen by the user, not a survey of the field; the count "
      "above is a measurement of these three releases and nothing more. The path to a "
      "field-level statement is more entries in the register, not extrapolation from this one.\n")
    (paths.REPORTS / "external_audit_availability.md").write_text("".join(L), encoding="utf-8")

    # ------------------------------------------------------------ external_audit.md
    M: list[str] = []
    B = M.append
    B("# External audit - Phase 7 Task 3B\n\n")
    B(f"**Lead result: {k} of {n} external candidates could be independently audited.** "
      "The harness therefore produced no verdict on any external model. The availability "
      "record is the primary output of this task and is in "
      "`reports/external_audit_availability.md`; the register is `reports/external_audit_register.md`.\n\n")
    B("## How many, and why not\n\n")
    B(row(["candidate", "could it be audited?", "why"]))
    B(row(["---"] * 3))
    B(row(["anemia-detection (student repository)", "no",
           "code released, but every notebook depends on preprocessed arrays, an augmented-image "
           "folder or a cleaned spreadsheet that were not released; 0 of 7 notebooks ran; no weights, "
           "no predictions"]))
    B(row(["BPANet (Lin et al. 2025)", "no",
           "data \"available from the corresponding authors upon reasonable request\"; no code "
           "availability statement; no released predictions or weights; not requested"]))
    B(row(["\"Hemo-ConViT\"", "no", "no primary source located (Europe PMC, Crossref, arXiv: 0 hits)"]))
    B("\n## Harness output\n\n")
    B("None. The external path (`hemosight.audit.ingest`, `scripts/external_audit.py`) was "
      "exercised end to end on the one released codebase up to the point where a predictions "
      "table would be ingested; that point was never reached. For the record, the path's "
      "behaviour on a release-shaped table is demonstrated only on a SYNTHETIC smoke test "
      "(`data/interim/phase7/external/_smoke_synthetic`, labelled as such), and the "
      "INSUFFICIENT DATA behaviour on assumed subject ids is covered by `tests/test_phase7.py`.\n\n")
    B("## Methodology from paper text, for the paper that could not be run\n\n")
    e = by["bpanet-lin-2025"]
    B(f"BPANet's full text was read. {e['checks_possible']}. These are entered in "
      "`reports/literature_gap.md` as **NOT REPORTED** where the paper does not state an item - a "
      "value distinct from UNKNOWN (paper not read) and from NO (this project measured a problem). "
      "**NOT REPORTED is not a failed check**; no check ran.\n\n")
    B("## The student repository\n\n")
    B(SCOPE)
    B("Run record: `data/interim/phase7/external/anemia-detection/run_results.json`; executed "
      "copies with their first error under `runs/`. The cloned repository was not modified.\n\n")
    B("## What would change the result\n\n")
    B("- A release of per-subject predictions with subject ids and the split used - for any model - "
      "would let all eight checks run; a release of predictions alone would let the demographic "
      "baseline, permutation and (with images) duplicate checks run.\n")
    B("- Every further candidate goes into the register whether or not it can be audited. If most "
      "cannot, that is a measured finding about reproducibility in this field and will be reported "
      "as one - after enough entries to support it, which three is not.\n")
    (paths.REPORTS / "external_audit.md").write_text("".join(M), encoding="utf-8")
    print(f"wrote external_audit_availability.md and external_audit.md ({k} of {n} auditable)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
