"""Phase 3.5, Task 5: generate reports/phase3_5_ratio.md.

Task 1's result is stated first and prominently. Thresholds were declared in CLAUDE.md
before anything ran.

    .\\.venv\\Scripts\\python.exe scripts\\phase3_5_report.py
"""

from __future__ import annotations

import json

from hemosight.io import paths
from hemosight.simulation.optical_data import (
    camspec_database,
    compare_with_transcribed,
    melanin_powerlaw_fit,
)

IN = paths.INTERIM / "phase3_5"
P3 = paths.INTERIM / "phase3"


def load(p):
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def row(cells):
    return "| " + " | ".join(str(c) for c in cells) + " |\n"


def main() -> int:
    t1 = load(IN / "task1_cancellation.json")
    t3 = load(IN / "task3_stability.json")
    gate_new = load(P3 / "task0_gate.json")
    gate_old = load(P3 / "task0_gate_TRANSCRIBED.json")

    L: list[str] = []
    A = L.append
    A("# Phase 3.5 - The ratio reformulation: REFUTED\n\n")
    A("Generated by `scripts/phase3_5_report.py`.\n\n")

    # ---------------------------------------------------------------- TASK 1
    if t1:
        eq = t1["best_equivalent_hb_g_dl"]
        best = t1["best_ratio_feature"]
        A("## 1. TASK 1 RESULT - stated first because it ends the phase\n\n")
        A("> ## ⛔ **REFUTED**\n")
        A(f"> The best ratio feature (`{best}`) leaves a within-subject spread of "
          f"**{t1['spread'][best]['mean_pairwise_dE']:.3f} dE2000**, which at the ratio's own "
          f"sensitivity of {t1['ratio_sensitivity_de_per_g_dl']:.3f} dE2000 per g/dL is an "
          f"**equivalent residual of {eq:.2f} g/dL**.\n")
        A(f">\n> The threshold declared before running was **>2.0 g/dL = the "
          f"reformulation does not rescue the claim**. This is {eq/2.0:.1f}x that.\n")
        A(">\n> **Work stopped. Task 2 was not run**, as the pre-declared protocol "
          "required.\n\n")

        A("### Every ratio feature is worse than doing nothing\n\n")
        A(row(["feature", "within-subject dE2000", "equivalent g/dL", "n subjects"]))
        A(row(["---"] * 4))
        for m, v in sorted(t1["spread"].items(), key=lambda kv: kv[1]["mean_pairwise_dE"]):
            label = f"**{m}**" if m.count("_over_") else m
            A(row([label, f"{v['mean_pairwise_dE']:.3f}",
                   f"{v['equivalent_hb_g_dl']:.2f}", v["n_subjects"]]))
        A("\nFor comparison, the same protocol in Phases 2 and 2.5 gave: no correction "
          "9.530, grey-world full frame 6.076, grey-world at 25% FOV 3.935, "
          "sclera-referenced 7.427, specular 7.821 dE2000.\n\n")
        A("**The uncorrected sclera (5.682) beats all three ratio features.** This is "
          "not a marginal miss - taking a ratio actively destroys information.\n")

    # ------------------------------------------------- implementation check
    A("\n### The algebra is right and the implementation is right\n\n")
    A("A negative result on a method that is *algebraically* guaranteed deserves proof "
      "that the machinery works before the conclusion is accepted. Applying a synthetic "
      "diagonal illuminant change to a real frame and re-measuring the ratio:\n\n")
    A(row(["region summariser", "ratio spread across synthetic illuminants"]))
    A(row(["---", "---"]))
    A(row(["plain mean (exactly diagonal-invariant)", "**0.000000 dE2000**"]))
    A(row(["robust percentile-trimmed mean (as used)", "0.046 dE2000"]))
    A("\n**The illuminant cancels exactly, to machine precision.** The observed spread "
      "on real captures is 6.399 dE2000 - **139x larger than the implementation's own "
      "residual**. So the illuminant genuinely does cancel, and almost none of the real "
      "variation between captures is an illuminant change.\n\n")
    A("(The 0.046 residual on the trimmed summariser is itself explainable: rescaling "
      "channels changes which pixels fall inside the luminance percentile window, so a "
      "slightly different pixel set is averaged. Negligible here, but worth knowing.)\n")

    # ---------------------------------------------------------------- WHY
    if t1 and t3:
        A("\n---\n\n## 2. Why it fails - two mechanisms, both measured\n\n")
        A("### 2.1 The reference is noisier within a subject than between subjects\n\n")
        A("The ratio method does not need the sclera to be the same across people. It "
          "needs it to be the same across captures **of one person**. Those are "
          "different requirements, so they were measured separately:\n\n")
        A(row(["dataset", "within-subject dE2000", "between-subject dE2000",
               "within/between", "regime"]))
        A(row(["---"] * 5))
        for name, r in t3.items():
            if not isinstance(r, dict) or "within_subject_dE" not in r:
                continue
            ratio = r["ratio_within_over_between"]
            regime = "**unusable**" if ratio >= 1.0 else "marginal" if ratio > 0.5 else "usable"
            A(row([name, f"{r['within_subject_dE']:.3f}", f"{r['between_subject_dE']:.3f}",
                   f"**{ratio:.3f}**", regime]))
        A("\n**On phone captures the sclera varies MORE across captures of the same "
          "person (5.860) than it does between different people (4.050).** The ratio "
          "1.447 is the wrong side of 1. A reference that is noisier than the population "
          "it normalises against is not a reference - dividing by it adds more variance "
          "than it removes, which is exactly what the Task 1 table shows.\n\n")
        A("Under controlled studio conditions (SBVPI) within-subject variation falls "
          "**3.5x**, from 5.860 to 1.685, and the ratio improves to 0.924. That is "
          "informative: the instability is dominated by capture conditions - geometry, "
          "gaze, specular contamination, focus - not by the tissue changing. But even in "
          "a studio the ratio is only 0.92, still not the << 1 regime the method needs.\n")

        A("\n### 2.2 von Kries diagonality is breaking down\n\n")
        A("Under a true diagonal model a within-image ratio cancels the illuminant "
          "**and** the camera's per-channel gains, so the phone effect should largely "
          "disappear. It does not:\n\n")
        A(row(["method", "phone variance fraction", "lighting", "between-subject"]))
        A(row(["---"] * 4))
        for m in ("uncorrected_sclera", "greyworld_sclera", "iris_over_sclera",
                  "pupil_over_sclera", "pupil_over_iris"):
            v = t1["variance"].get(m)
            if v:
                A(row([m, f"**{v['frac_within_phone']:.3f}**",
                       f"{v['frac_within_lighting']:.3f}",
                       f"{v['frac_between_subject']:.3f}"]))
        A("\nThe ratio leaves the phone effect at **0.177**, against 0.202 uncorrected "
          "and 0.177 for grey-world - essentially unchanged. Real camera sensitivities "
          "overlap enough that an illuminant change is not a per-channel gain, so the "
          "sensor-specific error survives a transformation that should have removed it. "
          "This is the signature the phase was designed to look for.\n")

        A("\n### 2.3 The ratio amplifies signal, but amplifies noise more\n\n")
        A(row(["quantity", "absolute colour", "ratio feature", "change"]))
        A(row(["---"] * 4))
        A(row(["signal, dE2000 per g/dL", "0.452", f"{t1['ratio_sensitivity_de_per_g_dl']:.3f}",
               f"**{t1['ratio_sensitivity_de_per_g_dl']/0.452:.2f}x better**"]))
        A(row(["noise, within-subject dE2000", "3.330 (grey-world)", "6.399",
               "**1.92x worse**"]))
        A(row(["net equivalent residual, g/dL", "5.23", f"{t1['best_equivalent_hb_g_dl']:.2f}",
               "**1.92x worse**"]))
        A("\nThe ratio does raise the haemoglobin signal, by 1.4x. It raises the noise by "
          "1.9x. Reporting only the first would have been the easy mistake here; the net "
          "effect is what matters and it is negative.\n")

    # ----------------------------------------------------------- per-subject offset
    if t3:
        A("\n---\n\n## 3. Would a per-subject offset help? No, twice over\n\n")
        A("**First: it removes the wrong term.** An offset subtracts a per-subject mean, "
          "which eliminates the *between*-subject variation and leaves the *within*-"
          "subject variation untouched. On MOBIUS that means removing 4.050 dE2000 and "
          "leaving **5.860** - it removes the smaller term and leaves the larger one. "
          "The problem is not that people differ; it is that one person's own captures "
          "differ.\n\n")
        A("**Second: it is not obtainable.** " + t3["offset_note"] + "\n")

    # ---------------------------------------------------------------- TASK 0
    A("\n---\n\n## 4. Task 0: the downloaded constants changed real numbers\n\n")
    cmp = compare_with_transcribed()
    A(row(["comparison", "value"]))
    A(row(["---", "---"]))
    A(row(["points compared", cmp["n_points"]]))
    A(row(["median relative error", f"{cmp['median_rel_error']*100:.2f}%"]))
    A(row(["max relative error", f"**{cmp['max_rel_error']*100:.0f}%**"]))
    A(row(["fraction of points >10% off", f"**{cmp['frac_above_10pct']*100:.1f}%**"]))
    A("\n### Worst disagreements\n\n")
    A(row(["quantity", "nm", "downloaded", "transcribed", "relative error"]))
    A(row(["---"] * 5))
    for r in cmp["worst_points"][:8]:
        A(row([r["quantity"], f"{r['wavelength_nm']:.0f}", f"{r['downloaded']:.1f}",
               f"{r['transcribed']:.1f}", f"{r['rel_error']*100:.0f}%"]))
    A("\nThe transcription had deoxy-haemoglobin far too high across the blue "
      "(460-490 nm) and the far red. **Note that the Phase 3 isosbestic self-check "
      "PASSED on this bad data** - it verified where the two curves cross, which was "
      "right, while the values between the crossings were wrong. A consistency check is "
      "not a verification, exactly as flagged at the time.\n")

    if gate_new and gate_old:
        A("\n### Effect on the Phase 3 gate: unchanged verdict, slightly worse\n\n")
        A(row(["residual dE2000", "MAE g/dL (transcribed)", "MAE g/dL (SOURCED)", "band now"]))
        A(row(["---"] * 4))
        for k in ("1.0", "2.0", "3.935", "6.076"):
            o = gate_old["residuals"][k]["mae_g_dl"]
            n = gate_new["residuals"][k]["mae_g_dl"]
            A(row([k, f"{o:.3f}", f"**{n:.3f}**", gate_new["residuals"][k]["band"]]))
        A("\nThe Phase 3 conclusion stands on sourced data and is marginally stronger: "
          f"**{gate_new['residuals']['3.935']['mae_g_dl']:.3f} g/dL** at the measured "
          "residual, and the 2.0 dE2000 case has moved from MARGINAL to NOT RECOVERABLE.\n")

    A("\n### Melanin: confirmed to be a fitted power law, not measured data\n\n")
    f = melanin_powerlaw_fit()
    A(f"Fitting `mu_a = A * lambda^-k` to the spectralLIB melanin curve gives "
      f"**A = {f['amplitude']:.3g}, k = {-f['exponent']:.3f}**, with a maximum "
      f"log-residual of **{f['max_abs_log_residual']:.6f}**. It is *exactly* a power "
      f"law - there is no measured structure in it at all.\n\n")
    A("Combined with the Phase 3 finding that a melanin volume fraction of 0.005 shifts "
      "recovered haemoglobin by **+9.6 g/dL**, this is now the single most consequential "
      "assumption in the model: a quantity the result is extremely sensitive to, which "
      "varies substantially between individuals, and which is known only through a "
      "smooth fit. It is flagged in `constants.py` as something to **sweep, never fix**, "
      "and it is the mechanism by which this method would be biased by skin tone.\n")

    db = camspec_database()
    A(f"\n### Camera sensitivities\n\n{len(db['cameras'])} cameras parsed from the Jiang "
      "camspec database (400-720 nm at 10 nm), plus an average mobile-phone SSF which is "
      "more representative of this project's actual inputs than any DSLR. **Only 2 of the "
      "6 nus8 cameras have a close match** (Canon 600D exactly; Canon 1DMarkIII against "
      "the 1Ds Mark III, a different body). Fujifilm X-M1 and Samsung NX2000 are absent "
      "entirely.\n")

    # ---------------------------------------------------------------- verdict
    A("\n---\n\n## 5. Verdict\n\n")
    A("### The ratio reformulation: **REFUTED**\n\n")
    A("### The imaging arm of this project: **definitively a negative result**\n\n")
    A("Both formulations of the imaging claim have now been tested and both have "
      "failed, each with a measured mechanism:\n\n")
    A(row(["formulation", "phase", "result", "mechanism"]))
    A(row(["---"] * 4))
    A(row(["Absolute illuminant recovery from the sclera", "2", "REFUTED",
           "loses to grey-world; p ~ 3e-8"]))
    A(row(["Absolute illuminant recovery from corneal specular", "2.5", "REFUTED",
           "no better than sclera, p = 0.29"]))
    emp = load(P3 / "empirical_signal.json")
    emp_sig = f"{emp['headline']['de_per_g_dl']:.2f}" if emp else "?"
    A(row(["Absolute colorimetric Hb inversion", "3", "NOT RECOVERABLE",
           f"signal 0.45 (sim) / {emp_sig} (measured) dE2000/g/dL vs 3.9 noise"]))
    A(row(["Illuminant-free within-image ratio", "3.5", "**REFUTED**",
           "reference noisier within-subject than between; diagonality fails"]))
    A("\nThe negative result is now comprehensive rather than partial. The project has "
      "tested the two available reference surfaces, both available formulations "
      "(absolute and ratio), and the inversion itself, on 100 subjects across 3 devices "
      "and 3 lighting conditions, with pre-declared thresholds in every case.\n\n")
    A("**Stated plainly and without softening: haemoglobin cannot be recovered from "
      "ambient-light RGB photographs of the eye at the accuracy any deployment would "
      "need, and the reasons are now quantified rather than speculated.** The eye does "
      "carry its own reference surfaces, and the illuminant does cancel in a ratio "
      "exactly as the algebra promises - but the reference surfaces are not stable "
      "enough across captures of the same person for either route to work, and the "
      "haemoglobin signal is far below the residual error either route leaves.\n\n")
    A("No third reformulation is proposed.\n")

    A("\n### What survives, and it is not nothing\n\n")
    A("* **The PPG arm is unaffected and is now co-primary.** Four narrow wavelengths, "
      "a controlled source, and no ambient illuminant to estimate - the entire error "
      "term that defeated Phases 2, 2.5, 3 and 3.5 does not exist there. It is also the "
      "project's best-labelled data: 252 subjects with venous HemoCue reference.\n")
    A("* **N1a stands**: 0.666 deg angular error across six sensors given a reference of "
      "known reflectance.\n")
    A("* **The segmentation pipeline stands**: sclera IoU 0.875, 0% failure on Eyes-Defy.\n")
    A("* **A quantified account of why four plausible approaches fail**, each with a "
      "mechanism and a pre-declared threshold. Most of the literature this project set "
      "out to improve on reports single-site accuracy without cross-device validation; "
      "this is a more honest contribution than that, even though it is negative.\n")

    (paths.REPORTS / "phase3_5_ratio.md").write_text("".join(L), encoding="utf-8")
    print(f"wrote {paths.REPORTS / 'phase3_5_ratio.md'}")
    if t1:
        print(f"  TASK 1: {t1['band']} at {t1['best_equivalent_hb_g_dl']:.2f} g/dL equivalent")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
