"""Phase 1, Task 5: reports/phase1_summary.md.

Per-dataset sanity tables, the overlap decision, exact split sizes, and the
"what this data CANNOT support" list that bounds every claim the project may make.
That last list is the deliverable, not a formality: it goes into the paper's
limitations section.

    .\\.venv\\Scripts\\python.exe scripts\\phase1_summary.py
"""

from __future__ import annotations

import json

import pandas as pd

from hemosight.io import paths


def md_table(df: pd.DataFrame, floatfmt: str = "{:.2f}") -> str:
    d = df.copy()
    for c in d.columns:
        if pd.api.types.is_float_dtype(d[c]):
            d[c] = d[c].map(lambda v: "" if pd.isna(v) else floatfmt.format(v))
    d = d.astype(str)
    head = "| " + " | ".join([d.index.name or ""] + list(d.columns)) + " |"
    sep = "| " + " | ".join(["---"] * (len(d.columns) + 1)) + " |"
    rows = ["| " + " | ".join([str(i)] + list(r)) + " |" for i, r in zip(d.index, d.values)]
    return "\n".join([head, sep] + rows)


def main() -> int:
    master = pd.read_csv(paths.MANIFESTS / "master.csv")
    nus = pd.read_csv(paths.MANIFESTS / "nus8.csv")
    splits = json.loads((paths.SPLITS / "split_summary.json").read_text(encoding="utf-8"))
    ov = json.loads((paths.OVERLAP / "overlap_results.json").read_text(encoding="utf-8"))
    pool = pd.read_csv(paths.SPLITS / "ghana_pool_grouped.csv")
    edx = pd.read_csv(paths.SPLITS / "eyes_defy_crosssite.csv")
    ppg = pd.read_csv(paths.SPLITS / "hb_ppg_grouped.csv")
    hashes = {s: pd.read_csv(paths.OVERLAP / f"hashes_{s}.csv")
              for s in ("cp_anemic", "ghana_conj", "ghana_nail")}

    L: list[str] = []
    A = L.append

    A("# Phase 1 - Summary and Limits\n\n")
    A("Companion to `reports/phase1_data_audit.md`. Generated by ")
    A("`scripts/phase1_summary.py`.\n")

    # ---------------------------------------------------------------- 1 tables
    A("\n## 1. Per-dataset summary\n\n")
    hb = master.dropna(subset=["hb_g_dl"])
    tab = pd.DataFrame({
        "n_subjects": master.groupby("dataset").subject_id.nunique(),
        "n_images": master.groupby("dataset").image_id.size(),
        "imgs_per_subj": (master.groupby("dataset").image_id.size()
                          / master.groupby("dataset").subject_id.nunique()).round(1),
        "hb_min": hb.groupby("dataset").hb_g_dl.min(),
        "hb_max": hb.groupby("dataset").hb_g_dl.max(),
        "n_severe_lt7": hb[hb.hb_g_dl < 7].groupby("dataset").hb_g_dl.size(),
        "n_devices": master.groupby("dataset").device_model.nunique(),
        "age_min": master.groupby("dataset").age.min(),
        "age_max": master.groupby("dataset").age.max(),
    })
    tab["n_severe_lt7"] = tab["n_severe_lt7"].fillna(0)
    tab.index.name = "dataset"
    A(md_table(tab))

    A("\n\n### Severity distribution (only CP-AnemiC ships severity labels)\n\n")
    cp = pd.read_csv(paths.MANIFESTS / "cp_anemic.csv")
    sev = cp.severity.value_counts().to_frame("images")
    sev.index.name = "severity"
    A(md_table(sev))

    A("\n\n### Effective (deduplicated) size\n\n")
    dd = pd.DataFrame([{
        "dataset": k, "files": len(v), "unique_images": int(v.md5.nunique()),
        "pct_redundant": round(100 * (1 - v.md5.nunique() / len(v)), 1)}
        for k, v in hashes.items()]).set_index("dataset")
    A(md_table(dd, "{:.1f}"))
    A("\n\nHeadline file counts overstate these datasets by roughly a factor of two.\n")

    # ---------------------------------------------------------------- 2 overlap
    A("\n## 2. Overlap findings and the decision taken\n\n")
    p0 = next(p for p in ov["pairs"] if p["pair"] == "cp_anemic|ghana_conj")
    A(f"""
**Finding 1 - CP-AnemiC is contained inside the Ghana conjunctiva set.**
{p0['md5_distinct_hashes_shared']} distinct MD5 hashes are shared;
{p0['phash_n_below_thresh']}/{p0['n_a']} ({100*p0['phash_frac_below_thresh']:.1f}%) of CP-AnemiC images have a
pHash neighbour within Hamming 10 in the Ghana set; {p0['embed_n_above']}/{p0['n_a']} exceed
0.92 embedding cosine. Four independent signals agree.

**DECISION: they remain ONE site.** Every cross-site claim must respect this. Any
result that trains on one and tests on the other is testing on its own training data.

**Finding 2 - CP-AnemiC Hb labels conflict on duplicated images.** 710 files, 498
unique images; 90 of 91 exact-duplicate groups carry more than one distinct Hb value.
**DECISION: CP-AnemiC Hb is not a trustworthy per-image regression target** on the
duplicated subset (303/710 files). Deduplicate and treat conflicted groups as
unlabelled, or exclude them; either way the choice must be stated in results.

**Finding 3 - conjunctiva and nail sets share participants.** Non-anemic subject
numbers match 204/204 (Jaccard 1.000); anemic 250/271 (0.919).
**DECISION: flagged as an N6 opportunity**, not contamination - approximately 454
participants with paired conjunctiva and nail images. They must still be grouped
together when splitting, which the leak-proof grouping already does.
""")

    # ---------------------------------------------------------------- 3 splits
    A("\n## 3. Exact split sizes\n\n")
    A(f"Seed `{splits['seed']}`, config `configs/phase1_splits.yaml`. ")
    A(f"Leak check: **{splits['leak_check']}**.\n")

    A("\n### Ghana pool (cp_anemic + ghana_conj + ghana_nail = one site)\n\n")
    g = pool.groupby("split").agg(images=("image_id", "count"),
                                  groups=("group", "nunique"),
                                  nominal_subjects=("subject_id", "nunique"),
                                  anemic_images=("anemia_label", "sum"))
    g.index.name = "split"
    A(md_table(g, "{:.0f}"))
    A(f"\n\n{splits['ghana_pool']['nominal_subject_ids']} nominal subject ids collapse to ")
    A(f"**{splits['ghana_pool']['leakproof_groups']} leak-proof groups**. The difference is ")
    A("leakage a plain subject-level split would have allowed.\n")

    A("\n### Eyes-Defy cross-site protocols\n\n")
    e = edx.groupby(["protocol", "split"]).agg(images=("image_id", "count"),
                                               subjects=("subject_id", "nunique"),
                                               with_hb=("hb_g_dl", lambda s: int(s.notna().sum())))
    A(md_table(e.reset_index().set_index("protocol"), "{:.0f}"))

    A("\n\n### Hb PPG\n\n")
    p = ppg.groupby("split").agg(subjects=("subject_id", "nunique"),
                                 hb_mean=("hb_g_dl", "mean"),
                                 hb_min=("hb_g_dl", "min"), hb_max=("hb_g_dl", "max"))
    p.index.name = "split"
    A(md_table(p))

    A("\n\n### nus8\n\n")
    A(f"{len(nus)} images, {nus.camera.nunique()} cameras, per-camera 3-fold CV ")
    A("(`nus8_cv3.csv`) plus leave-one-camera-out (`nus8_leave_one_camera_out.csv`).\n\n")
    nn = nus.groupby("camera").image_id.count().to_frame("images")
    nn.index.name = "camera"
    A(md_table(nn, "{:.0f}"))

    # ---------------------------------------------------------------- 4 limits
    A("""

## 4. What this data CANNOT support

> **Updated after Phase 1.5 (2026-09-11).** Items marked **[1.5]** were added or
> rewritten by the remediation. See `reports/phase1_5_remediation.md`.

This list bounds every claim the project may make. It is derived from the audit, not
from caution. Each item names the constraint and the claim it limits.

### 4.1 [1.5] N1c is bounded to 218 subjects; N1a and N1b are not
CP-AnemiC and the Ghana conjunctiva set are pre-segmented cutouts: **the least-cropped
image among all 4,972 is still 49.7% black**, and the largest is 0.14 MP against
Eyes-Defy's 11.9 MP. The sclera - N1's white reference - is absent. A full, exhaustive
search (not sampled) found **no uncropped originals anywhere on disk**, including inside
`Fingernails.rar`, which is a compressed copy of the same cutouts. That question is
closed.

Phase 1.5 responded by splitting N1 rather than weakening it:
* **N1a** (illuminant accuracy) - `nus8`, 6 cameras, 1,265 images. Unaffected.
* **N1b** (sclera as a valid white reference) - `MOBIUS` 3 phones x 3 lighting x 100
  subjects, plus `SBVPI`. Needs no Hb labels. Unaffected.
* **N1c** (end-to-end Hb) - Eyes-Defy only: **218 subjects, 2 sites, 2 regional variants
  of one Galaxy S6, no severe cases**. This limitation must appear in every N1c claim.

### 4.2 There is effectively one conjunctiva site with Hb, not three
CP-AnemiC is a labelled subset of the Ghana conjunctiva collection. Ghana conjunctiva
and Ghana fingernails share a participant roster. **The entire Ghana pool is one site,
one population, one collection protocol.** With Eyes-Defy's two sites, the project has
**three genuinely independent sites in total** (Ghana, India, Italy) - and only two of
them have both full photographs and haemoglobin.

### 4.3 [1.5] The trustworthy haemoglobin base is 469 rows with ZERO severe cases
The Phase 1.5 arbitration rejected every Hb value in the Ghana pool. CP-AnemiC's Hb is
not self-consistent (90 of 91 duplicate groups conflict; worst spread **7.10 g/dL within
one byte-identical image**), and the Ghana conjunctiva set ships **no Hb at all**. The
flag `hb_label_trusted` enforces this in the manifests.

What remains: **469 trusted rows** - 217 Eyes-Defy + 252 Hb_PPG - spanning 7.0-17.4
g/dL. **None is below 7 g/dL.** All 48 real severe cases sit in the rejected set.
Therefore **no calibrated claim about severe anemia is available from real data at all**,
and the N2 simulator's severe range cannot be validated against any trustworthy real
case. This is the corrected justification for N2.

Additionally, the binary label that the Ghana pool retains carries its **own 1.67% noise
floor**: on the 419 images present in both collections the two disagree on 7. No binary
result on that pool may claim accuracy above ~98.3% and attribute the gap to the model.

### 4.4 N2's premise as written is false and must be narrowed
"No public dataset contains severe anemia" is contradicted by CP-AnemiC's 48 cases
(minimum 3.1 g/dL). The defensible claim is that severe cases are rare, confined to a
single site, and carry unreliable labels.

### 4.5 Device diversity and haemoglobin never co-occur
EXIF is stripped from CP-AnemiC and both Ghana sets: **device is unknown for 9,232 of
the 9,450 conjunctiva/nail images.** Eyes-Defy has exactly two models, `SM-G920F` and
`SM-G920I` - regional variants of one Samsung Galaxy S6, so its India/Italy contrast is
barely a device contrast at all.

Real device diversity exists, but only where Hb does not:

* **MOBIUS** - 3 phones (Sony Xperia Z5 Compact, Apple iPhone 6s, Xiaomi Pocophone F1)
  crossed with 3 lighting conditions (indoor / natural / poor) over 100 subjects,
  recoverable from the filename grammar. No haemoglobin.
* **nus8** - 6 cameras with ground-truth illuminants. No people.

So cross-device behaviour can be characterised for *segmentation and illuminant
estimation*, but **never for the haemoglobin estimate itself**. N5's "stratify by
source device" cannot be executed on any dataset that has an Hb label. Report the
device axis as an upstream-only analysis and say so plainly.

### 4.6 [1.5] Skin tone has no ground truth; ITA is a proxy confounded with site
SCIN was removed from the project in Phase 1.5 and deleted from disk: it held no data (5
documentation files), and as dermatology imagery with no conjunctiva, no Hb and no
participant overlap, its labels could not be attached to any subject here without an
unvalidated cross-domain transfer.

N5 now estimates skin tone by **Individual Typology Angle on N1-calibrated periocular
skin**, which needs no external dataset and makes the melanin-vs-illuminant
decomposition mechanistic. Its limitations, to be carried verbatim into the paper:
**there are no ground-truth skin tone labels in this project; ITA is a proxy, not a
measurement; and the tone axis is confounded with site** (India vs Italy is
simultaneously a population, a tone and a capture-condition contrast).

### 4.7 Severe age skew between sites confounds any cross-site comparison
CP-AnemiC is children **6-60 months**. Eyes-Defy is adults **19-88**. Hb_PPG is adults
**21-90**. Conjunctival appearance, blood volume and eyelid tissue thickness all vary
with age. **A model trained on Ghanaian children and tested on Italian adults changes
population and age simultaneously**, so a performance drop cannot be attributed to
site. No published result may describe that transfer as a clean cross-site test.

### 4.8 Geographic and population narrowness
Two countries supply all conjunctiva images with Hb: Ghana (one collection, children)
and Italy/India (one collection, adults). Hb_PPG adds one further population for PPG
only. **There is no African adult conjunctiva data, no paediatric data outside Ghana,
and no population from the Americas, East Asia or Oceania anywhere in the collection.**

### 4.9 Roughly half of every Ghana file count is redundant
Ghana conjunctiva: 2,015 unique images among 4,262 files. Ghana fingernails: 2,097
among 4,260. CP-AnemiC: 498 among 710. **Any "n=4,262" claim is wrong by about 2x.**
Report deduplicated counts.

### 4.10 [1.5] N6 scope: conjunctiva+nail classification only; image+PPG simulation-only
These are **fixed scope limits, not open problems to be solved later.**
* The ~454 participants with paired conjunctiva and nail images are in the
  BINARY-LABEL-ONLY pool, so **real fusion is classification only**. No fused, calibrated
  Hb estimate in g/dL can be validated on paired modalities.
* `Hb_PPG_Dataset` shares no participants with any image dataset, and under the "no new
  data ever" constraint it never will. **Image+PPG fusion is simulation-only,
  permanently.** Any such result must be labelled a simulation result.

### 4.11 Two nus8 cameras are missing
Six of eight cameras are extracted (SonyA57 and PanasonicGX1 are not). The cross-sensor
claim is over six sensors; say six, not eight.

### 4.12 No clinical claim is available at any point
All data is retrospective and public. There is no prospective validation, no
reference-standard comparison under controlled conditions, and no clinical population
sampled for this project. **Screening framing only, everywhere, permanently.**
""")

    out = paths.REPORTS / "phase1_summary.md"
    out.write_text("".join(L), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
