"""Phase 6.5 closure report: reports/phase6_5_closure.md.

Every number is read from the artefacts the phase produced; nothing is typed in.
"""
from __future__ import annotations

import json

from hemosight.io import paths

I = paths.INTERIM


def load(rel):
    p = I / rel
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def row(cells):
    return "| " + " | ".join(str(c) for c in cells) + " |\n"


def main() -> int:
    emp = load("phase3/empirical_signal.json")
    cnn = load("phase6_5/image_cnn.json")
    ill = load("phase6_5/eyes_defy_illuminant.json")
    hv = load("phase6/harness_validation.json")
    regen = load("phase6/known_truth/phase5_deep_model_regeneration.json")
    gate = load("phase3/task0_gate.json")
    assert emp and cnn and hv, "run the Phase 6.5 scripts first"

    H, NS, PN = emp["headline"], emp["noise_over_signal"], emp["permutation_null"]
    L: list[str] = []
    A = L.append
    A("# Phase 6.5 - closure of every outstanding item before the write-up\n\n")
    A("Generated by `scripts/phase6_5_report.py` from the phase's artefacts. Items are in "
      "the order they were run; Task 1 was completed and its verdict checked before "
      "anything else was started, as instructed.\n\n")

    # ------------------------------------------------------------------ Task 1
    A("## 1. TASK 1 - the empirical colour-per-haemoglobin signal, re-measured\n\n")
    A("### What was on record\n\n")
    A("`scripts/phase3_report.py` carried the string **\"~0.70 dE2000 per g/dL, 216 "
      "Eyes-Defy subjects, binned by haemoglobin, n=3 lowest bin excluded\"** with no "
      "producing script and no output file. It was the numerator of the 5.6x "
      "noise-to-signal ratio.\n\n")
    A("### What the measurement found\n\n")
    A("`scripts/phase3_empirical_signal.py` -> `data/interim/phase3/empirical_signal.json` "
      f"({emp['n_subjects']} subjects; {emp['n_skipped']} lack a palpebral mask). Per-subject "
      "palpebral colour from the dataset's own mask (three mask encodings were found and "
      "handled: alpha cutout, white-background cutout, 3-channel), mean linear-sRGB "
      "luminance-trimmed 5-95%, CIELAB D65, as captured.\n\n")
    A(row(["estimator", "dE2000 per g/dL", "null (Hb shuffled, 500x)", "p", "reading"]))
    A(row(["---"] * 5))
    b = PN["binned_min_n"]
    A(row(["binned by Hb (the method on record)", f"{H['binned_method_on_record']:.2f}",
           f"{b['null_mean']:.2f} +/- {b['null_sd']:.2f}", f"{b['p_empirical']:.2f}",
           "**cannot measure the signal** - returns ~2.1 with no Hb signal at all"]))
    r1 = PN["regression_site"]
    A(row(["regression, Hb + site", f"{H['upper_bound_site_only']:.2f} (CI "
           f"{H['upper_bound_site_only_ci95'][0]:.2f}-{H['upper_bound_site_only_ci95'][1]:.2f})",
           f"{r1['null_mean']:.2f}", f"{r1['p_empirical']:.3f}",
           "upper bound - counts sex-linked colour as Hb (r(Hb, male) = 0.55)"]))
    r3 = PN["regression_site_sex_age"]
    A(row(["**regression, Hb + site + sex + age (HEADLINE)**",
           f"**{H['de_per_g_dl']:.2f}** (CI {H['ci95'][0]:.2f}-{H['ci95'][1]:.2f})",
           f"{r3['null_mean']:.2f}", f"{r3['p_empirical']:.3f}",
           "the Hb-specific signal; still an upper bound"]))
    A(f"\nPer site (adjusted): India {H['per_site'].get('eyes_defy:India', float('nan')):.2f}, "
      f"Italy {H['per_site'].get('eyes_defy:Italy', float('nan')):.2f}. Grey-world on a tight "
      f"crop: {H['grey_world_tight_crop']:.2f}. Between-subject colour at FIXED Hb, sex, age "
      f"and site: **{H['residual_between_subject_de2000_at_fixed_hb_sex_age_site']:.2f} dE2000** "
      f"= {NS['between_subject_residual_in_hb_equivalents']:.1f} g/dL equivalent - the real "
      "data's own noise floor, under the dataset's own fixed white LED, before any "
      "capture-condition noise.\n\n")
    A("### The verdict on the old figure, and on the gate\n\n")
    A("**The 0.70 figure is WITHDRAWN as a measurement, not corrected.** The method it "
      "was attributed to has a null of ~2.1 dE2000/g/dL: CIEDE2000 between noisy bin means "
      "measures the noise in the means. Whatever it read, it was never a measurement. That "
      f"the adjusted regression ({H['de_per_g_dl']:.2f}, CI {H['ci95'][0]:.2f}-{H['ci95'][1]:.2f}) "
      "brackets 0.70 is coincidence and is not treated as confirmation.\n\n")
    A("**Recomputed downstream quantities.** Nothing was adjusted to match.\n\n")
    A(row(["quantity", "was", "now"]))
    A(row(["---"] * 3))
    A(row(["empirical signal", "~0.70", f"{H['de_per_g_dl']:.2f} (CI {H['ci95'][0]:.2f}-{H['ci95'][1]:.2f})"]))
    A(row(["noise/signal at 3.935 dE2000 (grey-world, 25% FOV)", "5.6x",
           f"{NS['grey_world_25pct_fov_3.935']:.1f}x (CI {NS['grey_world_25pct_fov_3.935_ci95'][0]:.1f}-{NS['grey_world_25pct_fov_3.935_ci95'][1]:.1f})"]))
    A(row(["noise/signal at 6.076 (full frame)", "8.7x", f"{NS['grey_world_full_frame_6.076']:.1f}x"]))
    A(row(["equivalent Hb error at 3.935, empirical", "5.6 g/dL",
           f"{NS['equivalent_hb_error_g_dl_at_3.935']:.1f} g/dL (CI {NS['grey_world_25pct_fov_3.935_ci95'][0]:.1f}-{NS['grey_world_25pct_fov_3.935_ci95'][1]:.1f}); "
           f"{NS['equivalent_hb_error_g_dl_at_3.935_using_upper_bound_signal']:.1f} even with the unadjusted upper-bound signal"]))
    A(row(["model vs empirical", "'within ~1.5x, model slightly conservative'",
           f"model underestimates by {NS['simulated_signal_0.452_ratio_to_empirical']:.1f}x (CI 1.3-2.6x)"]))
    A(row(["Phase 3 Task 0 gate (simulated inversion)", "3.893 g/dL NOT RECOVERABLE",
           f"{gate['gate_mae_at_measured_residual']:.3f} g/dL, unchanged - computed on the model, not on this figure" if gate else "unchanged"]))
    A("\n**Does any verdict change? No.** The Phase 3 gate verdict was computed on the "
      "simulated inversion and is untouched. The empirical cross-check that supported it "
      f"still supports it: {NS['equivalent_hb_error_g_dl_at_3.935']:.1f} g/dL equivalent "
      "error at the measured residual, above the pre-declared 2.0 g/dL NOT RECOVERABLE "
      f"line at the central estimate, at both CI bounds ({NS['grey_world_25pct_fov_3.935_ci95'][0]:.1f}-"
      f"{NS['grey_world_25pct_fov_3.935_ci95'][1]:.1f}), and even under the unadjusted "
      f"upper-bound signal ({NS['equivalent_hb_error_g_dl_at_3.935_using_upper_bound_signal']:.1f}). "
      "Phases 2, 2.5 and 3.5 never used the 0.70 figure: Phase 2/2.5 report dE2000 only, "
      "and Phase 3.5 converts with its own measured ratio sensitivity (0.637) and the "
      "simulated 0.452. The margin the closure rests on is smaller than was written "
      "(4.7x, not 5.6x) and the sim-to-real gap is larger (1.9x, not 1.5x); both are now "
      "stated where the old numbers were.\n\n")
    A("**Two findings the constant could not have produced.** (1) Sex confounds the "
      "colour-Hb relationship in Eyes-Defy exactly as it confounded PPG in Phase 4: "
      f"r(Hb, male) = 0.55, and adjusting for it moves the slope from {H['upper_bound_site_only']:.2f} "
      f"to {H['de_per_g_dl']:.2f}. (2) Between-subject conjunctival colour at fixed Hb, sex, age "
      f"and site is {H['residual_between_subject_de2000_at_fixed_hb_sex_age_site']:.2f} dE2000 "
      f"({NS['between_subject_residual_in_hb_equivalents']:.1f} g/dL equivalent) under a fixed "
      "white LED with ambient light excluded - a noise floor intrinsic to the tissue and "
      "capture, not to calibration, and several times the signal.\n\n")
    A("**Wired in.** `reproduce_all.py` stage \"Phase 3 empirical signal\" (deterministic, "
      "seed 20260911, ~1 min); `phase3_report.py`, `phase3_5_report.py` and "
      "`phase5_final_report.py` read the JSON and refuse to run without it; "
      "`tests/test_phase3.py` fails if the report ever holds a copy, if the binned method "
      "is presented as a measurement, or if the equivalent error drops below 2.0 g/dL "
      "(which would change the verdict and must be reported, not absorbed).\n\n")

    # ------------------------------------------------------------------ Task 2
    A("## 2. TASK 2 - the image CNN baseline (pilot comparison arm)\n\n")
    A(f"**Limitation first.** {cnn['limitation']}\n\n")
    B = cnn["baselines"]; C = cnn["cnn_pooled"]
    A("`scripts/phase6_5_image_cnn.py`, `src/hemosight/baseline/image_cnn.py`: ResNet-18, "
      f"ImageNet initialisation, palpebral bounding-box crop, {cnn['epochs']} epochs, "
      f"{cnn['folds']}-fold subject-disjoint CV (one image per subject), target standardised "
      f"on train folds, geometric augmentation only, {cnn['seeds']} seeds. Bands: {cnn['bands']}.\n\n")
    A("### Pooled 10-fold, identical folds for every row\n\n")
    A(row(["model", "MAE g/dL", "r", "R2", "band"]))
    A(row(["---"] * 5))
    for k, lab in (("population_mean", "population mean"), ("sex_only", "sex alone"),
                   ("demographics_age_sex", "demographics (age, sex)"),
                   ("colour_features_lab", "colour features (mean palpebral Lab + ridge)"),
                   ("colour_features_lab_plus_demographics", "colour features + demographics")):
        v = B[k]
        A(row([lab, f"{v['mae_g_dl']:.3f}", f"{v['pearson_r']:+.3f}", f"{v['r2']:+.3f}", v["band"]]))
    A(row([f"**CNN, seed-averaged ({cnn['seeds']} seeds)**", f"**{C['mae_g_dl']:.3f}**",
           f"{C['pearson_r']:+.3f}", f"{C['r2']:+.3f}", f"**{C['band']}**"]))
    cd = cnn["cnn_plus_demographics"]
    A(row(["CNN + demographics (stacked ridge)", f"{cd['mae_g_dl']:.3f}", f"{cd['pearson_r']:+.3f}",
           f"{cd['r2']:+.3f}", cd["band"]]))
    A(f"\nPer seed: {', '.join(f'{m['mae_g_dl']:.3f}' for m in C['per_seed'])} (SD "
      f"{C['seed_mae_sd']:.4f}). Train MAE {C['train_mae_mean']:.3f}, **train-test gap "
      f"{C['train_test_gap_mean']:+.3f}**. Sex probe on the 512-d penultimate features: "
      f"{cnn['sex_probe']['accuracy']:.3f} vs base rate {cnn['sex_probe']['base_rate']:.3f}. "
      f"r(CNN prediction, male) = {cnn['cnn_pred_vs_sex_r']:+.3f} against r(Hb, male) = "
      f"{cnn['hb_vs_sex_r']:+.3f}.\n\n")
    if "permutation" in cnn:
        pm = cnn["permutation"]
        A(f"Permutation test (run because the CNN beat "
          f"{'the demographic baseline' if cnn['beats_demographics'] else 'the population mean'}): "
          f"real {pm['real_mae_seed0']:.4f}, null {pm['null_mean']:.4f} +/- {pm['null_sd']:.4f}, "
          f"empirical p = {pm['p_empirical']:.4f} (floor {pm['p_floor']:.4f}), z = {pm['z']:+.2f}, n = {pm['n']}.\n\n")
    A("### Cross-site - the only cross-site axis the imaging data supports\n\n")
    A(row(["direction", "n train/test", "train-site mean", "sex", "demographics", "colour", "**CNN**", "CNN bias", "CNN gap", "band"]))
    A(row(["---"] * 10))
    for k, e in cnn["cross_site"].items():
        A(row([k.replace("_", " "), f"{e['n_train']}/{e['n_test']}",
               f"{e['population_mean_of_train_site']['mae_g_dl']:.3f}", f"{e['sex_only']['mae_g_dl']:.3f}",
               f"{e['demographics_age_sex']['mae_g_dl']:.3f}", f"{e['colour_features_lab']['mae_g_dl']:.3f}",
               f"**{e['cnn']['mae_g_dl']:.3f}** (r={e['cnn']['pearson_r']:+.2f})",
               f"{e['cnn']['bias_g_dl']:+.2f}", f"{e['cnn']['train_test_gap_mean']:+.2f}", e["cnn"]["band"]]))
    V = cnn["verdict"]
    A("\n### Verdict\n\n")
    beats_sex = V["cnn_beats_sex_alone"]
    A(f"* Pooled band: **{V['cnn_pooled_band']}**. Beats population mean: "
      f"{V['cnn_beats_population_mean']}. Beats sex alone: **{beats_sex}**. Beats "
      f"demographics: **{V['cnn_beats_demographics']}**.\n")
    A(f"* Cross-site bands: {V['cross_site_bands']}; beats the train-site mean: "
      f"{V['cross_site_cnn_beats_train_site_mean']}.\n")
    if not V["cnn_beats_demographics"]:
        A("* **The expected outcome: failure.** A conventional CNN on the only cross-site "
          "haemoglobin photographs in the project does not beat a single binary "
          "demographic variable, on the same folds, under the same bands, with the same "
          "scrutiny the PPG deep models received. The imaging refutation now has the "
          "standard-approach comparison section 3 required, and the comparison agrees "
          "with it. The imaging verdict is not revisited.\n")
    else:
        A("* **UNEXPECTED: the CNN beats the demographic baseline.** This is reported "
          "prominently and the imaging verdict must be revisited before the write-up.\n")
    A("\n")

    # ------------------------------------------------------------------ Task 3
    A("## 3. TASK 3 - the deep model's Phase 5 checks, end to end\n\n")
    if regen:
        A(f"`scripts/phase6_5_deep_predictions.py` regenerated the ten per-seed prediction "
          f"vectors and the six candidates with the Phase 5 driver in {regen['elapsed_s']/60:.1f} min. "
          f"Seed-averaged MAE {regen['real_mae_seed_averaged']:.4f} against harden.json's "
          f"{regen['real_mae_recorded']:.4f}; max |per-seed MAE - recorded| = "
          f"{regen['max_abs_seed_diff']:.4f} (cuDNN autotune; the measured seed SD is 0.0069).\n\n")
    deep = [c for c in hv["cases"] if c["case"].startswith("phase5_deep_")]
    if deep:
        A(row(["check", "expected", "harness verdict", "headline"]))
        A(row(["---"] * 4))
        for c in deep:
            A(row([c["check"], c["expected"], c["verdict"], c["headline"]]))
        s = hv["summary"]
        A(f"\nKnown-truth cases now **{s['reproduced']}/{s['known_truth_cases']}**; faults caught "
          f"{s['faults_caught']}/{s['fault_cases']}; false positives "
          f"{s['false_positive']['false_fail_total']} of {s['false_positive']['check_runs']} "
          f"check-runs ({s['false_positive']['false_positive_rate']:.2%}). "
          f"`deep_model_validated_end_to_end`: {s.get('deep_model_validated_end_to_end')}.\n\n")
        A("**The already-logged caveat stands.** The harness permutes labels against fixed "
          "predictions; Phase 5 refit the model inside every permutation. The nulls differ, "
          "so the harness's p is NOT a reproduction of 0.0041 and is not presented as one. "
          "The verdict is what is compared, and it agrees.\n\n")
    else:
        A("Not run (predictions file absent).\n\n")

    # ------------------------------------------------------------------ Task 4
    A("## 4. TASK 4 - the two over-claiming ticks\n\n")
    if ill:
        A("**Phase 2 \"apply the estimator to the conjunctiva datasets\": the estimate was "
          "PRODUCED.** `scripts/phase6_5_eyes_defy_illuminant.py` runs the Phase 2 pipeline "
          "(U-Net -> sclera -> vessel exclusion -> robust RGB -> sclera-referenced illuminant, "
          f"neutral prior) on all {ill['n']} Eyes-Defy images ({ill['n_with_sclera_estimate']} "
          "with enough sclera) and stores the per-image estimate.\n\n")
        A(row(["estimator", "spread about site mean, all", "India", "Italy", "between-site angle"]))
        A(row(["---"] * 5))
        for name, e in ill["methods"].items():
            bs = e["by_site"]
            A(row([name, f"{e['all'].get('mean_deg', float('nan')):.2f} deg",
                   f"{bs.get('eyes_defy:India', {}).get('mean_deg', float('nan')):.2f}",
                   f"{bs.get('eyes_defy:Italy', {}).get('mean_deg', float('nan')):.2f}",
                   f"{e.get('between_site_angle_deg', float('nan')):.2f} deg"]))
        A(f"\nSclera vs grey-world (25% crop) per image: {ill['sclera_vs_gw25_angle_deg']['mean']:.2f} deg. "
          f"Within-subject stability: {ill['within_subject_stability']}. Context: {ill['capture_context']}.\n\n")
    else:
        A("Phase 2 tick: the estimate was not produced; the tick is restated in CLAUDE.md.\n\n")
    A("**Phase 6 Task 2 \"export\": PDF export WORKS.** `reportlab` 5.0.1 installed and "
      "declared in `pyproject.toml`; `/api/runs/{id}/report.pdf` exercised end to end "
      "through the API (HTTP 200, `application/pdf`, `%PDF-1.4`). The stale \"no network\" "
      "comment in `main.py` is corrected.\n\n")

    # ------------------------------------------------------------------ Task 5
    A("## 5. TASK 5 - hygiene\n\n")
    A("* **Licences: 8 of 8 resolved** (`reports/dataset_manifest.md`, "
      "`reports/phase1_dataset_licences.md` verification section). CC BY 4.0: both Ghana "
      "Mendeley sets, CP-AnemiC (with the authors' \"academic purpose only\" statement), "
      "Hb-PPG (figshare API). Custom non-commercial no-redistribution agreements: SBVPI and "
      "MOBIUS (MOBIUS alone permits scaled-down/watermarked figures). No licence stated "
      "anywhere: NUS-8 (landing page has none) and Eyes-Defy-Anemia (IEEE DataPort record "
      "has no licence field; bundled docx: free of charge, cite three papers). Nothing "
      "permits committing images or derived measurements; the rule stands.\n")
    A("* **Constants banner: RETAINED, narrowed, one value lifted.** Efron 2009 and Zhivov "
      "2006 were fetched: neither abstract carries a numeric thickness and both full texts "
      "are subscription-only, so the stromal (200 um) and tarsal (800 um) thicknesses and all "
      "blood volume fractions remain hand-transcribed and flagged. The 32 um epithelium is "
      "now corroborated independently (Li et al. 2015, OCT, 34.0 +/- 5.8 um, n = 62) and its "
      "flag is lifted. Zhivov 2006 is a review in *The Ocular Surface* 4(2):81-93, not "
      "*Cornea* as previously cited; corrected. Phase 3 Task 4 showed the model tolerates "
      "0.8-2.0x thickness and +/-30% BVF under 1 g/dL, so no plausible correction moves a verdict.\n")
    A("* **Database:** the two `t` rows and the `e2e` row deleted; two near-duplicate real "
      "pre-registrations deleted (the last one, the one a run actually cites, kept); the "
      "two smoke-test runs that pointed at deleted rows now carry `prereg_id = NULL` rather "
      "than a substituted record. `PreRegIn.title` now requires >= 8 characters after "
      "stripping; test added; the front end no longer submits a short title.\n")
    A("* **Stray log entries:** the three RESULTS LOG entries that sat after section 9 are "
      "moved into section 8.\n\n")

    # ------------------------------------------------------------------ Task 6
    A("## 6. TASK 6 - commit\n\nSee the git log; the commit message carries the summary. "
      "`tests/test_phase5.py::test_no_dataset_files_are_tracked_by_git` guards the tree.\n\n")

    A("## 7. What remains\n\n**The write-up.** Every item from the 2026-09-12 audit is "
      "closed; the two open plan boxes are ticked with their artefacts; the imaging arm now "
      "has its conventional comparison arm and it agrees with the refutation. The one "
      "number a reader should carry from this phase: the central mechanism ratio is "
      f"**{NS['grey_world_25pct_fov_3.935']:.1f}x, not 5.6x**, and the paper must use the "
      "measured figure.\n")
    (paths.REPORTS / "phase6_5_closure.md").write_text("".join(L), encoding="utf-8")
    print(f"wrote {paths.REPORTS / 'phase6_5_closure.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
