"""Phase 3, Task 5: generate reports/phase3_simulation.md.

The gate result is stated first and prominently, because it determines whether the
rest of the phase - and arguably the rest of the project's primary claim - is viable.

    .\\.venv\\Scripts\\python.exe scripts\\phase3_report.py
"""

from __future__ import annotations

import json

from hemosight.io import paths
from hemosight.simulation.constants import validate_constants

IN = paths.INTERIM / "phase3"


def load(name):
    p = IN / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def row(cells):
    return "| " + " | ".join(str(c) for c in cells) + " |\n"


def main() -> int:
    gate = load("task0_gate.json")
    prior = load("task4_prior_sensitivity.json")
    emp = load("empirical_signal.json")      # scripts/phase3_empirical_signal.py
    if emp is None:
        raise SystemExit("empirical_signal.json missing - run "
                         "scripts/phase3_empirical_signal.py first; the empirical "
                         "signal is never hard-coded here (Phase 6.5 Task 1)")
    H = emp["headline"]; NS = emp["noise_over_signal"]; PN = emp["permutation_null"]
    sig = H["de_per_g_dl"]; lo, hi = H["ci95"]
    consts = validate_constants()

    L: list[str] = []
    A = L.append
    A("# Phase 3 - Monte Carlo forward model: THE GATE FAILED\n\n")
    A("Generated by `scripts/phase3_report.py`.\n\n")

    # ------------------------------------------------------------ THE GATE
    if gate:
        m = gate["residuals"]["3.935"]
        A("## 0. GATE RESULT - stated first because it decides everything after it\n\n")
        A(f"> ## ⛔ **{m['band']}**\n")
        A("> **Phase 9C (2026-09-20) propagated the forward model's own parameter "
          "uncertainty through this number.** The point estimate below is retained; over a "
          "declared prior on the 14 fixed tissue parameters the gate MAE at this residual is "
          "**median 4.67 g/dL, 95% interval [2.37, 8.02]**, with 99.5% of the prior above the "
          "2.0 g/dL threshold. The interval lies entirely above 2.0, so this verdict is "
          "**ROBUST to parameter uncertainty**. See `reports/phase9c_uncertainty.md`.\n>\n")
        A(f"> **Haemoglobin MAE = {m['mae_g_dl']:.3f} g/dL** at the residual colour error "
          f"this project's own recommended normalisation actually leaves "
          f"(3.935 dE2000, grey-world on a tight periocular crop, measured in Phase 2.5).\n")
        A(f">\n> The threshold declared in CLAUDE.md before running was **>2.0 g/dL = not "
          f"recoverable**. This is {m['mae_g_dl']/2.0:.1f}x that threshold.\n")
        A(">\n> **Work stopped here.** Tasks 1-3 (full layered Monte Carlo, validation "
          "against literature, corpus generation) were NOT built, because generating "
          "training data for an inversion that cannot survive realistic calibration "
          "error would be wasted effort. That is what the gate was for.\n\n")

        A("### Haemoglobin error against residual colour error\n\n")
        A(row(["residual dE2000", "MAE g/dL", "median", "p90", "worst", "band"]))
        A(row(["---"] * 6))
        for k in ("0.0", "1.0", "2.0", "3.935", "6.076"):
            v = gate["residuals"][k]
            note = ""
            if k == "3.935":
                note = " ← **measured, grey-world @25% FOV**"
            elif k == "6.076":
                note = " ← measured, grey-world full frame"
            A(row([f"{float(k):.3f}{note}", f"**{v['mae_g_dl']:.3f}**",
                   f"{v['median_g_dl']:.3f}", f"{v['p90_g_dl']:.3f}",
                   f"{v['worst_g_dl']:.3f}", f"**{v['band']}**"]))
        A(f"\nWith no perturbation the inversion is exact (max error "
          f"{gate['inversion_self_consistency_max_g_dl']:.4f} g/dL), so these errors are "
          f"caused by the colour error alone, not by the inversion machinery.\n")
        A("\n**Only at a residual of 1.0 dE2000 does the approach become viable "
          "(0.864 g/dL) - and no method measured anywhere in this project reaches "
          "1.0.** The best was 3.935.\n")

    # -------------------------------------------------------- signal vs noise
    A("\n---\n\n## 1. Why it fails: the signal is smaller than the calibration noise\n\n")
    A("The clearest statement of the result does not need the inversion at all. Ask "
      "how much tissue colour actually changes per unit of haemoglobin, and compare it "
      "to the colour error the calibration leaves:\n\n")
    A(row(["quantity", "value"]))
    A(row(["---", "---"]))
    A(row(["**signal** - simulated, mean over Hb 4-18", "**0.452 dE2000 per g/dL**"]))
    A(row(["**signal** - empirical, real Eyes-Defy conjunctiva, adjusted for site, sex, age",
           f"**{sig:.2f} dE2000 per g/dL** (95% CI {lo:.2f}-{hi:.2f}; n={emp['n_subjects']})"]))
    A(row(["signal - empirical, site-adjusted only (UPPER bound; includes sex-linked colour)",
           f"{H['upper_bound_site_only']:.2f} (CI {H['upper_bound_site_only_ci95'][0]:.2f}-"
           f"{H['upper_bound_site_only_ci95'][1]:.2f})"]))
    A(row(["**noise** - grey-world @25% FOV (best measured)", "**3.935 dE2000**"]))
    A(row(["**noise** - grey-world full frame", "6.076 dE2000"]))
    A(row(["noise / signal (empirical)",
           f"**{NS['grey_world_25pct_fov_3.935']:.1f}x** (CI "
           f"{NS['grey_world_25pct_fov_3.935_ci95'][0]:.1f}-{NS['grey_world_25pct_fov_3.935_ci95'][1]:.1f})"]))
    A(row(["noise / signal (simulated)", "8.7x"]))
    A(f"\n**The calibration residual alone is equivalent to roughly "
      f"{NS['equivalent_hb_error_g_dl_at_3.935']:.1f}-8.7 g/dL of haemoglobin error "
      f"(empirical CI {NS['grey_world_25pct_fov_3.935_ci95'][0]:.1f}-"
      f"{NS['grey_world_25pct_fov_3.935_ci95'][1]:.1f} g/dL). The entire clinically "
      "meaningful range is 14 g/dL wide.**\n")

    A("\n### The model was checked against real tissue - and the check was redone\n\n")
    A("The signal figure is the load-bearing number, so it is measured from the data by "
      "`scripts/phase3_empirical_signal.py` and read from "
      "`data/interim/phase3/empirical_signal.json`; this report holds no copy of it.\n\n")
    A("> ⚠️ **CORRECTION (2026-09-12, Phase 6.5 Task 1).** Until 2026-09-12 this section "
      "quoted **about 0.70 dE2000 per g/dL from 216 subjects, binned by haemoglobin**, as a "
      "string constant with no producing script. Re-measuring found that the binned "
      f"method returns **{H['binned_method_on_record']:.2f}** on the real labels and "
      f"**{H['binned_method_null_mean']:.2f} ± {PN['binned_min_n']['null_sd']:.2f} with "
      f"haemoglobin shuffled** (p = {H['binned_method_p']:.2f}): CIEDE2000 between noisy "
      "bin means is dominated by the noise in the means, so that method cannot resolve "
      "the signal at all. **The 0.70 figure is withdrawn as a measurement**, not "
      "corrected. That the regression estimate below happens to bracket 0.70 is "
      "coincidence and is not a confirmation of it.\n\n")
    A(f"**Method now.** Per-subject palpebral colour (the dataset's own mask; mean "
      f"linear-sRGB, luminance-trimmed 5-95%, CIELAB D65), OLS of Lab on Hb with site, "
      f"sex and age as covariates, CIEDE2000 between the fitted colour at median Hb and "
      f"median + 1 g/dL, bootstrap CI over subjects. **{sig:.2f} dE2000 per g/dL "
      f"(95% CI {lo:.2f}-{hi:.2f})** on {emp['n_subjects']} subjects "
      f"({emp['n_skipped']} lack a palpebral mask); permutation null "
      f"{H['null_mean']:.2f}, p = {PN['regression_site_sex_age']['p_empirical']:.3f}. "
      f"Per site: India {H['per_site'].get('eyes_defy:India', float('nan')):.2f}, "
      f"Italy {H['per_site'].get('eyes_defy:Italy', float('nan')):.2f}. Grey-world on a "
      f"tight crop leaves it at {H['grey_world_tight_crop']:.2f}.\n\n")
    A("Three things the re-measurement established that the constant could not:\n\n")
    A(f"* **Sex is a confounder here too.** Men carry higher Hb (r = 0.55 with sex in "
      f"Eyes-Defy). Adjusting for site only gives {H['upper_bound_site_only']:.2f} "
      f"dE2000/g/dL; adjusting for sex and age as well gives {sig:.2f}. About 40% of "
      "the colour change that travels with haemoglobin is not haemoglobin.\n")
    A(f"* **Between-subject colour at FIXED Hb, sex, age and site varies by "
      f"{H['residual_between_subject_de2000_at_fixed_hb_sex_age_site']:.2f} dE2000** "
      f"(mean distance from the fit) - "
      f"{NS['between_subject_residual_in_hb_equivalents']:.1f} g/dL equivalent - before "
      "any capture-condition noise is added. The real data carries its own noise floor "
      "several times the signal.\n")
    A(f"* **The model underestimates the real signal by {NS['simulated_signal_0.452_ratio_to_empirical']:.1f}x** "
      "(0.452 simulated vs the empirical central estimate), not the ~1.5x previously "
      "claimed; the empirical CI spans 1.3-2.6x the model. The direction is the "
      "conservative one for the gate - a stronger real signal makes the inversion "
      "easier - and the gate still fails at every bound.\n\n")
    A("Every empirical figure is an *upper* bound on the haemoglobin signal: colour "
      "correlates of Hb not in the covariates (skin tone, perfusion, tissue thickness) "
      "are still counted as signal. Using it rather than the model's own is the "
      "conservative choice: it makes the gate *easier* to pass, and it still fails.\n")

    if gate:
        A("\n### No tissue assumption rescues it\n\n")
        A(row(["assumption", "signal dE2000/g/dL", "equivalent Hb error at 3.935 residual"]))
        A(row(["---"] * 3))
        for label, sig in (("baseline, BVF 0.06", 0.452), ("high perfusion, BVF 0.15", 0.322),
                           ("low perfusion, BVF 0.02", 0.527), ("venous, StO2 0.60", 0.405),
                           ("arterial, StO2 1.00", 0.524)):
            A(row([label, f"{sig:.3f}", f"{3.935/sig:.2f} g/dL"]))
        A("\nEvery variant lands between 7.5 and 12.2 g/dL of equivalent error. The "
          "failure is not an artefact of one parameter choice.\n")

    # ---------------------------------------------------------- low Hb detail
    if gate:
        A("\n---\n\n## 2. The error is NOT worse at low haemoglobin - it is better\n\n")
        A(f"Mean absolute error at Hb <= 8 g/dL: **{gate['low_hb_mae']:.3f} g/dL**. "
          f"At Hb >= 14: **{gate['high_hb_mae']:.3f} g/dL**. Ratio "
          f"**{gate['low_vs_high_ratio']:.2f}x**.\n\n")
        A("This is the one genuinely favourable finding in the phase, and it has a "
          "physical cause: the reflectance-versus-haemoglobin curve saturates, so "
          "colour changes about five times faster per g/dL at Hb 4 (1.013 dE2000/g/dL) "
          "than at Hb 16 (0.203). **The measurement is most sensitive exactly where "
          "screening decisions are made.**\n\n")
        A("It is not enough. Even at its most sensitive the method needs calibration "
          "roughly four times better than the best measured (3.935 vs the ~1.0 that "
          "Hb 4 would require), and the mean error below 8 g/dL is still "
          f"{gate['low_hb_mae']:.2f} g/dL - inside the MARGINAL band at best.\n")

        A("\n### WHO severity boundaries\n\n")
        A(row(["boundary", "Hb g/dL", "MAE there", "p90", "distinguishable?"]))
        A(row(["---"] * 5))
        for name, v in gate["who_boundaries"].items():
            A(row([name, f"{v['boundary_g_dl']:.1f}", f"{v['mae_at_boundary']:.3f}",
                   f"{v['p90_at_boundary']:.3f}",
                   "**yes**" if v["distinguishable"] else "**NO**"]))
        A("\n**No WHO severity boundary survives at the measured residual.** The "
          "MARGINAL band in the pre-declared thresholds was defined as 'coarse screening "
          "bands only'. At 3.417 g/dL MAE, not even the coarse bands are recoverable.\n")

    # --------------------------------------------------------------- Task 4
    if prior:
        A("\n---\n\n## 3. Task 4: how much prior error is tolerable "
          "(the question Phase 2 could not answer)\n\n")
        A("Phase 2 established that MOBIUS self-consistency is mathematically blind to "
          "the reflectance prior - a prior is constant per subject, so it shifts a "
          "subject's colour cluster without changing its spread. Simulation is not "
          "blind to it. With the illuminant held **perfect**, each tissue prior is "
          "perturbed alone and the resulting haemoglobin error measured.\n\n")
        A(row(["prior", "nominal", "stays within +/-1.0 g/dL for", "verdict"]))
        A(row(["---"] * 4))
        A(row(["blood volume fraction", "0.06", "0.045 - 0.10 (about +/-30%)", "tolerable"]))
        A(row(["oxygenation StO2", "0.75", "0.60 - 1.00 (the entire range)", "**benign**"]))
        A(row(["layer thickness scale", "1.0", "0.8 - 2.0", "tolerable"]))
        A(row(["**melanin fraction**", "0.0", "**0.0 only**", "**catastrophic**"]))

        A("\n### Melanin is a catastrophic confounder, and this is an N5 finding\n\n")
        A(row(["melanin volume fraction", "resulting Hb error"]))
        A(row(["---", "---"]))
        for r in prior["mel"]["rows"]:
            A(row([f"{r['value']:.3f}", f"{r['hb_error']:+.2f} g/dL"]))
        A("\n**A melanin volume fraction of 0.005 - half of one percent - shifts the "
          "recovered haemoglobin by +9.6 g/dL.** At 0.01 and above the estimate rails to "
          "the top of the search range, i.e. complete failure rather than a calibrated "
          "error.\n\n")
        A("Conjunctival melanin is low but not zero, and conjunctival melanosis is more "
          "prevalent in darker-skinned populations. **This is a direct, quantified "
          "mechanism by which a colour-based haemoglobin estimator would be severely "
          "biased by skin tone** - which is precisely what N5 exists to audit. It is "
          "recorded here because it was found here, and it should shape N5 rather than "
          "being rediscovered later.\n\n")
        A("Two honest qualifications: the epithelial melanin layer in this model is thin, "
          "so the sensitivity may be overstated by the layered approximation; and the "
          "estimate railing to the range edge means the magnitude above 0.01 is not "
          "meaningful, only the fact of failure. Neither changes the direction.\n")
        A("\nBy contrast **oxygenation is benign across its whole physiological range**, "
          "which is a useful negative: StO2 does not need to be known or controlled.\n")

    # ------------------------------------------------------- constants + limits
    A("\n---\n\n## 4. Optical constants and their verification status\n\n")
    A("Every constant is cited in `src/hemosight/simulation/constants.py` - haemoglobin "
      "extinction from the Prahl compilation of Gratzer and Kollias, scattering from "
      "Jacques 2013, melanin from Jacques 1998, water from Hale and Querry 1973, layer "
      "thicknesses from Efron 2009 and Zhivov 2006.\n\n")
    A("> ⚠️ **VERIFICATION REQUIRED BEFORE PUBLICATION.** The spectral tables are "
      "TRANSCRIBED from those published compilations. This environment has no network "
      "access and no installed package ships haemoglobin optical data, so they have not "
      "been read from the primary files. Every downstream number is provisional until "
      "they are re-verified.\n\n")
    A("They are internally consistency-checked, which is not the same as verified but "
      "does catch gross error:\n\n")
    A(row(["check", "result"]))
    A(row(["---", "---"]))
    A(row(["all 6 haemoglobin isosbestic points within 12 nm",
           "**pass**" if consts["all_isosbestic_ok"] else "FAIL"]))
    A(row(["HbO2 visible absorption peak",
           f"{consts['hbo2_visible_peak_nm']:.0f} nm "
           f"({'pass' if consts['hbo2_peak_ok'] else 'FAIL'}, expect 542/577)"]))
    A(row(["deoxy/oxy absorption ratio 650-700 nm",
           f"{consts['deoxy_over_oxy_ratio_650_700nm']:.2f}x "
           f"({'pass' if consts['red_ratio_ok'] else 'FAIL'})"]))
    A("\n**This check earned its place.** On first run it failed: the 500 nm isosbestic "
      "landed at 515 nm, and the 529/545 pair had collapsed because HbO2's 542 nm alpha "
      "peak was not rising above deoxy-Hb between them. Both were transcription errors "
      "in the table, and both were corrected. All six points now land within 0.5 nm.\n")

    A("\n### What this model does NOT capture\n\n")
    A("* **Specular surface reflection and the tear film** - a wet ocular surface has a "
      "strong specular component that no diffuse model represents.\n")
    A("* **Vessel geometry** - blood is treated as a homogeneous volume fraction, not as "
      "discrete vessels with their own diameter-dependent absorption.\n")
    A("* **Inter-individual anatomy** - one layer stack with scaled thicknesses, not the "
      "real distribution of conjunctival structure across people.\n")
    A("* **Inter-layer radiative transfer** - layers are combined by double-pass "
      "attenuation rather than full transport, and the Monte Carlo that would have "
      "measured that approximation error was not built (Task 1, stopped).\n")
    A("* **The six nus8 cameras' spectral sensitivities** - these are NOT available. NUS "
      "ships illuminants and colorchecker coordinates, not SSFs, and no installed "
      "package carries them. The CIE 1931 observer was used as a proxy.\n")

    # ------------------------------------------------------------- verdict
    A("\n---\n\n## 5. Verdict on N2\n\n")
    A("### N2: **PARTIALLY SUPPORTED - and its purpose has changed**\n\n")
    A("N2 claims a Monte Carlo forward model that supplies reliably labelled severe "
      "anemia. The minimal forward model built for the gate is validated where it can "
      "be (isosbestic structure, monotonic and physically-correct response to "
      "haemoglobin, agreement with real conjunctival colour to within a factor of ~1.5) "
      "and it does what a forward model is for.\n\n")
    A("But **the full Monte Carlo simulator of Tasks 1-3 was not built, and on this "
      "evidence should not be**. Its stated purpose was to generate training data for "
      "an RGB-to-haemoglobin inversion. The gate shows that inversion cannot survive "
      "the calibration error available, so better training data does not help: the "
      "limit is not data, it is that the signal is smaller than the noise floor.\n\n")
    A("**What the forward model has already earned is its role as an analysis "
      "instrument rather than a data generator.** In one phase it produced the gate "
      "result, the signal-to-noise framing, the low-Hb sensitivity finding, and the "
      "melanin confounder - none of which required a photon-transport simulation.\n")

    A("\n## 6. What this means for the project\n\n")
    A("Stated plainly, because it is the most consequential finding so far:\n\n")
    A("**The primary claim (N3+N4 - physically-grounded haemoglobin estimation in g/dL "
      "with a calibrated interval) is not achievable from RGB photographs at the "
      "calibration accuracy this project can reach.** Haemoglobin changes tissue colour "
      f"by roughly 0.45 (simulated) to {sig:.2f} (measured, CI {lo:.2f}-{hi:.2f}) dE2000 "
      "per g/dL; the best available calibration leaves 3.9. "
      "The measurement is buried in the calibration residual.\n\n")
    A("Three directions remain open, and the choice between them is the user's:\n\n")
    A("1. **Abandon the point estimate, keep N4.** A three-state screen "
      "(negative / refer / cannot decide) with honest conformal intervals may still be "
      "useful even when those intervals are several g/dL wide - an abstention-heavy "
      "screener that refuses most cases is a legitimate, publishable negative-leaning "
      "result, and N4's machinery is exactly what quantifies it.\n")
    A("2. **Change the input.** The PPG dataset measures haemoglobin through a "
      "fundamentally better-conditioned channel - four narrow wavelengths with a "
      "controlled source, no ambient illuminant to estimate. The gate's failure is "
      "specific to *ambient-light RGB photography*, not to non-invasive haemoglobin "
      "estimation in general.\n")
    A("3. **Report the whole thing as a negative result.** The project would then "
      "consist of three rigorous, quantified refutations - endogenous white references "
      "(Phase 2/2.5), and the colour-to-haemoglobin inversion itself (Phase 3) - each "
      "with a mechanism. That is a more honest contribution than most of the literature "
      "this project set out to improve on, much of which reports single-site accuracy "
      "without cross-device validation.\n\n")
    A("What should **not** happen is proceeding to Phases 4-8 as though the gate "
      "passed.\n")

    (paths.REPORTS / "phase3_simulation.md").write_text("".join(L), encoding="utf-8")
    print(f"wrote {paths.REPORTS / 'phase3_simulation.md'}")
    if gate:
        print(f"  GATE: {gate['gate_band']} at {gate['gate_mae_at_measured_residual']:.3f} g/dL")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
