"""Phase 4.5, TASK 3: generate reports/phase4_5_deep.md.

    .\\.venv\\Scripts\\python.exe scripts\\phase4_5_report.py
"""

from __future__ import annotations

import json

from hemosight.io import paths

IN = paths.INTERIM / "phase4_5"


def load(n):
    p = IN / n
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def row(c):
    return "| " + " | ".join(str(x) for x in c) + " |\n"


def main() -> int:
    dp, ce = load("deep_results.json"), load("ceiling.json")
    dperm = load("deep_permutation.json")
    L: list[str] = []
    A = L.append

    A("# Phase 4.5 - Deep models on raw PPG: the verdict does not change\n\n")
    A("Generated by `scripts/phase4_5_report.py`. This phase existed to close the one "
      "representation Phase 4 did not test, so that a negative-results write-up can "
      "answer \"did you try deep learning?\" with evidence rather than omission. **The "
      "expected outcome was failure and that is what occurred** - but the ceiling "
      "analysis turns it into a stronger claim than \"our model failed\".\n\n")

    # ------------------------------------------------------------- headline
    if dp:
        A("## 0. THE ANSWER\n\n")
        A(row(["model", "MAE g/dL", "R²", "verdict"]))
        A(row(["---"] * 4))
        A(row(["sex alone (Phase 4)", "**0.831**", "0.415", "still the best in the study"]))
        A(row(["demographics (Phase 4)", "0.831", "0.411", "same as sex alone"]))
        A(row(["population mean", f"{dp['baselines']['population_mean']:.3f}", "0.000",
               "the null model"]))
        best = dp["best"]
        for cond, d in dp["conditions"].items():
            for arch, v in d.items():
                mark = " ← best deep" if (cond == best["condition"]
                                          and arch == best["arch"]) else ""
                A(row([f"deep: {arch} ({cond}){mark}", f"{v['mae_g_dl']:.3f}",
                       f"{v['r2']:+.3f}", v["band"]]))
        A(row(["hand-engineered features (Phase 4)", "1.190", "-0.025", "NOT VIABLE"]))
        A(f"\n**No deep model beats the demographic baseline; none beats sex alone.** "
          f"The best is {best['arch']} on {best['condition']} at "
          f"**{best['mae_g_dl']:.3f} g/dL**, against 0.831 for a single binary "
          f"variable. Every deep model has an R² at or below zero on at least one "
          f"condition - no better than predicting a constant.\n")

    # ------------------------------------------------------------- leakage
    if dp:
        A("\n---\n\n## 1. Leakage control and memorisation\n\n")
        A("With 252 subjects a network of this size can memorise. Two guards:\n\n")
        A("* **Subject-disjoint folds asserted in code.** Every fold raises if any "
          "subject id appears in both train and test. Windows from one recording never "
          "straddle a boundary.\n")
        A("* **Train-test gap reported**, so memorisation is visible rather than "
          "hidden.\n\n")
        A(row(["model", "train MAE", "test MAE", "gap", "interpretation"]))
        A(row(["---"] * 5))
        for cond, d in dp["conditions"].items():
            for arch, v in d.items():
                gap = v["train_test_gap"]
                interp = ("memorising" if gap > 0.35 else
                          "mild overfit" if gap > 0.15 else "not overfitting")
                A(row([f"{arch} ({cond})", f"{v['train_mae_g_dl']:.3f}",
                       f"{v['mae_g_dl']:.3f}", f"{gap:+.3f}", interp]))
        A("\nThe pattern is the signature of absent signal: the models fit the training "
          "subjects (train MAE well below test) and carry none of it across. They are "
          "memorising subject identity, which is the only thing the waveform reliably "
          "encodes here.\n")

        A("\n### The sex probe\n\n")
        A("Phase 4 Task 3 showed how easily an apparent haemoglobin model is really a "
          "sex classifier. A logistic probe was trained on each network's learned "
          "representation, subject-grouped so the probe cannot leak either:\n\n")
        A(row(["model", "sex probe accuracy", "base rate", "learned sex?"]))
        A(row(["---"] * 4))
        for cond, d in dp["conditions"].items():
            for arch, v in d.items():
                if "sex_probe_accuracy" in v:
                    acc, base = v["sex_probe_accuracy"], v["sex_base_rate"]
                    A(row([f"{arch} ({cond})", f"{acc*100:.1f}%", f"{base*100:.1f}%",
                           "**yes**" if acc > base + 0.05 else "no"]))
        A("\nNone of the representations encodes sex above its base rate. That is worth "
          "stating precisely: **the deep models did not fall into the Phase 4 trap, "
          "because they learned nothing at all** - not sex, not haemoglobin. The probe "
          "was run as a safeguard and came back clean for the least encouraging "
          "possible reason.\n")

    # ------------------------------------------------------------- ceiling
    if ce:
        A("\n---\n\n## 2. Ceiling analysis: is the signal there at all?\n\n")
        A("\"Our model failed\" and \"the signal is not present\" are different claims. "
          "Three model-independent measures decide which one is warranted.\n")

        mi = ce["mutual_information"]
        A("\n### 2.1 Mutual information\n\n")
        A(row(["quantity", "value"]))
        A(row(["---", "---"]))
        A(row(["max MI over all features", f"{mi['max']:.4f}"]))
        A(row(["mean MI", f"{mi['mean']:.4f}"]))
        A(row(["null (shuffled Hb) mean", f"{mi['null_mean']:.4f}"]))
        A(row(["null 95th percentile", f"{mi['null_p95']:.4f}"]))
        A(row(["**features above the null p95**",
               f"**{mi['n_above_null_p95']} of {ce['n_features']}**"]))
        A(f"\n**Not one feature carries more mutual information with haemoglobin than "
          f"shuffled labels produce.** The highest ({mi['top'][0]['feature']}, MI "
          f"{mi['top'][0]['mi']:.4f}) sits below the null 95th percentile.\n")

        co = ce["correlations"]
        A("\n### 2.2 Correlations with multiple-comparison correction\n\n")
        A(f"With {ce['n_features']} features, {co['expected_false_positives_at_05']:.1f} "
          f"are expected to reach p<0.05 by chance. **{co['n_raw_p_below_05']} did** - "
          f"almost exactly the chance rate. After Benjamini-Hochberg FDR control at "
          f"q=0.05, **{co['n_significant_pearson_fdr']} survive**.\n\n")
        A(row(["feature", "Pearson r", "raw p", "FDR-adjusted p", "significant?"]))
        A(row(["---"] * 5))
        for e in co["top"][:6]:
            A(row([e["feature"], f"{e['pearson_r']:+.3f}", f"{e['p']:.4f}",
                   f"{e['p_fdr']:.4f}", "yes" if e["significant_fdr"] else "**no**"]))

        pm = ce["permutation"]
        A("\n### 2.3 Permutation test - the decisive one\n\n")
        A(row(["quantity", "value"]))
        A(row(["---", "---"]))
        A(row(["real PPG model, 10-fold CV MAE", f"**{pm['real_mae']:.4f}** g/dL"]))
        A(row(["null (Hb shuffled across subjects), mean",
               f"{pm['null_mean']:.4f} g/dL"]))
        A(row(["null SD", f"{pm['null_sd']:.4f}"]))
        A(row(["**permutation p-value**", f"**{pm['p_value']:.4f}**"]))
        A(row(["z against the null", f"{pm['z_score']:+.2f}"]))
        A(row(["population-mean MAE", f"{pm['population_mean_mae']:.4f} g/dL"]))
        A(f"\n**The real model is worse than {pm['p_value']*100:.1f}% of models trained "
          f"on randomly shuffled haemoglobin labels.** It sits {pm['z_score']:+.2f} "
          f"standard deviations from the null mean, in the wrong direction - fitting "
          f"{ce['n_features']} features to noise costs variance that the shuffled "
          f"models, being equally uninformative but no worse, do not pay differently.\n")

        A(f"\n> ### The stronger claim is warranted\n>\n> {ce['conclusion']}\n")

    if dperm:
        A("\n---\n\n## 2.4 The deep model has its own permutation test - and it passes\n\n")
        A("The best deep model reached r = +0.248 and R^2 = +0.061. Weak, but not "
          "obviously nothing - and it was selected as best-of-six, which inflates "
          "any naive significance. So it was permutation-tested on its own terms: "
          "same architecture, same folds, haemoglobin shuffled across subjects.\n\n")
        A(row(["quantity", "value"]))
        A(row(["---", "---"]))
        A(row(["real speccnn (660 nm) MAE", f"**{dperm['real_mae']:.4f}** g/dL"]))
        A(row(["null mean +/- SD", f"{dperm['null_mean']:.4f} +/- "
                                   f"{dperm['null_sd']:.4f} (n={dperm['n_perms']})"]))
        A(row(["z against the null", f"**{dperm['z']:+.2f}**"]))
        A(row(["distinguishable from chance?", f"**{dperm['distinguishable']}**"]))
        A(f"\n**This one is real.** At z = {dperm['z']:+.2f} the spectrogram "
          "CNN extracts information from the raw waveform that shuffled labels do "
          "not produce. It is the single positive finding in the phase, and it "
          "must not be overstated:\n\n")
        A(row(["model", "MAE g/dL", "vs population mean"]))
        A(row(["---"] * 3))
        A(row(["sex alone", "0.831", "**-0.344**"]))
        A(row(["deep speccnn, 660 nm", f"{dperm['real_mae']:.3f}",
               f"-{1.175 - dperm['real_mae']:.3f}"]))
        A(row(["population mean", "1.175", "-"]))
        A(row(["hand-engineered features", "1.208", "+0.033 (worse)"]))
        A("\n**The effect is real and clinically useless.** It improves on "
          "predicting a constant by 0.054 g/dL; a single binary demographic "
          "variable beats it by six times that margin. An estimator with MAE "
          "1.12 g/dL separates no WHO severity band.\n\n")
        A("### The contrast that matters\n\n")
        A(row(["representation", "permutation p", "verdict"]))
        A(row(["---"] * 3))
        A(row(["hand-engineered AC/DC features", "0.978",
               "**indistinguishable from chance**"]))
        A(row(["raw waveform, spectrogram CNN", "< 0.05",
               "**distinguishable from chance**"]))
        A("\nThe raw waveform carries haemoglobin-correlated information that the "
          "AC/DC ratio features discard. That is exactly the question this phase "
          "was run to answer, and the answer is yes - the features were throwing "
          "something away. It is simply far too little to matter.\n\n")
        A("One honest caveat on attribution: the permutation shuffles Hb across "
          "subjects, breaking any subject-level association. A significant result "
          "means the waveform encodes something tracking haemoglobin **at the "
          "subject level** - which could be haemoglobin itself or a physiological "
          "correlate. The sex probe rules out sex specifically (43.6-52.3% against "
          "a 57.0% base rate), but not every possible confound.\n")

    # ------------------------------------------------------------- verdict
    A("\n---\n\n## 3. Verdict\n\n")
    A("### Deep models do NOT change the Phase 4 verdict. The PPG arm remains NOT "
      "VIABLE - but the reason is more precise than before.\n\n")
    A("Three architectures (1D dilated CNN, bidirectional GRU, spectrogram CNN), two "
      "wavelength conditions, subject-disjoint 10-fold CV, target standardised per fold "
      "so no model was handicapped by initialisation. **None beats a single binary "
      "demographic variable.**\n\n")
    A("The precise finding has two parts, and the second corrects what the "
      "feature-based analysis alone would have supported:\n\n")
    A("1. **The hand-engineered AC/DC features contain no signal.** Zero of 51 features "
      "exceed the null mutual information, zero survive FDR correction, and the feature "
      "model is *worse* than 97.8% of models trained on shuffled labels.\n")
    A("2. **The raw waveform does contain a real signal - and it is useless.** A "
      "spectrogram CNN is distinguishable from chance at z = -4.72, so the AC/DC "
      "features were discarding something. But it reaches MAE 1.12 g/dL against 0.83 "
      "for sex alone and 1.18 for a constant. Real, statistically significant, and far "
      "below any clinical threshold.\n\n")
    A("Saying only \"deep learning found nothing\" would have been wrong. The accurate "
      "statement is that deep learning found something the features missed, and it is "
      "still nowhere near enough.\n\n")
    A("This is the useful result the phase was run to obtain. The deep-learning question "
      "is now closed with evidence rather than left open by omission.\n")

    A("\n### What this does and does not establish\n\n")
    A("* **Establishes:** in this dataset - 252 adults, one device, Hb 8.5-17.3 g/dL - "
      "four-wavelength fingertip PPG carries no haemoglobin information recoverable by "
      "hand-engineered features or by three standard deep architectures, and the "
      "feature-based result is statistically indistinguishable from chance.\n")
    A("* **Does not establish:** that PPG-based haemoglobin estimation is impossible in "
      "general. A larger cohort, a wider haemoglobin range (this one contains **no "
      "severe anemia at all**), multiple devices, or a different sensor geometry could "
      "change the answer. What can be said is that it is not recoverable here, and that "
      "the published literature reporting success on datasets of this size warrants the "
      "permutation test applied above.\n")

    (paths.REPORTS / "phase4_5_deep.md").write_text("".join(L), encoding="utf-8")
    print(f"wrote {paths.REPORTS / 'phase4_5_deep.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
