"""Phase 9D, Task 4: generate reports/phase9d_power.md from data/interim/phase9d/power.json.

    .\\.venv\\Scripts\\python.exe scripts\\phase9d_report.py
"""

from __future__ import annotations

import json

from hemosight.io import paths

IN = paths.INTERIM / "phase9d" / "power.json"


def row(cells) -> str:
    return "| " + " | ".join(str(c) for c in cells) + " |\n"


def main() -> int:
    if not IN.exists():
        print(f"missing {IN}; run scripts/phase9d_power.py first")
        return 1
    d = json.loads(IN.read_text(encoding="utf-8"))
    A_ = d["arms"]
    reg = A_["imaging_regression"]
    scr_ = A_["imaging_screening"]
    cnn = scr_["image_cnn"]
    lab = scr_["colour_features_lab"]
    cs = A_["imaging_cross_site"]
    ppg = A_["ppg"]
    m = d["method"]

    L: list[str] = []
    A = L.append
    A("# Phase 9D - power analysis: what this study could have detected\n\n")
    A("Generated by `scripts/phase9d_report.py` from `data/interim/phase9d/power.json`. "
      "The method, the one deciding comparison per arm, the clinical yardsticks and the "
      "verdict rule were **pre-declared in CLAUDE.md on 2026-09-20 before any number here "
      "was computed**.\n\n")
    A("> ## THE ANSWER IN ONE PARAGRAPH\n>\n")
    A(f"> **Both regression comparisons are adequately powered; the imaging screening "
      f"comparisons are not, and the project's most load-bearing finding is its least "
      f"powered.** For haemoglobin error in g/dL this study could detect improvements of "
      f"**{reg['mde_80']:.2f} g/dL** (imaging) and **{ppg['mae_vs_sex_alone']['mde_80']:.2f} "
      f"g/dL** (PPG) at 80% power - far smaller than the **1.0 g/dL** that the narrowest WHO "
      "band would require, so *no effect large enough to matter clinically could have been "
      "missed*. For the screening comparisons the smallest detectable specificity gain is "
      f"**{cnn['specificity_at_matched_sensitivity']['mde_80']:.3f}** within site, against a "
      f"pre-declared clinically meaningful margin of **0.10** - marginally underpowered - and "
      f"**{cs['italy_to_india']['specificity_at_matched_sensitivity']['mde_80']:.3f}** in the "
      "italy->india cross-site direction, **three times the margin**. The cross-site collapse "
      "is the result that governs the imaging verdict, and it rests on the least powered "
      "comparison in the project. The PPG arm splits: its MAE comparison is the "
      "best-powered in the project, its specificity comparison is adequately powered, and "
      f"its AUROC comparison is not (MDE 80% = {ppg['auroc']['mde_80']:.2f} on "
      f"{ppg['n_anaemic']} anaemic subjects).\n\n")

    # ------------------------------------------------------------------ Task 3
    A("---\n\n## 1. What was computed, and what was deliberately not\n\n")
    A(f"**Computed: the minimum detectable effect (MDE).** {m['formula']}, two-sided, "
      f"alpha = {0.05}. The multiplier is {m['multiplier_80']:.3f} at 80% power and "
      f"{m['multiplier_90']:.3f} at 90%. The MDE answers *what effect size could this design "
      "have detected, given its sample size and the variance structure of its own "
      "measurements*.\n\n")
    A("**NOT computed: observed, retrospective or post-hoc power** - power recomputed at the "
      "effect size that was actually observed. This is a known statistical error, and it is "
      "worth saying why rather than just naming it. Observed power is a deterministic "
      "function of the observed p-value, so it contains no information the p-value does not "
      "already carry; and because it is low by construction whenever a result is null, "
      "reporting it would hand every negative finding in this project a built-in excuse. "
      "`hemosight.evaluation.power` contains no such function, by design. **A reader can "
      "therefore tell exactly which analysis was run: the design's detectable effect, not the "
      "study's luck.**\n\n")
    A("**Two caveats that travel with the MDE and are not corrected for.** "
      f"{m['caveats'][0]}; and {m['caveats'][1]}. The MDE does use this sample to estimate a "
      "nuisance *variance* - that is standard, and is not the same error as using the "
      "observed *effect*.\n\n")
    A("**A clarification that prevents a misreading.** An effect can be statistically "
      "significant and still smaller than the MDE at 80% power: significance needs about "
      "1.96 x SE, while 80% power needs 2.80 x SE. So Phase 9A's image-CNN specificity gain "
      f"(+{cnn['specificity_at_matched_sensitivity']['observed_difference_note']:.3f}, CI "
      "excluding zero) is real on its own terms and simultaneously below this arm's MDE(80%) "
      f"of {cnn['specificity_at_matched_sensitivity']['mde_80']:.3f}. The two statements are "
      "about different questions and neither corrects the other.\n\n")
    A("**Pairing.** Every comparison scores two models on the same subjects, so every "
      "difference here is paired. For the MAE comparisons the exact paired SE "
      "sd(d)/sqrt(n) is used; for sensitivity and specificity at a nested operating point no "
      "closed form applies, so the SE is the SD of the "
      f"{m['bootstrap']['n_boot']}-replicate subject-level paired bootstrap, the identical "
      f"scheme (seed {m['bootstrap']['seed']}) Phase 9A used to produce the intervals those "
      "verdicts rest on. Pairing matters materially: on the imaging MAE comparison the "
      f"per-subject errors of the two models correlate at r = "
      f"{reg['paired']['error_correlation']:.2f}, which makes the paired SE "
      f"{reg['paired']['pairing_variance_saving'] * 100:.0f}% smaller than an unpaired one "
      "and the MDE correspondingly tighter. An unpaired SE would have overstated every MDE "
      "in this report.\n\n")
    A("**The comparisons are the ones that decided the arms.** Model scores, folds and "
      "baselines are rebuilt by importing Phase 9A's own construction functions, and the "
      "script asserts it reproduces Phase 9A's recorded point differences before reporting "
      "anything: image-CNN MAE "
      f"{reg['paired']['mean_a']:.4f} and baseline {reg['paired']['mean_b']:.4f}; PPG deep "
      f"{ppg['mae_vs_sex_alone']['paired']['mean_a']:.4f} and sex alone "
      f"{ppg['mae_vs_sex_alone']['paired']['mean_b']:.4f}; every screening difference to "
      "within 5e-3.\n\n")

    # ------------------------------------------------------------------ Task 4 table
    A("---\n\n## 2. The summary table\n\n")
    A(row(["arm", "n", "deciding comparison", "SE", "MDE @80%", "MDE @90%",
           "clinical yardstick", "power to detect the yardstick",
           "what the MDE means clinically", "verdict"]))
    A(row(["---"] * 10))
    A(row(["Imaging regression", reg["paired"]["n"],
           "image-CNN MAE vs site + sex + age (1.273 g/dL)", f"{reg['se']:.4f}",
           f"**{reg['mde_80']:.3f} g/dL**", f"{reg['mde_90']:.3f} g/dL",
           "1.0 g/dL (narrowest WHO band)",
           f"**{reg['power_at_the_yardstick'] * 100:.0f}%**",
           f"{reg['mde_80']:.2f} g/dL moves **no** WHO boundary and no gate band",
           f"**{reg['verdict']}**"]))
    A(row(["Imaging screening (within site)", f"{scr_['image_cnn']['n']} ({scr_['image_cnn']['n_anaemic']} anaemic)",
           "specificity gain at matched sensitivity vs site + sex + age",
           f"{cnn['specificity_at_matched_sensitivity']['se']:.4f}",
           f"**{cnn['specificity_at_matched_sensitivity']['mde_80']:.3f}**",
           f"{cnn['specificity_at_matched_sensitivity']['mde_90']:.3f}",
           "0.10 (Phase 9A margin)",
           f"**{cnn['specificity_at_matched_sensitivity']['power_at_the_yardstick'] * 100:.0f}%**",
           f"{cnn['specificity_at_matched_sensitivity']['referrals_avoided_at_mde_80']:.0f} of "
           f"{cnn['n_non_anaemic']} needless referrals avoided",
           f"**{cnn['specificity_at_matched_sensitivity']['verdict']}**"]))
    sens = cnn["sensitivity_at_matched_specificity"]
    A(row(["Imaging screening (within site)", f"{scr_['image_cnn']['n']}",
           "sensitivity gain at matched specificity vs site + sex + age",
           f"{sens['se']:.4f}", f"**{sens['mde_80']:.3f}**", f"{sens['mde_90']:.3f}",
           "0.10 (Phase 9A margin)",
           f"**{sens['power_at_the_yardstick'] * 100:.0f}%**",
           f"{sens['additional_anaemic_detected_at_mde_80']:.0f} of {sens['n_anaemic']} "
           "anaemic subjects additionally detected",
           f"**{sens['verdict']}**"]))
    for k, lbl in (("italy_to_india", "Imaging **cross-site** italy->india"),
                   ("india_to_italy", "Imaging **cross-site** india->italy")):
        b = cs[k]["specificity_at_matched_sensitivity"]
        A(row([lbl, f"{cs[k]['n']} ({cs[k]['n_anaemic']} anaemic)",
               "specificity gain at matched sensitivity vs sex + age",
               f"{b['se']:.4f}", f"**{b['mde_80']:.3f}**", f"{b['mde_90']:.3f}",
               "0.10 (Phase 9A margin)",
               f"**{b['power_at_the_yardstick'] * 100:.0f}%**",
               f"{b['referrals_avoided_at_mde_80']:.0f} of {cs[k]['n_non_anaemic']} needless "
               "referrals avoided", f"**{b['verdict']}**"]))
    pm = ppg["mae_vs_sex_alone"]
    A(row(["PPG regression", ppg["n"], "deep-model MAE vs sex alone (0.831 g/dL)",
           f"{pm['se']:.4f}", f"**{pm['mde_80']:.3f} g/dL**", f"{pm['mde_90']:.3f} g/dL",
           "1.0 g/dL (narrowest WHO band)",
           f"**{pm['power_at_the_yardstick'] * 100:.0f}%**",
           f"{pm['mde_80']:.2f} g/dL moves **no** WHO boundary",
           f"**{pm['verdict']}**"]))
    ps = ppg["specificity_at_matched_sensitivity"]
    A(row(["PPG screening", f"{ppg['n']} ({ppg['n_anaemic']} anaemic)",
           "specificity gain at matched sensitivity vs demographics",
           f"{ps['se']:.4f}", f"**{ps['mde_80']:.3f}**", f"{ps['mde_90']:.3f}",
           "0.10 (Phase 9A margin)",
           f"**{ps['power_at_the_yardstick'] * 100:.0f}%**",
           f"{ps['referrals_avoided_at_mde_80']:.0f} of {ppg['n_non_anaemic']} needless "
           "referrals avoided", f"**{ps['verdict']}**"]))
    A("\nAUROC differences are reported in section 3 rather than here, because **AUROC has no "
      "pre-declared clinical yardstick in this project.** Borrowing the 0.10 sensitivity / "
      "specificity margin as an AUROC scale would be an invented threshold, so the AUROC MDEs "
      "are given as supporting information and no arm verdict rests on them.\n\n")

    # ------------------------------------------------------------------ per-arm detail
    A("---\n\n## 3. Per arm, in clinical units\n\n")

    A("### 3.1 Imaging regression - ADEQUATELY POWERED\n\n")
    A(f"n = {reg['paired']['n']} Hb-labelled Eyes-Defy subjects. The deciding comparison is "
      "the one Phase 6.5 and Phase 9A actually used: image-CNN MAE against the "
      "site-inclusive demographic baseline. Paired SE "
      f"{reg['se']:.4f} g/dL (bootstrap SE for reference "
      f"{reg['se_bootstrap_for_reference']:.4f}), giving **MDE(80%) = {reg['mde_80']:.3f} "
      f"g/dL** and MDE(90%) = {reg['mde_90']:.3f} g/dL.\n\n")
    A(f"**In clinical units.** {reg['mde_80']:.2f} g/dL is roughly a fifth of the narrowest "
      "WHO severity band (the 1.0 g/dL mild band for men, 10.0-10.9). An MAE improvement that "
      "small **cannot move any WHO boundary**, and it cannot move a gate band either "
      "(VIABLE < 1.0, MARGINAL 1.0-2.0). So the design was sensitive to improvements an order "
      "of magnitude smaller than the smallest one that could change a clinical decision. "
      "**The negative result is informative evidence of absence:** had the photograph carried "
      "a clinically useful amount of haemoglobin information beyond site, sex and age, this "
      "sample would have found it.\n\n")

    A("### 3.2 Imaging screening, within site - marginally UNDERPOWERED\n\n")
    A(f"n = {scr_['image_cnn']['n']}, {scr_['image_cnn']['n_anaemic']} anaemic "
      f"({scr_['image_cnn']['n_non_anaemic']} not), the Phase 9A cohort. Both halves of the "
      "pre-declared margin rule are reported.\n\n")
    A(row(["comparison", "SE", "MDE @80%", "MDE @90%", "vs the 0.10 margin", "verdict"]))
    A(row(["---"] * 6))
    b = cnn["specificity_at_matched_sensitivity"]
    A(row(["specificity gain at matched sensitivity (image-CNN)", f"{b['se']:.4f}",
           f"{b['mde_80']:.3f}", f"{b['mde_90']:.3f}",
           f"{b['mde_80'] / 0.10:.2f}x the margin", b["verdict"]]))
    b2 = lab["specificity_at_matched_sensitivity"]
    A(row(["specificity gain at matched sensitivity (mean-CIELAB)", f"{b2['se']:.4f}",
           f"{b2['mde_80']:.3f}", f"{b2['mde_90']:.3f}",
           f"{b2['mde_80'] / 0.10:.2f}x the margin", b2["verdict"]]))
    A(row(["sensitivity gain at matched specificity (image-CNN)", f"{sens['se']:.4f}",
           f"{sens['mde_80']:.3f}", f"{sens['mde_90']:.3f}",
           f"{sens['mde_80'] / 0.10:.2f}x the margin", sens["verdict"]]))
    A(f"\n**In clinical units.** At 80% power the smallest detectable specificity gain, "
      f"{b['mde_80']:.3f}, corresponds to sparing "
      f"{b['referrals_avoided_at_mde_80']:.0f} of {cnn['n_non_anaemic']} non-anaemic subjects "
      "a needless blood test; the smallest detectable sensitivity gain, "
      f"{sens['mde_80']:.3f}, to detecting "
      f"{sens['additional_anaemic_detected_at_mde_80']:.0f} more of "
      f"{sens['n_anaemic']} anaemic subjects - about 1 additional case per "
      f"{scr_['image_cnn']['n'] / sens['additional_anaemic_detected_at_mde_80']:.0f} people "
      "screened.\n\n")
    A(f"**Verdict, applied as declared: UNDERPOWERED - but by a small margin, and the "
      f"statement must be precise.** MDE(80%) is {b['mde_80']:.3f} against a yardstick of "
      f"0.100, i.e. {(b['mde_80'] / 0.10 - 1) * 100:.0f}% over. What the design could **not** "
      f"reliably detect is an effect sitting exactly at the 0.10 margin: an effect of precisely "
      f"that size would have been found "
      f"{cnn['specificity_at_matched_sensitivity']['power_at_the_yardstick'] * 100:.0f}% of "
      "the time, not 80%. What the design "
      "**could** detect it did: the mean-CIELAB model's observed specificity gain of "
      f"+{b2['observed_difference_note']:.3f} is well above its own MDE of {b2['mde_80']:.3f}, "
      "and Phase 9A recorded it with a CI excluding zero. **So this is not a case of a null "
      "result resting on thin power** - the arm found a real within-site effect. The honest "
      "limitation is narrower: a *borderline* effect, one just large enough to matter under "
      "the project's own margin, could have been missed.\n\n")

    A("### 3.3 Imaging cross-site - UNDERPOWERED, and this is the load-bearing finding\n\n")
    A("**Reported per direction and never pooled.** Each direction trains on one site and "
      "tests on the other, so each uses a fraction of the cohort - and the two fractions are "
      "very differently composed, which matters more than the raw n.\n\n")
    A(row(["direction", "n", "anaemic", "non-anaemic", "spec-gain SE", "MDE @80%",
           "MDE @90%", "vs 0.10", "AUROC MDE @80%", "MAE MDE @80%", "verdict"]))
    A(row(["---"] * 11))
    for k in ("italy_to_india", "india_to_italy"):
        c = cs[k]
        b = c["specificity_at_matched_sensitivity"]
        A(row([k.replace("_", " "), c["n"], c["n_anaemic"], c["n_non_anaemic"],
               f"{b['se']:.4f}", f"**{b['mde_80']:.3f}**", f"{b['mde_90']:.3f}",
               f"**{b['mde_80'] / 0.10:.1f}x**", f"{c['auroc']['mde_80']:.3f}",
               f"{c['mae']['mde_80']:.3f} g/dL", f"**{b['verdict']}**"]))
    it = cs["italy_to_india"]
    A(f"\n**The italy->india direction is the least powered comparison in the project.** "
      f"MDE(80%) = {it['specificity_at_matched_sensitivity']['mde_80']:.3f} specificity, "
      f"**{it['specificity_at_matched_sensitivity']['mde_80'] / 0.10:.1f} times** the "
      "pre-declared clinically meaningful margin. The cause is visible in the table and is "
      f"not simply n: of {it['n']} test subjects {it['n_anaemic']} are anaemic and only "
      f"{it['n_non_anaemic']} are not, so **specificity is estimated on "
      f"{it['n_non_anaemic']} subjects**. A specificity comparison on 27 people cannot be "
      "precise, whatever the total sample says.\n\n")
    A(f"**In clinical units**, the smallest detectable specificity gain in that direction "
      f"corresponds to sparing only "
      f"{it['specificity_at_matched_sensitivity']['referrals_avoided_at_mde_80']:.0f} of "
      f"{it['n_non_anaemic']} non-anaemic subjects a needless test - i.e. the design could "
      "only have detected an effect far larger than the one the project declared worth "
      "having.\n\n")
    A("**What this does and does not do to the recorded verdict.** Phase 9A's cross-site "
      "result was **not** a null finding: it reported sensitivity **0.397** in "
      "italy->india, flagging 27 of 68 anaemic subjects - a large, directly observed failure, "
      "not an absence of evidence. A power analysis constrains what *null* comparisons can be "
      "concluded from; it does not weaken an observed collapse. **But the honest statement is "
      "uncomfortable and is made anyway:** the comparison carrying the most weight in this "
      "project - the one that turned a within-site success into a non-deployable verdict - is "
      "also its least precisely estimated, and the *size* of the cross-site penalty is "
      "correspondingly uncertain even though its *direction* is not. Anyone continuing this "
      "line of work should treat the cross-site magnitude as poorly pinned down and collect "
      "more sites before quoting it.\n\n")

    A("### 3.4 PPG - ADEQUATELY POWERED on MAE, UNDERPOWERED on screening AUROC\n\n")
    A(f"n = {ppg['n']} subjects with venous HemoCue reference, "
      f"{ppg['n_anaemic']} anaemic - prevalence **{ppg['prevalence'] * 100:.1f}%**, which is "
      "what drives the split verdict.\n\n")
    A(row(["comparison", "SE", "MDE @80%", "MDE @90%", "yardstick", "verdict"]))
    A(row(["---"] * 6))
    A(row(["deep-model MAE vs sex alone", f"{pm['se']:.4f}", f"**{pm['mde_80']:.3f} g/dL**",
           f"{pm['mde_90']:.3f} g/dL", "1.0 g/dL", f"**{pm['verdict']}**"]))
    A(row(["specificity gain at matched sensitivity vs demographics", f"{ps['se']:.4f}",
           f"**{ps['mde_80']:.3f}**", f"{ps['mde_90']:.3f}", "0.10",
           f"**{ps['verdict']}**"]))
    A(row(["AUROC vs demographics", f"{ppg['auroc']['se']:.4f}",
           f"{ppg['auroc']['mde_80']:.3f}", f"{ppg['auroc']['mde_90']:.3f}",
           "*no pre-declared yardstick*", "*not used for the arm verdict*"]))
    A(f"\n**The MAE comparison is the best-powered in the project**: MDE(80%) = "
      f"{pm['mde_80']:.3f} g/dL on {ppg['n']} subjects with the project's best reference "
      "standard, against a 1.0 g/dL yardstick. Phase 4.5's negative result - the raw-waveform "
      "model losing to sex alone - is therefore **informative**: an improvement of even "
      f"{pm['mde_80']:.2f} g/dL would have been detected, and none of that size exists.\n\n")
    A(f"**The screening AUROC comparison is badly powered, and the reason is prevalence, not "
      f"n.** With only {ppg['n_anaemic']} anaemic subjects of {ppg['n']}, the paired AUROC SE "
      f"is {ppg['auroc']['se']:.4f} and MDE(80%) = {ppg['auroc']['mde_80']:.3f} - an AUROC "
      "gap of nearly 0.27 would be needed for reliable detection. Phase 9A's recorded PPG "
      f"AUROC difference of {ppg['auroc']['observed_difference_note']:+.4f} with CI "
      "[-0.195, +0.189] is therefore **consistent with anything from a moderate real effect "
      "to none at all**, and the arm's AUROC-based conclusion should be read as *uninformative "
      "on its own*. It is the MAE comparison and the number-needed-to-screen arithmetic "
      "(NNS 15.8 vs 14.0 for referring everybody) that carry the PPG verdict, not the AUROC. "
      "The specificity comparison, by contrast, is adequately powered "
      f"(MDE(80%) = {ps['mde_80']:.3f}) because it is estimated on the "
      f"{ppg['n_non_anaemic']} non-anaemic subjects, of which there are many.\n\n")

    # ------------------------------------------------------------------ closing
    A("---\n\n## 4. Verdicts, and what they change\n\n")
    A(row(["arm", "verdict", "the sentence the write-up must carry"]))
    A(row(["---"] * 3))
    A(row(["Imaging regression", f"**{reg['verdict']}**",
           f"MDE(80%) {reg['mde_80']:.2f} g/dL against a 1.0 g/dL clinical yardstick - the "
           "negative result is informative evidence of absence"]))
    A(row(["Imaging screening, within site",
           f"**{cnn['specificity_at_matched_sensitivity']['verdict']}** (marginally)",
           f"MDE(80%) {cnn['specificity_at_matched_sensitivity']['mde_80']:.3f} against 0.10 - "
           "a borderline effect could have been missed, though the effect the arm did find was "
           "comfortably detectable"]))
    A(row(["Imaging cross-site",
           f"**{it['specificity_at_matched_sensitivity']['verdict']}**",
           f"MDE(80%) {it['specificity_at_matched_sensitivity']['mde_80']:.3f} "
           f"({it['specificity_at_matched_sensitivity']['mde_80'] / 0.10:.1f}x the margin) in "
           "italy->india on 27 non-anaemic subjects - the magnitude of the cross-site penalty "
           "is poorly pinned down, though its direction was directly observed"]))
    A(row(["PPG regression", f"**{pm['verdict']}**",
           f"MDE(80%) {pm['mde_80']:.2f} g/dL against 1.0 g/dL - the best-powered comparison "
           "in the project; the negative result is informative"]))
    A(row(["PPG screening (AUROC)", "**UNDERPOWERED**",
           f"MDE(80%) {ppg['auroc']['mde_80']:.2f} AUROC on {ppg['n_anaemic']} anaemic "
           "subjects - the AUROC comparison is uninformative alone"]))
    A("\n**What this phase changes: nothing about any recorded verdict.** It was not run to "
      "reinterpret a result, and it does not. Every MAE and screening number stands exactly as "
      "recorded. What it adds is the second half of each negative sentence - *and we could "
      "have detected an effect of size Y* - which those sentences previously lacked.\n\n")
    A("**Where it connects to the project's own framing.** Phase 7's "
      "`statistical_vs_clinical.md` established that this project's one real effect is "
      "statistically significant and clinically useless. The power analysis closes the "
      "symmetric gap: for the two regression arms the effects that were *too small to detect* "
      "are also **far too small to matter**, which is why their negative results are "
      "informative rather than merely inconclusive. An effect below 0.18 g/dL of MAE is not a "
      "missed opportunity; it is a quantity no clinical decision could use.\n\n")
    A("**What the phase does not establish.** MDEs are computed at the variance structure of "
      "these samples, and a different cohort with different prevalence or different "
      "between-subject spread would have different MDEs. The cross-site MDEs in particular are "
      "estimated on small subsets and are themselves imprecise. No MDE here is a statement "
      "about any future study's power.\n")

    (paths.REPORTS / "phase9d_power.md").write_text("".join(L), encoding="utf-8")
    print(f"wrote {paths.REPORTS / 'phase9d_power.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
