"""Generate `reports/phase9a_screening_metrics.md` from `phase9a/screening.json`.

Leads with the model-versus-baseline screening comparison, not with AUROC. AUROC
without a baseline beside it is exactly the reporting pattern this project criticises
in `reports/literature_gap.md`, so it is never the headline here.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from hemosight.io import paths   # noqa: E402

SRC = paths.INTERIM / "phase9a" / "screening.json"
# Phase 9E computed the cross-site intervals Phase 9A never stored (specificity, PPV,
# referral rate). Read, never retyped; the report degrades to the bare rate if absent.
XSCI = paths.INTERIM / "phase9e" / "cross_site_intervals.json"
DST = paths.REPORTS / "phase9a_screening_metrics.md"


def f(x, nd=3):
    if x is None:
        return "-"
    try:
        v = float(x)
    except (TypeError, ValueError):
        return str(x)
    if v != v:
        return "n/a"
    if v == float("inf"):
        return "inf"
    return f"{v:.{nd}f}"


def ci(pair, nd=3):
    return f"[{f(pair[0], nd)}, {f(pair[1], nd)}]"


def signed(x, nd=3):
    v = float(x)
    return ("n/a" if v != v else f"{v:+.{nd}f}")


def main() -> int:
    r = json.loads(SRC.read_text(encoding="utf-8"))
    img, ppg, xs = r["imaging"], r["ppg"], r["imaging_cross_site"]
    try:
        xsci = json.loads(XSCI.read_text(encoding="utf-8"))["directions"]
    except (OSError, KeyError, json.JSONDecodeError):
        xsci = {}

    def rate(direction, metric, nd=3):
        """A cross-site rate with its interval attached, never bare (Phase 9E)."""
        d = xsci.get(direction, {}).get(metric)
        v = xs["directions"][direction]["cnn"][metric]
        if not d:
            return f(v, nd)
        return f"{f(v, nd)} {ci([d['lo'], d['hi']], nd)}"

    def flagged(direction):
        c = xs["directions"][direction]["cnn"]
        return "%d of %d" % (c["n_anaemic_flagged"], c["n_anaemic"])
    L: list[str] = []
    A = L.append

    A("# Phase 9A - the screening reframe: both arms re-evaluated as a triage task")
    A("")
    A("Generated by `scripts/phase9a_report.py` from `data/interim/phase9a/screening.json`.")
    A("**Every threshold, operating-point criterion and margin in this report was declared")
    A("in CLAUDE.md section 6 and committed (`755da9b`) before any of it ran.**")
    A("")
    A("## Why this phase exists")
    A("")
    A("Every gate in this project was written in mean absolute error, g/dL. The product a")
    A("screening tool delivers is a **binary referral decision**, which is a different task")
    A("with different metrics. This phase tests the recorded refutations on the product's")
    A("own terms. It was not an attempt to rescue them, and one recorded claim did not")
    A("survive - see the correction in section 1.")
    A("")

    # ---------------------------------------------------------------- 1. headline
    A("## 1. THE COMPARISON THAT DECIDES IT - model versus the cheap baseline")
    A("")
    A("The question is never whether the model has skill. It is whether it has skill")
    A("**beyond a demographic baseline**, on the screening task, at an operating point")
    A("chosen without seeing the test labels.")
    A("")
    A("Operating point, pre-declared: **the highest specificity subject to sensitivity")
    A("≥ 0.90, chosen on the training folds only** and applied to the held-out fold.")
    A("Margin, pre-declared: **≥ 0.10** improvement with a **bootstrap CI lower bound")
    A("above zero**, in either direction (sensitivity at matched specificity, or")
    A("specificity at matched sensitivity - the pre-declaration says these count equally).")
    A("")
    A("### 1a. Imaging, pooled site-mixed CV (n = %d, %d anaemic, prevalence %s)"
      % (img["n"], img["n_anaemic"], f(img["prevalence"])))
    A("")
    A("Best demographic baseline: **%s** (selected as the *strongest* demographic"
      % img["best_demographic_baseline_by_auroc"])
    A("competitor by AUROC, which makes the model's task harder, not easier).")
    A("")
    A("| model | matched-spec: sens vs base | diff (95% CI) | matched-sens: spec vs base | diff (95% CI) | margin cleared | verdict |")
    A("| --- | --- | --- | --- | --- | --- | --- |")
    for k, c in img["comparisons"].items():
        ms, mn, b = c["matched_specificity"], c["matched_sensitivity"], c["how_near_the_boundary"]
        A("| `%s` | %s vs %s | **%s** %s | %s vs %s | **%s** %s | %s | **%s** |" % (
            k, f(ms["model_sensitivity"]), f(ms["baseline_sensitivity"]),
            signed(ms["sensitivity_difference"]), ci(ms["sensitivity_difference_ci"]),
            f(mn["model_specificity"]), f(mn["baseline_specificity"]),
            signed(mn["specificity_difference"]), ci(mn["specificity_difference_ci"]),
            "YES" if b["either_margin_cleared"] else "no", c["screening_verdict"]))
    A("")
    A("**What this says.** At a fixed detection rate (sensitivity ≈ 0.90) the image-based")
    A("models refer **fewer** people than demographics for the same cases found. The")
    A("simplest one - three mean CIELAB numbers from the palpebral region plus a ridge -")
    A("gains **%s specificity, CI %s**, which **clears the pre-declared margin**; its"
      % (signed(img["comparisons"]["colour_features_lab"]["matched_sensitivity"]["specificity_difference"]),
         ci(img["comparisons"]["colour_features_lab"]["matched_sensitivity"]["specificity_difference_ci"])))
    A("referral rate is %s against the baseline's %s. The CNN gains %s, CI %s - the CI"
      % (f(img["comparisons"]["colour_features_lab"]["matched_sensitivity"]["model_referral_rate"]),
         f(img["comparisons"]["colour_features_lab"]["matched_sensitivity"]["baseline_referral_rate"]),
         signed(img["comparisons"]["image_cnn"]["matched_sensitivity"]["specificity_difference"]),
         ci(img["comparisons"]["image_cnn"]["matched_sensitivity"]["specificity_difference_ci"])))
    A("excludes zero but the point estimate falls **0.004 short** of the margin.")
    A("")
    A("> ### \U0001F534 CORRECTION to the record, forced by this result")
    A(">")
    A("> The Phase 7 DECISION LOG entry of 2026-09-12 states that controlled capture")
    A("> \"does not beat site + sex + age, and **moves no clinical threshold**\". The first")
    A("> clause stands on MAE. **The second clause is too strong and is corrected here.**")
    A("> At matched sensitivity the image moves the referral burden by a margin that, for")
    A("> the colour model, exceeds what this phase pre-declared as clinically meaningful,")
    A("> with a CI excluding zero. The AUROC advantage over the demographic baseline is")
    A("> also significant: CNN %s, CI %s; colour %s, CI %s."
      % (signed(img["comparisons"]["image_cnn"]["auroc_difference"]),
         ci(img["comparisons"]["image_cnn"]["auroc_difference_ci"]),
         signed(img["comparisons"]["colour_features_lab"]["auroc_difference"]),
         ci(img["comparisons"]["colour_features_lab"]["auroc_difference_ci"])))
    A("> **No model earns USEFUL, and the overall arm verdict does not change - but the")
    A("> reason it does not change is cross-site failure (section 3), not the absence of")
    A("> a clinically meaningful within-site effect.** See `docs/archive/corrections.md`.")
    A("")
    A("### 1b. PPG (n = %d, %d anaemic, prevalence %s) - single site, single device"
      % (ppg["n"], ppg["n_anaemic"], f(ppg["prevalence"])))
    A("")
    A("Best demographic baseline: **%s**." % ppg["best_demographic_baseline_by_auroc"])
    A("")
    A("| model | matched-spec: sens vs base | diff (95% CI) | matched-sens: spec vs base | diff (95% CI) | margin cleared | verdict |")
    A("| --- | --- | --- | --- | --- | --- | --- |")
    for k, c in ppg["comparisons"].items():
        ms, mn, b = c["matched_specificity"], c["matched_sensitivity"], c["how_near_the_boundary"]
        A("| `%s` | %s vs %s | %s %s | %s vs %s | %s %s | %s | **%s** |" % (
            k, f(ms["model_sensitivity"]), f(ms["baseline_sensitivity"]),
            signed(ms["sensitivity_difference"]), ci(ms["sensitivity_difference_ci"]),
            f(mn["model_specificity"]), f(mn["baseline_specificity"]),
            signed(mn["specificity_difference"]), ci(mn["specificity_difference_ci"]),
            "YES" if b["either_margin_cleared"] else "no", c["screening_verdict"]))
    A("")
    A("**Nothing clears a margin in either direction.** The selected deep model is")
    A("**significantly worse** than demographics at matched sensitivity (%s, CI %s), and"
      % (signed(ppg["comparisons"]["ppg_deep_speccnn_660_selected"]["matched_sensitivity"]["specificity_difference"]),
         ci(ppg["comparisons"]["ppg_deep_speccnn_660_selected"]["matched_sensitivity"]["specificity_difference_ci"])))
    A("its AUROC advantage is %s, CI %s - centred on zero."
      % (signed(ppg["comparisons"]["ppg_deep_speccnn_660_selected"]["auroc_difference"]),
         ci(ppg["comparisons"]["ppg_deep_speccnn_660_selected"]["auroc_difference_ci"])))
    A("")

    # ------------------------------------------------- 2. how many cases flagged
    A("## 2. How many anaemic subjects each model actually flags")
    A("")
    A("Pre-declared as belonging in the headline, not a footnote. `refer-everybody` is")
    A("included because a tool that refers everyone has sensitivity 1.00 and no value.")
    A("**NNS** = number needed to screen to correctly refer one anaemic case.")
    A("")
    for arm, a in (("Imaging (pooled)", img), ("PPG", ppg)):
        A("### %s" % arm)
        A("")
        A("| model | MAE g/dL | AUROC (95%% CI) | AUPRC (prev %s) | sens | spec | flagged | referral rate | false-referral | PPV | NPV | NNS | plug-in sens |" % f(a["prevalence"], 3))
        A("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |")
        re_ = a["refer_everybody"]
        A("| *refer everybody* | - | - | - | %s | %s | %d/%d | %s | %s | %s | %s | %s | - |" % (
            f(re_["sensitivity"]), f(re_["specificity"]), re_["n_anaemic_flagged"],
            re_["n_anaemic"], f(re_["referral_rate"]), f(re_["false_referral_rate"]),
            f(re_["ppv"]), f(re_["npv"]), f(re_["number_needed_to_screen"], 1)))
        for k, m in a["models"].items():
            sp = m["screening_point"]
            A("| `%s` | %s | %s %s | %s | %s | %s | %d/%d | %s | %s | %s | %s | %s | %s |" % (
                k, f(m["mae_g_dl"]), f(m["auroc"]), ci(m["auroc_ci"]), f(m["auprc"]),
                f(sp["sensitivity"]), f(sp["specificity"]),
                sp["n_anaemic_flagged"], sp["n_anaemic"], f(sp["referral_rate"]),
                f(sp["false_referral_rate"]), f(sp["ppv"]), f(sp["npv"]),
                f(sp["number_needed_to_screen"], 1),
                f(m["plugin_point"]["sensitivity"])))
        A("")
    A("**The PPG plug-in column reproduces Phase 7 exactly: sensitivity 0.000 for every")
    A("PPG model, flagging none of the 18 anaemic subjects.** That figure is a property of")
    A("the **plug-in rule** - refer if the *predicted* Hb is below the diagnostic")
    A("threshold - not of the model's discriminative ceiling: at a properly chosen")
    A("operating point the same models reach sensitivity 0.889. This does not rescue them.")
    A("At that point the selected deep model refers **%s of everyone** for specificity"
      % f(ppg["models"]["ppg_deep_speccnn_660_selected"]["screening_point"]["referral_rate"]))
    A("%s, and its NNS (%s) is **worse than referring everybody** (%s) because it misses"
      % (f(ppg["models"]["ppg_deep_speccnn_660_selected"]["screening_point"]["specificity"]),
         f(ppg["models"]["ppg_deep_speccnn_660_selected"]["screening_point"]["number_needed_to_screen"], 1),
         f(ppg["refer_everybody"]["number_needed_to_screen"], 1)))
    A("two cases while still referring nine people in ten.")
    A("")

    # -------------------------------------------------------- 3. within / cross
    A("## 3. Within-site and cross-site, never pooled into one number")
    A("")
    A("### 3a. Within site - and a correction to how the recorded AUROC 0.875 reads")
    A("")
    A("**The recorded `who_anaemia_auroc.cnn = 0.875` is POOLED across both sites** and")
    A("had never been decomposed. The two sites differ in mean Hb by 2.4 g/dL and in")
    A("anaemia prevalence by a factor of nearly four, so a site-blind ranking is scored")
    A("partly on separating the sites. Decomposed:")
    A("")
    A("| site | n | anaemic | prevalence | model | AUROC (95% CI) | sens | spec | referral | NNS |")
    A("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    for s, v in img["within_site"].items():
        if "note" in v:
            continue
        for k in ("image_cnn", "colour_features_lab", "demographics_age_sex", "sex_only"):
            m = v[k]
            A("| %s | %d | %d | %s | `%s` | %s %s | %s | %s | %s | %s |" % (
                s.split(":")[1], v["n"], v["n_anaemic"], f(v["prevalence"]), k,
                f(m["auroc"]), ci(m["auroc_ci"]), f(m["sensitivity"]),
                f(m["specificity"]), f(m["referral_rate"]),
                f(m["number_needed_to_screen"], 1)))
    A("")
    A("Within-site comparisons against age+sex (site is constant inside a site, so it")
    A("carries no information there):")
    A("")
    A("| site | model | AUROC diff (95% CI) | matched-sens spec diff (95% CI) | margin cleared | verdict |")
    A("| --- | --- | --- | --- | --- | --- |")
    for s, v in img["within_site"].items():
        if "comparisons" not in v:
            continue
        for k, c in v["comparisons"].items():
            mn = c["matched_sensitivity"]
            A("| %s | `%s` | %s %s | %s %s | %s | **%s** |" % (
                s.split(":")[1], k, signed(c["auroc_difference"]),
                ci(c["auroc_difference_ci"]), signed(mn["specificity_difference"]),
                ci(mn["specificity_difference_ci"]),
                "YES" if c["how_near_the_boundary"]["either_margin_cleared"] else "no",
                c["screening_verdict"]))
    A("")
    A("**The pooled advantage is site-driven.** In India the CNN's AUROC advantage over")
    A("age+sex is %s, CI %s - centred near zero. In Italy it is %s, CI %s. All of the"
      % (signed(img["within_site"]["eyes_defy:India"]["comparisons"]["image_cnn"]["auroc_difference"]),
         ci(img["within_site"]["eyes_defy:India"]["comparisons"]["image_cnn"]["auroc_difference_ci"]),
         signed(img["within_site"]["eyes_defy:Italy"]["comparisons"]["image_cnn"]["auroc_difference"]),
         ci(img["within_site"]["eyes_defy:Italy"]["comparisons"]["image_cnn"]["auroc_difference_ci"])))
    A("pooled ranking advantage comes from one of the two sites.")
    A("")
    A("### 3b. Cross-site - the decisive failure, and it is not a knife-edge")
    A("")
    A("**Counts first, rates second, and no rate without its interval.** Phase 9D found")
    A("this the least precisely estimated comparison in the project, so the observed")
    A("counts - which carry no estimation uncertainty at all - lead, and every rate below")
    A("carries a 95% subject-level bootstrap CI (the specificity, PPV and referral-rate")
    A("intervals were computed in Phase 9E; Phase 9A stored only the sensitivity one).")
    A("")
    A("| direction | n test | anaemic | flagged | MAE (recorded) | bias | AUROC (95% CI) | sens (95% CI) | spec (95% CI) | verdict |")
    A("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |")
    for tag, v in xs.get("directions", {}).items():
        c = v["cnn"]
        A("| %s | %d | %d | **%s** | %s (%s) | %s | %s %s | **%s** | %s | **%s** |" % (
            tag, v["n_test"], v["n_anaemic_test"], flagged(tag),
            f(c["mae_g_dl"]), f(c["mae_recorded"]), signed(c["bias_g_dl"]),
            f(c["auroc"]), ci(c["auroc_ci"]), rate(tag, "sensitivity"),
            rate(tag, "specificity"), v["screening_verdict"]))
    A("")
    A("The operating point is chosen on the **training site** and applied to the held-out")
    A("site, which is the only honest construction available. It transfers badly:")
    A("`italy_to_india` flags **%s** anaemic subjects - sensitivity %s - because"
      % (flagged("italy_to_india"), rate("italy_to_india", "sensitivity")))
    A("the %s g/dL bias pushes predictions above the train-site cut. `india_to_italy`"
      % signed(xs["directions"]["italy_to_india"]["cnn"]["bias_g_dl"], 2))
    A("flags %s anaemic subjects, sensitivity %s, but at specificity %s - below the"
      % (flagged("india_to_italy"), rate("india_to_italy", "sensitivity"),
         rate("india_to_italy", "specificity")))
    A("pre-declared 0.50 floor, and its whole interval is below that floor.")
    A("")
    A("**What is certain here and what is not.** The *direction* of the collapse is")
    A("directly observed and is not in doubt: 41 of 68 anaemic subjects went unflagged in")
    A("one direction, and that is a count, not an estimate. The *magnitude* is another")
    A("matter. `italy_to_india` specificity rests on **%d non-anaemic subjects** and"
      % (xs["directions"]["italy_to_india"]["n_test"]
         - xs["directions"]["italy_to_india"]["n_anaemic_test"]))
    A("Phase 9D measured only 14% power on that direction, so the size of the cross-site")
    A("penalty must not be quoted as a precise quantity. Phase 9E gives the sample that")
    A("would pin it down (`reports/phase9e_boundaries.md`).")
    A("")
    A("**Checked for seed dependence rather than assumed.** Per-seed cross-site operating")
    A("points give sensitivity 0.250 / 0.412 / 0.426 for `italy_to_india` and")
    A("sensitivity 0.957 / 0.957 / 0.826 at specificity 0.449 / 0.378 / 0.602 for")
    A("`india_to_italy`. **No seed satisfies both floors in either direction**, so the")
    A("cross-site verdict does not rest on the non-determinism documented in section 6.")
    A("")

    # ------------------------------------------------------- 4. reconciliation
    A("## 4. Reconciling the screening verdicts with the recorded regression verdicts")
    A("")
    A("| model | recorded regression verdict | screening verdict | screening framing |")
    A("| --- | --- | --- | --- |")
    rows = [
        ("image CNN, pooled", "MAE 1.301 MARGINAL; does not beat site+sex+age (1.273)",
         img["comparisons"]["image_cnn"]["screening_verdict"],
         "**WEAKENS** - AUROC and matched-sensitivity specificity gains over demographics "
         "have CIs excluding zero; the margin is missed by 0.004"),
        ("colour features (Lab)", "MAE 1.343 MARGINAL",
         img["comparisons"]["colour_features_lab"]["screening_verdict"],
         "**WEAKENS** - clears the pre-declared specificity margin (+0.192, CI excludes "
         "zero); misses the 0.90 sensitivity floor by 0.010"),
        ("image CNN, within India", "within-site r 0.54",
         img["within_site"]["eyes_defy:India"]["comparisons"]["image_cnn"]["screening_verdict"],
         "CONFIRMS - no AUROC advantage over age+sex was detected; +0.012, CI "
         "[-0.105, 0.141], which spans zero"),
        ("image CNN, within Italy", "within-site r 0.63",
         img["within_site"]["eyes_defy:Italy"]["comparisons"]["image_cnn"]["screening_verdict"],
         "WEAKENS within this site - AUROC +0.445 (CI excludes zero); still misses the "
         "sensitivity floor"),
        ("image CNN, italy_to_india", "MAE 1.96 MARGINAL",
         xs["directions"]["italy_to_india"]["screening_verdict"],
         "**CONFIRMS, strongly** - misses 41 of 68 anaemic subjects (sensitivity "
         "0.397, 95% CI [0.278, 0.514])"),
        ("image CNN, india_to_italy", "MAE 1.99 MARGINAL",
         xs["directions"]["india_to_italy"]["screening_verdict"],
         "**CONFIRMS** - flags 57 of 98 non-anaemic subjects; specificity 0.418, 95% "
         "CI [0.323, 0.516], the whole interval below the 0.50 floor"),
        ("PPG features, 4-wavelength", "MAE 1.190, R2 -0.025 NOT VIABLE",
         ppg["comparisons"]["ppg_features_four_wavelength"]["screening_verdict"],
         "CONFIRMS **on MAE and NNS, not on AUROC** - AUROC diff -0.001, CI spans "
         "zero, but Phase 9D puts the AUROC MDE at 0.270 on 18 anaemic subjects, so "
         "that comparison is uninformative on its own"),
        ("PPG + demographics", "MAE 0.824 - 'a sex classifier with a PPG-shaped decoration'",
         ppg["comparisons"]["ppg_features_plus_demographics"]["screening_verdict"],
         "CONFIRMS - no margin cleared; specificity gain +0.090 short of 0.10"),
        ("PPG deep, speccnn 660", "MAE 1.113 NOT VIABLE; real but useless (z=-4.96)",
         ppg["comparisons"]["ppg_deep_speccnn_660_selected"]["screening_verdict"],
         "**CONFIRMS, strengthened** - significantly WORSE than demographics at matched "
         "sensitivity (-0.090, CI excludes zero)"),
    ]
    for a_, b_, c_, d_ in rows:
        A("| %s | %s | **%s** | %s |" % (a_, b_, c_, d_))
    A("")
    A("### Verdict per arm")
    A("")
    A("**Imaging: WEAKENED within site, CONFIRMED cross-site.** The recorded clause")
    A("\"moves no clinical threshold\" is contradicted for the site-mixed regime and is")
    A("corrected. The arm remains not deployable, but the binding reason is now the")
    A("cross-site collapse - 41 of 68 anaemic subjects missed in one direction")
    A("(sensitivity 0.397, CI [0.278, 0.514]); 57 of 98 non-anaemic subjects needlessly")
    A("flagged in the other (specificity 0.418, CI [0.323, 0.516]) - rather than the")
    A("absence of a within-site effect. Under this project's own")
    A("hard constraint - *single-site accuracy numbers are considered worthless* - that")
    A("binding reason is the one that governs.")
    A("")
    A("**PPG: CONFIRMED, and strengthened.** No condition clears any margin; the selected")
    A("deep model is significantly worse than demographics at matched sensitivity; its NNS")
    A("is worse than referring everybody. Phase 7's plug-in sensitivity 0.000 reproduces")
    A("exactly, now correctly labelled as a plug-in artefact rather than a discriminative")
    A("ceiling. **The PPG verdict rests on its MAE and NNS figures, which are well")
    A("powered (MDE 0.137 g/dL), and not on its AUROC comparison, whose MDE is 0.270 on")
    A("18 anaemic subjects.** An AUROC difference of -0.000 on that sample is not")
    A("evidence of equivalence; it is an uninformative measurement, and is reported as")
    A("one.")
    A("")
    A("### How precisely these numbers are known (added by Phase 9E)")
    A("")
    A("Phase 9D measured what this design could have detected, and the answer differs")
    A("sharply by comparison. **The two regression comparisons are ADEQUATELY POWERED** -")
    A("MDE 0.181 g/dL for imaging and 0.137 for PPG, against a narrowest WHO band of 1.0 -")
    A("so those negative results are informative evidence of absence and keep their full")
    A("strength. **Three comparisons here are UNDERPOWERED and their nulls are bounded,")
    A("not empty:** within site no specificity gain of 0.10 or larger was detected and")
    A("the design could have detected 0.116 (67% power at the margin); the same applies")
    A("to the sensitivity direction at 0.114. Cross-site, the MDE is 0.314 for")
    A("italy_to_india (14% power) and 0.165 for india_to_italy (40%). **This bounds what")
    A("the null comparisons mean; it does not touch the observed collapse**, which is a")
    A("count of subjects, not an estimate. Phase 9E converts each underpowered comparison")
    A("into a required sample size - see `reports/phase9e_boundaries.md`.")
    A("")

    # ------------------------------------------------------------ 5. thresholds
    A("## 5. WHO thresholds, and which subjects they were applied to")
    A("")
    th = img["thresholds"]
    A("Both datasets are **entirely adult** - Eyes-Defy ages %s-%s, Hb-PPG ages %s-%s,"
      % (f(th["age_min"], 0), f(th["age_max"], 0),
         f(ppg["thresholds"]["age_min"], 0), f(ppg["thresholds"]["age_max"], 0)))
    A("**no subject under 19** - so **no child threshold applies to anyone** and none was")
    A("used. `hemosight.evaluation.screening.who_threshold` raises rather than applying an")
    A("adult threshold to a subject under 15.")
    A("")
    A("| group | threshold | Eyes-Defy | Hb-PPG |")
    A("| --- | --- | --- | --- |")
    A("| men ≥ 15 y | Hb < 13.0 g/dL | applied | applied |")
    A("| non-pregnant women ≥ 15 y | Hb < 12.0 g/dL | applied | applied |")
    A("| children (6-59 mo / 5-11 y / 12-14 y) | 11.0 / 11.5 / 12.0 | none present | none present |")
    A("")
    A("Resulting prevalence: Eyes-Defy **%d of %d (%s)**, Hb-PPG **%d of %d (%s)**."
      % (img["n_anaemic"], img["n"], f(img["prevalence"]),
         ppg["n_anaemic"], ppg["n"], f(ppg["prevalence"])))
    A("")
    A("> **Limitation, declared before running and not resolvable from the data.**")
    A("> **Pregnancy status is not recorded in either dataset.** The non-pregnant")
    A("> threshold is applied to every woman. A pregnant woman's WHO threshold is 11.0")
    A("> g/dL, so any pregnant subject is over-called anaemic in every number above.")
    A("")

    # ------------------------------------------------------------ 6. limitations
    A("## 6. Limitations and reproducibility")
    A("")
    A("1. **The knife-edges are real and are not resolved by this data.** The pooled CNN")
    A("   misses the sensitivity floor by 0.010 (0.890 against 0.900, bootstrap CI")
    A("   [0.822, 0.950]) and the specificity margin by 0.004. The colour model clears the")
    A("   margin but misses the same floor by 0.010. With 91 anaemic subjects the boundary")
    A("   cannot be resolved; the verdict labels should not be read as decisive, and the")
    A("   cross-site result should.")
    A("2. **Pilot scale.** Eyes-Defy is 216 subjects, one image each, one Samsung Galaxy S6")
    A("   in two regional variants, two sites, no severe cases. Hb-PPG is 252 subjects,")
    A("   one site, one device, **18 anaemic subjects** - every PPG interval here is wide")
    A("   for that reason alone.")
    A("3. **The operating point was chosen on training folds only**, so the held-out")
    A("   sensitivity lands near but not exactly on the 0.90 target: all 10/10 folds")
    A("   reached the target in training, and held-out sensitivity is 0.879-0.901.")
    A("4. **`population_mean` is a constant predictor**, so its AUROC (%s imaging, %s PPG)"
      % (f(img["models"]["population_mean"]["auroc"]), f(ppg["models"]["population_mean"]["auroc"])))
    A("   is an artefact of 10 slightly different train-fold means breaking ties, not a")
    A("   ranking. Its screening row is the honest one: it refers everybody.")
    A("5. **Regenerated, because it was never saved.** Phase 4 Gate B and Phase 6.5 Task 2")
    A("   stored only summary metrics, so every **baseline** per-subject prediction here was")
    A("   regenerated with the same estimators on the identical folds")
    A("   (`KFold(10, shuffle=True, random_state=20260911)`, verified identical across both")
    A("   PPG scripts). The four-wavelength PPG predictions were reused from the Phase 6")
    A("   known-truth files and reproduce the recorded MAEs to 0.0000.")
    A("6. **Cross-site CNN non-determinism, measured not assumed.** The cross-site")
    A("   predictions had to be regenerated (only MAE was stored). Two independent runs of")
    A("   the identical seeded construction gave seed-averaged MAE 1.863 then 1.914")
    A("   (`italy_to_india`) and 1.978 then 1.882 (`india_to_italy`) - a spread of")
    A("   0.05-0.10 g/dL, and up to 0.167 per seed. That is an order of magnitude larger")
    A("   than the ~0.01 tolerance documented for the deep sweep. The cross-site path")
    A("   trains a single model on one site with no fold averaging, and no cuDNN")
    A("   determinism flags are set in this project; **the cause was not isolated and is")
    A("   not recorded as established.** All observed values stay inside the MARGINAL band")
    A("   and no seed satisfies both screening floors, so no verdict moves.")
    A("")
    A("## 7. Reproduce")
    A("")
    A("```")
    A("python scripts/phase9a_cross_site_preds.py   # GPU, ~45 s")
    A("python scripts/phase9a_screening.py          # CPU, ~5-6 min")
    A("python scripts/phase9a_report.py")
    A("```")
    A("")
    A("Nothing here is a clinical validation. All evaluation is retrospective, on public")
    A("datasets, and every number is a screening-triage figure on a pilot-scale cohort.")

    DST.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {DST} ({len(chr(10).join(L)):,} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
