"""Phase 4, Task 4: generate reports/phase4_ppg_gate.md.

Both gate results are stated first. Thresholds were declared in CLAUDE.md before
anything ran.

    .\\.venv\\Scripts\\python.exe scripts\\ppg_gate_report_phase4.py
"""

from __future__ import annotations

import json

from hemosight.io import paths

IN = paths.INTERIM / "phase4"


def load(n):
    p = IN / n
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def row(c):
    return "| " + " | ".join(str(x) for x in c) + " |\n"


def main() -> int:
    a, b, q = load("gate_a.json"), load("gate_b.json"), load("task2_sqi.json")
    L: list[str] = []
    A = L.append

    A("# Phase 4 - The PPG arm: BOTH GATES FAILED\n\n")
    A("Generated by `scripts/ppg_gate_report_phase4.py`. Thresholds were declared in CLAUDE.md "
      "before any of this ran.\n\n")

    # ------------------------------------------------------------- headline
    if b:
        four = b["conditions"]["1_four_wavelength"]
        phone = b["conditions"]["3_phone_rgb_simulated"]
        demo = b["baselines"]["demographics"]
        mean = b["baselines"]["population_mean"]
        A("## 0. THE RESULT IN ONE TABLE\n\n")
        A(row(["predictor", "MAE g/dL", "R^2", "verdict"]))
        A(row(["---"] * 4))
        A(row(["**sex alone**", f"**{b['baselines']['sex_only']['mae_g_dl']:.3f}**",
               f"{b['baselines']['sex_only']['r2']:.3f}", "best in the study"]))
        A(row(["demographics (age/sex/height/weight)", f"{demo['mae_g_dl']:.3f}",
               f"{demo['r2']:.3f}", "same as sex alone"]))
        A(row(["population mean (predict 13.9 for everyone)", f"{mean['mae_g_dl']:.3f}",
               "0.000", "the null model"]))
        A(row(["**PPG, all four wavelengths**", f"**{four['mae_g_dl']:.3f}**",
               f"**{four['r2']:+.3f}**", "**worse than the mean**"]))
        A(row(["PPG, 660 nm only",
               f"{b['conditions']['2_660nm_only']['mae_g_dl']:.3f}",
               f"{b['conditions']['2_660nm_only']['r2']:+.3f}", "worse than the mean"]))
        A(row(["PPG, simulated phone-RGB", f"{phone['mae_g_dl']:.3f}",
               f"{phone['r2']:+.3f}", "equal to the mean"]))
        A("\n**Four-wavelength PPG has a negative R^2** - it predicts haemoglobin worse "
          "than assuming every subject has the population average. **Sex alone beats it "
          "by 30%.** Everything below is explanation.\n")

    # ------------------------------------------------------------- GATE A
    if a:
        A("\n---\n\n## 1. GATE A - does the AC/DC normalisation cancel? **FAIL**\n\n")
        A(f"> **{a['gate_a']}**. The normalisation does not reduce non-haemoglobin "
          f"variance on real data. It *increases* it: median nuisance CV goes from "
          f"**{a['raw_dc_nuisance_cv']:.3f}** for raw DC to "
          f"**{a['normalised_nuisance_cv']:.3f}** for AC/DC "
          f"({a['reduction_acdc']*100:+.1f}%) and **{a['ratio_nuisance_cv']:.3f}** for "
          f"the ratio-of-ratios ({a['reduction_ratio']*100:+.1f}%). The declared "
          f"threshold was a reduction of 50% or more.\n\n")
        A(row(["feature group", "median nuisance CV", "reduction vs raw DC",
               "median R^2 with Hb"]))
        A(row(["---"] * 4))
        for g, v in a["groups"].items():
            red = 1.0 - v["median_nuisance_cv"] / a["raw_dc_nuisance_cv"]
            A(row([g, f"{v['median_nuisance_cv']:.4f}",
                   "-" if "RAW DC" in g else f"{red*100:+.1f}%",
                   f"{v['median_r2_hb']:.4f}"]))
        A(f"\nThe best single feature has an equivalent haemoglobin noise of "
          f"**{a['best_equivalent_hb_noise_g_dl']:.2f} g/dL** against a population "
          f"spread of only **{a['population_hb_sd']:.3f} g/dL**. The noise is "
          f"{a['best_equivalent_hb_noise_g_dl']/a['population_hb_sd']:.1f}x the signal "
          f"it has to resolve.\n")

        A("\n### An honest limitation of Gate A as designed\n\n")
        A("Part of the cancellation claim is **not testable on this dataset**. AC/DC is "
          "supposed to cancel source intensity and sensor gain - but all 252 subjects "
          "were recorded on **one device**, so there is no device variation present for "
          "it to cancel. The between-subject DC variation here (CV 0.39-0.63) reflects "
          "finger thickness, perfusion and skin tone, not instrument differences.\n\n")
        A("What Gate A *does* establish is the part that matters: AC/DC also claims to "
          "cancel **static tissue absorption**, and it demonstrably does not - the "
          "normalised features are more subject-variable than the raw DC they came "
          "from, and none of them carries haemoglobin information. So the gate is weak "
          "on one half of its premise and decisive on the other.\n")

    # ------------------------------------------------------------- GATE B
    if b:
        A("\n---\n\n## 2. GATE B - the wavelength restriction\n\n")
        A("### 2.1 What a phone can actually sense\n\n")
        A("This is not an estimate. The Jiang camspec database gives measured "
          "sensitivities for 28 cameras over 400-720 nm:\n\n")
        A(row(["PPG wavelength", "mean R", "mean G", "mean B", "visible to a phone?"]))
        A(row(["---"] * 5))
        A(row(["660 nm", "0.1787", "0.0158", "0.0066", "**yes, in R only**"]))
        for lam in (730, 850, 940):
            A(row([f"{lam} nm", "0.0000", "0.0000", "0.0000",
                   "**no** - beyond 720 nm and behind the IR-cut filter"]))
        A("\n**A phone sees one of the four wavelengths, in one of its three channels.** "
          "Three quarters of the dataset's measurement is invisible to the target "
          "hardware. That is a hardware fact, independent of any model.\n")

        A("\n### 2.2 Results per condition, grouped 10-fold CV\n\n")
        A("Each subject contributes exactly one record, so a subject-level K-fold IS "
          "leave-subject-out - no within-subject split is possible or was made.\n\n")
        A(row(["condition", "n features", "MAE g/dL", "Pearson r", "R^2", "band"]))
        A(row(["---"] * 6))
        for k in ("1_four_wavelength", "2_660nm_only", "3_phone_rgb_simulated"):
            v = b["conditions"][k]
            A(row([k, v["n_features"], f"**{v['mae_g_dl']:.3f}**",
                   f"{v['pearson_r']:+.3f}", f"{v['r2']:+.3f}", v["band"]]))
        A(f"\nA non-linear model finds nothing either: gradient boosting on the "
          f"four-wavelength features gives MAE "
          f"**{b['gbr_four_wavelength']['mae_g_dl']:.3f}** g/dL, r = "
          f"{b['gbr_four_wavelength']['pearson_r']:+.3f}.\n")
        A("\n**The bands say MARGINAL, and the bands are misleading here.** An MAE near "
          "1.18 g/dL looks tolerable only because the population spread is itself small "
          "(SD 1.47 g/dL). The R^2 is the honest statistic: **negative** for two of the "
          "three conditions. These models are worse than a constant.\n")

    # ------------------------------------------------------------- TASK 3
    if b:
        A("\n---\n\n## 3. Task 3 - the baselines, and why they decide the phase\n\n")
        A(row(["model", "MAE g/dL", "Pearson r", "R^2"]))
        A(row(["---"] * 4))
        for name, key in (("population mean", "population_mean"),
                          ("sex alone", "sex_only"),
                          ("demographics (age, sex, height, weight)", "demographics")):
            v = b["baselines"][key]
            A(row([name, f"{v['mae_g_dl']:.3f}", f"{v.get('pearson_r', 0.0):+.3f}",
                   f"{v['r2']:+.3f}"]))
        A("\nTwo things follow, and both matter more than any PPG number:\n\n")
        A("1. **Sex alone (MAE 0.831) equals full demographics (0.831).** Age, height "
          "and weight add nothing. This is ordinary physiology - men carry higher "
          "haemoglobin, which is why the WHO thresholds themselves differ by sex "
          "(13 g/dL for men, 12 for women).\n")
        A("2. **Adding PPG to demographics does not improve demographics.** "
          "Demographics alone 0.831; four-wavelength PPG plus demographics "
          f"{b['conditions']['1_four_wavelength_plus_demographics']['mae_g_dl']:.3f}; "
          "phone-RGB plus demographics "
          f"{b['conditions']['3_phone_rgb_simulated_plus_demographics']['mae_g_dl']:.3f}. "
          "The differences are noise.\n\n")
        A("> **This is the trap the pre-declared thresholds would have walked into.** "
          "A 'PPG + demographics' model scores MAE 0.824, which is inside the VIABLE "
          "band. Reported without the baseline it would look like a working PPG "
          "haemoglobin estimator. It is a sex classifier with a PPG-shaped decoration "
          "attached. Task 3 exists precisely to catch this, and it did.\n")

    # ------------------------------------------------------------- TASK 2
    if q:
        A("\n---\n\n## 4. Task 2 - signal quality and abstention\n\n")
        A(row(["SQI threshold", "rejection rate"]))
        A(row(["---", "---"]))
        for t, v in q["rejection_rates"].items():
            A(row([f"SQI < {t}", f"{v*100:.1f}%"]))
        A(f"\n**It does not repeat the Phase 2 defect.** The Phase 2 image quality score "
          f"had AUROC 0.816 yet rejected 0 of 17 deliberately-bad frames - it ranked but "
          f"never refused. This SQI rejects **{q['rejection_rates']['0.3']*100:.1f}%** at "
          f"its operating threshold, and the rejected group does have higher error "
          f"({q['mae_rejected']:.3f} vs {q['mae_retained']:.3f} g/dL).\n\n")
        A(f"But the relationship is weak and non-monotonic: r(SQI, |error|) = "
          f"**{q['r_sqi_error']:+.3f}**, and MAE by SQI quartile runs 0.892, 0.796, "
          f"0.868, 0.769 - no trend. And there is a deeper problem: the only model with "
          f"any skill is the demographics model, which uses no PPG at all, so 'signal "
          f"quality predicting its error' has no mechanism and the small difference is "
          f"most likely chance. **A quality index cannot be meaningfully validated "
          f"against a model that ignores the signal it measures.**\n")

        A("\n### The dataset's own SNR claim could not be reproduced\n\n")
        A("The dataset reports 850 nm as cleanest (19.04 dB) and 940 nm as worst "
          "(16.44 dB, 17.5% of subjects below 10 dB). An independent computation - "
          "cardiac-band power including harmonics against out-of-band power - gives "
          "8.1-8.3 dB for all four channels with **no meaningful ordering** and 71-73% "
          "of subjects below 10 dB.\n\n")
        A("The README does not define its SNR, so this is a difference of definition "
          "rather than a contradiction. It is reported rather than tuned into agreement: "
          "matching a published number by adjusting an undocumented definition would be "
          "fitting to the answer.\n")

    # ------------------------------------------------------------- verdict
    A("\n---\n\n## 5. Verdict\n\n")
    A(row(["gate / condition", "result"]))
    A(row(["---", "---"]))
    A(row(["**GATE A** - does AC/DC cancel nuisances?", "**FAIL**"]))
    A(row(["**GATE B** - four wavelengths", "**NOT VIABLE** (negative R^2)"]))
    A(row(["**GATE B** - 660 nm only", "**NOT VIABLE** (negative R^2)"]))
    A(row(["**GATE B** - simulated phone-RGB", "**NOT VIABLE** (R^2 ~ 0)"]))
    A("\n### The PPG arm: **NOT VIABLE** on this dataset\n\n")
    A("Stated plainly. Four-wavelength contact PPG, with the physically-motivated "
      "AC/DC and ratio-of-ratios features that pulse oximetry is built on, carries **no "
      "recoverable haemoglobin information** in these 252 subjects. It does not beat "
      "predicting the population mean, and it is beaten outright by asking the "
      "subject's sex.\n\n")
    A("The phone-deployability question is answered even more simply: **three of the "
      "four wavelengths are invisible to a phone camera**, so even a working "
      "four-wavelength method could not have transferred to the target hardware.\n")

    A("\n### What was tested, and what was not\n\n")
    A("* **Tested:** AC/DC per wavelength, ratio-of-ratios for all six wavelength "
      "pairs, perfusion index, pulse morphology summaries (beat CV, spectral purity, "
      "SNR, heart rate), linear (Ridge) and non-linear (gradient boosting) models, "
      "grouped 10-fold CV, against three baselines.\n")
    A("* **Not tested:** a deep model over raw waveforms. It is the remaining untried "
      "representation. It is recorded as untested, not as a proposed rescue.\n")
    A("* **Limits of this dataset:** one device, so the device-invariance half of the "
      "AC/DC claim is untestable; haemoglobin spans only 8.5-17.3 g/dL with SD 1.47 and "
      "**no severe anemia at all**, and a narrow range depresses every correlation.\n")

    (paths.REPORTS / "phase4_ppg_gate.md").write_text("".join(L), encoding="utf-8")
    print(f"wrote {paths.REPORTS / 'phase4_ppg_gate.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
