"""Phase 1.5, Task 8: generate reports/phase1_5_remediation.md.

Reads the machine-produced evidence (label arbitration JSON, original-image search
JSON, manifests) so every number in the report traces to a script rather than to
prose written once and never re-checked.

    .\\.venv\\Scripts\\python.exe scripts\\remediation_report_phase1_5.py
"""

from __future__ import annotations

import json

import pandas as pd

from hemosight.io import paths


def main() -> int:
    arb = json.loads((paths.INTERIM / "phase1_5_label_arbitration.json").read_text(encoding="utf-8"))
    srch = json.loads((paths.INTERIM / "phase1_5_original_search.json").read_text(encoding="utf-8"))
    master = pd.read_csv(paths.MANIFESTS / "master.csv")

    q1, q2, q3 = arb["Q1_cp_anemic_hb"], arb["Q2_ghana_binary"], arb["Q3_cross_binary_agreement"]
    noise = arb["binary_label_noise"]
    scan = {r["dataset"]: r for r in srch["full_scan"]}
    trusted = master[master.hb_label_trusted.astype(bool)]

    L: list[str] = []
    A = L.append

    A(f"""# Phase 1.5 - Remediation of the Phase 1 findings

Generated by `scripts/remediation_report_phase1_5.py`. Every number below is read from
`data/interim/phase1_5_*.json` or the manifests, not transcribed by hand.

Phase 1 produced four findings that threatened the claim set: the two largest
conjunctiva datasets have no sclera, CP-AnemiC is contained inside the Ghana set with
self-contradictory haemoglobin labels, SCIN shipped no data, and figures containing
dataset pixels were version-controlled. Phase 1.5 resolved each one. **No claim was
abandoned. Three were narrowed, one was restructured, and one method was replaced.**

---

## Summary of decisions

| # | Decision | Evidence | Effect on the claim set |
| --- | --- | --- | --- |
| 1 | N1 split into **N1a / N1b / N1c** | Sclera absent from 4,972 cutouts | Headline survives; only N1c is bounded |
| 2 | Uncropped originals **do not exist** | Exhaustive scan + RAR5 listing | N1c permanently limited to 218 subjects |
| 3 | Ghana pool is **BINARY-LABEL-ONLY** | {q1['groups_with_conflicting_hb']}/{q1['duplicate_groups']} groups conflict on Hb | Hb regression base drops to **{len(trusted)} rows** |
| 4 | N2 justification **corrected** | 48 severe cases do exist, but are unreliable | Argument moves to label trustworthiness |
| 5 | N5 **rebuilt on ITA**, SCIN deleted | SCIN held 0 data files | N5 loses its external dependency |
| 6 | N6 **scoped**, permanently | No Hb on paired subjects; no PPG overlap | Classification-only + simulation-only |
| 7 | `reports/figures/` **untracked** | 9/10 licences unverified | No dataset pixels in git |

---

## 1. N1 restructured into three sub-claims

The Phase 1 finding does not invalidate N1 - it invalidates treating N1 as a single
end-to-end claim. Two of the three sub-claims are entirely unaffected by the cutout
problem, because neither needs haemoglobin labels.

| Sub-claim | Question | Dataset | Metric | Affected by the cutout finding? |
| --- | --- | --- | --- | --- |
| **N1a** | Is the illuminant estimate accurate across sensors? | `nus8`, 6 cameras, 1,265 images | Angular error, ΔE2000 vs colorchecker | **No** |
| **N1b** | Is the sclera a valid white reference across devices and lighting? | `MOBIUS` 3 phones x 3 lighting x 100 subjects; `SBVPI` | ΔE2000 spread across conditions per subject, before vs after correction | **No** |
| **N1c** | Does the correction improve Hb estimation end to end? | Eyes-Defy only | Hb MAE, bias, Bland-Altman | **Yes - bounded** |

**N1b's protocol is the important addition.** It tests the white-reference premise
*without any haemoglobin label*, by self-consistency: images of one subject taken on
different phones under different lighting show the same tissue, so a valid reference
should bring their corrected colour into agreement. Controls are grey-world,
white-patch, and no correction. This is why MOBIUS - previously written off as
"segmentation only, no Hb" - turns out to be the single most valuable dataset for the
headline claim.

**N1c carries a fixed limitation** that must be stated wherever it is reported:
218 subjects, 2 sites, 2 regional variants of one Samsung Galaxy S6, no severe cases
(minimum 7.0 g/dL).

---

## 2. The search for uncropped originals: conclusively negative

Full scan of every image, not a sample.

| dataset | n | black mean | **black MIN** | n < 5% black | max MP |
| --- | --- | --- | --- | --- | --- |""")

    for d in ("cp_anemic", "ghana_conj", "ghana_nail", "eyes_defy"):
        r = scan[d]
        A(f"\n| {d} | {r['n_images']:,} | {r['black_mean']:.3f} | **{r['black_min']:.3f}** | "
          f"{r['n_below_5pct_black']} | {r['max_megapixels']:.2f} |")

    rar = next((a for a in srch["archives"] if a["archive"].endswith(".rar")), {})
    A(f"""

**The least-cropped image in either conjunctiva dataset is still ~49.7% black**, and the
largest is 0.14 MP against Eyes-Defy's 11.9 MP. Not one image in either set falls below
5% black.

Archives were checked too. `Fingernails.rar` was listed with a pure-Python RAR5 header
parser (no extraction - `data/raw/` stays read-only): **{rar.get('listed_entries', 'n/a')} entries,
{rar.get('extensions', {}).get('.png', 'n/a')} PNGs with names identical to the extracted folder** - a compressed copy, not
originals. The 12 nus8 archives are sensor data. `ghana_conj` has no subdirectories and
no non-image files.

**Conclusion, recorded so it is never re-litigated: the cutouts are the only form in
which these data were ever distributed.** Widening N1c would require contacting the
original authors, which the project's constraints exclude.

---

## 3. Haemoglobin label arbitration

The task as briefed asked which collection's Hb to adopt for shared images. **That
comparison could not be run as stated**: the Ghana conjunctiva set ships
**{q2['hb_values_present']} haemoglobin values**. "Adopt Ghana as authoritative" was never an available
option. The arbitration therefore answered four answerable questions instead.

| Question | Result |
| --- | --- |
| Q1. Is CP-AnemiC's Hb self-consistent per unique image? | **No** - {q1['groups_with_conflicting_hb']} of {q1['duplicate_groups']} duplicate groups conflict; worst spread **{q1['max_hb_spread_within_one_image']:.2f} g/dL** |
| Q2. Is Ghana's binary label self-consistent? | **Yes** - {q2['groups_with_conflicting_binary_label']} of {q2['duplicate_groups']} groups conflict |
| Q3. Do the two agree on the binary label for shared images? | **{q3['binary_label_agree']}/{q3['shared_unique_images']} ({100*q3['agreement_rate']:.2f}%)** - {q3['binary_label_disagree']} disagreements |
| Q4. Is CP-AnemiC's Hb consistent with its own binary label? | **Exactly** - label is precisely `hb < 11.0`, 0 mismatches |

**Verdict: `{arb['verdict']}`.** Neither collection is self-consistent on haemoglobin,
so the briefed fallback applies: the entire Ghana pool leaves every Hb regression task.

### The flag is structural, not advisory

`hb_label_trusted` is set inside `_finalise()` in `src/hemosight/io/manifests.py`, so it
is written by **every** builder and **survives a manifest rebuild**. A `trusted_hb()`
helper raises if the column is missing. Downstream code cannot silently consume a
rejected value by calling `df.hb_g_dl.notna()`.

| dataset | trusted Hb rows |
| --- | --- |""")

    for d, n in master.groupby("dataset").hb_label_trusted.sum().items():
        A(f"\n| {d} | {int(n)} |")

    A(f"""

**The project's entire trustworthy haemoglobin base is {len(trusted)} rows**
({', '.join(f'{k} {int(v)}' for k, v in trusted.groupby('dataset').size().items())}),
spanning {trusted.hb_g_dl.min():.1f}-{trusted.hb_g_dl.max():.1f} g/dL, containing
**{int((trusted.hb_g_dl < 7).sum())} severe cases**.

### A second finding: the retained binary label has its own noise floor

Ghana's binary label is internally self-consistent, but it **disagrees with CP-AnemiC on
{q3['binary_label_disagree']} of {q3['shared_unique_images']} shared unique images ({100*noise['observed_noise_floor']:.2f}%)**. Since CP-AnemiC's label is exactly
`hb < 11.0`, each disagreement is a genuine mislabelling in one collection or the other.
Five are images CP-AnemiC assigns non-conflicted Hb of 8.9-10.6 g/dL (clearly anemic)
that Ghana files as `Non-Anemic-0NN`.

**No binary result on this pool may claim accuracy above ~{100*(1-noise['observed_noise_floor']):.1f}% and attribute the
gap to the model.** The rate is measurable on {q3['shared_unique_images']} images and unmeasurable on the rest.

---

## 4. N2's justification corrected

**Was:** *"This supplies severe-anemia cases that no public dataset contains."* -
factually false; CP-AnemiC holds 48 images below 7 g/dL, minimum 3.1 g/dL.

**Now:** *"The only real severe-anemia cases available (n=48, single site) carry mutually
contradictory haemoglobin labels, as established in Phase 1. The Monte Carlo forward
model is therefore the only source of reliably labelled severe anemia in this project.
Its purpose is label trustworthiness, not merely data quantity."*

The replacement is not a retreat. The 48 cases are precisely the ones the arbitration
rejected, so the simulator remains the only trustworthy source for the severe range -
an argument that follows directly from Phase 1 evidence rather than from an unchecked
claim about the literature.

---

## 5. N5 rebuilt without SCIN

`data/raw/scin-main/` was deleted: 5 documentation files, 212 KB, **0 data files**.
SCIN's images live in a GCS bucket that was never downloaded, and SCIN is dermatology
imagery with no conjunctiva, no haemoglobin, and no participant correspondence to any
dataset here.

N5's method is now:

- **Skin tone:** Individual Typology Angle, closed form from CIELAB, on periocular skin
  in **N1-calibrated** images. Reusing the N1 pipeline is what makes the decomposition
  mechanistic rather than descriptive.
- **Population axis:** India vs Italy within Eyes-Defy.
- **Device axis:** MOBIUS, 3 phones x 3 lighting conditions.
- **Decomposition:** melanin vs illuminant error, testable in N2 simulation where
  melanin is known by construction.

**Limitations, verbatim for the paper:** no ground-truth skin tone labels; ITA is a
proxy; the tone axis is confounded with site.

This is the only deliberate deletion inside `data/raw/`, made on explicit instruction.
It removed documentation, not data, and is recoverable from
`github.com/google-research-datasets/scin`. The READ-ONLY rule otherwise stands.

---

## 6. N6 scoped

Recorded as **fixed limits, not open problems**:

- **Real fusion is conjunctiva + nail, classification only.** The ~454 paired
  participants are in the BINARY-LABEL-ONLY pool, so no fused, calibrated g/dL estimate
  can be validated on paired modalities.
- **Image + PPG fusion is simulation-only, permanently.** `Hb_PPG_Dataset` shares no
  participants with any image dataset, and under "no new data ever" it never will.

---

## 7. Figures removed from version control

`reports/figures/` renders dataset pixels, and 9 of 10 datasets ship no licence file.
It is now in `.gitignore` and removed from the index with `git rm -r --cached` (files
kept on disk). `reports/README.md` gives the exact regeneration commands per figure.
Verified: `git ls-files reports/figures/` returns nothing.

---

## What changed in the claim set

| Claim | Before Phase 1.5 | After |
| --- | --- | --- |
| N1 | One end-to-end claim, apparently refuted | Three sub-claims; two unaffected, one bounded |
| N2 | Premise factually false | Premise is label trustworthiness |
| N3 | unchanged | unchanged |
| N4 | unchanged | unchanged |
| N5 | Depended on SCIN, which has no usable data | ITA on N1-calibrated skin, no external dependency |
| N6 | Implied validated multimodal Hb regression | Classification-only + simulation-only, stated as permanent |

**Nothing was abandoned.** The claim set is smaller in scope and considerably harder to
refute than it was before the audit.
""")

    out = paths.REPORTS / "phase1_5_remediation.md"
    out.write_text("".join(L), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
