"""Phase 9A: re-evaluate both arms as a SCREENING task, not a regression task.

Every gate in this project was written in mean absolute error, g/dL. The product a
screening tool delivers is a binary referral decision. This script evaluates that task
against the criteria pre-declared in CLAUDE.md section 6 (Phase 9A) and committed
before it ran.

Nothing is retrained except what was never saved: the cross-site image-CNN per-subject
predictions (Phase 6.5 wrote only summary MAE), regenerated by
`scripts/cross_site_cnn_predictions_phase9a.py` with the recorded construction. Baseline
per-subject predictions were likewise never saved and are regenerated here on the
IDENTICAL folds - KFold(10, shuffle=True, random_state=20260911) - using the same
estimators as Phase 4 Gate B and Phase 6.5 Task 2.

Outputs `data/interim/phase9a/screening.json`.
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.linear_model import RidgeCV
from sklearn.model_selection import KFold
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from hemosight.evaluation import screening as scr   # noqa: E402
from hemosight.io import paths                      # noqa: E402

SEED = 20260911
N_SPLITS = 10
OUT = paths.INTERIM / "phase9a"
IMG_PRED = paths.INTERIM / "phase6_5" / "image_cnn_predictions.csv"
IMG_CROPS = paths.INTERIM / "phase6_5" / "eyes_defy_crops.npz"
IMG_JSON = paths.INTERIM / "phase6_5" / "image_cnn.json"
XS_PRED = OUT / "cross_site_predictions.csv"
PPG_DEEP = paths.INTERIM / "phase6" / "known_truth" / "phase5_deep_model.csv"
PPG_FEAT = paths.INTERIM / "phase4" / "features.csv"
PPG_GATEB = paths.INTERIM / "phase4" / "gate_b.json"


# --------------------------------------------------------------------- helpers
def folds_for(n: int) -> list[tuple]:
    """The project's one fold construction, used by every arm."""
    return list(KFold(N_SPLITS, shuffle=True, random_state=SEED).split(np.arange(n)))


def ridge_cv(F: np.ndarray, y: np.ndarray, folds: list[tuple]) -> np.ndarray:
    """Phase 6.5 / Phase 4 Gate B baseline estimator, unchanged."""
    preds = np.full(len(y), np.nan)
    for tr, te in folds:
        m = make_pipeline(SimpleImputer(strategy="median"), StandardScaler(),
                          RidgeCV(alphas=np.logspace(-3, 3, 25)))
        m.fit(F[tr], y[tr])
        preds[te] = m.predict(F[te])
    return preds


def mean_cv(y: np.ndarray, folds: list[tuple]) -> np.ndarray:
    preds = np.full(len(y), np.nan)
    for tr, te in folds:
        preds[te] = y[tr].mean()
    return preds


def evaluate_model(name: str, score: np.ndarray, y: np.ndarray, truth: np.ndarray,
                   thr: np.ndarray, folds: list[tuple]) -> dict:
    """Every screening quantity for one model, at both operating points."""
    nested = scr.nested_calls(score, truth, folds)
    at_point = scr.screening_metrics(truth, nested["call"])
    plug = scr.screening_metrics(truth, scr.plugin_calls(score, thr))
    rank = scr.ranking_metrics(truth, score)

    auroc_ci = scr.bootstrap_ci(truth, score,
                                lambda t, s: scr.ranking_metrics(t, s)["auroc"])
    auprc_ci = scr.bootstrap_ci(truth, score,
                                lambda t, s: scr.ranking_metrics(t, s)["auprc"])
    sens_ci = scr.bootstrap_ci(truth, nested["call"],
                               lambda t, c: scr.screening_metrics(t, c)["sensitivity"])
    spec_ci = scr.bootstrap_ci(truth, nested["call"],
                               lambda t, c: scr.screening_metrics(t, c)["specificity"])
    return {
        "name": name,
        "mae_g_dl": float(np.mean(np.abs(score - y))),
        "auroc": rank["auroc"], "auroc_ci": [auroc_ci["lo"], auroc_ci["hi"]],
        "auprc": rank["auprc"], "auprc_ci": [auprc_ci["lo"], auprc_ci["hi"]],
        "auprc_baseline_prevalence": rank["auprc_baseline"],
        "screening_point": {**at_point,
                            "sensitivity_ci": [sens_ci["lo"], sens_ci["hi"]],
                            "specificity_ci": [spec_ci["lo"], spec_ci["hi"]],
                            "folds_reaching_target_sensitivity":
                                nested["folds_reaching_target"],
                            "n_folds": nested["n_folds"],
                            "mean_cut_g_dl": nested["mean_cut"]},
        "plugin_point": plug,
        "roc": scr.roc_points(truth, score),
        "_call": nested["call"], "_score": score,
    }


def compare(model: dict, base: dict, truth: np.ndarray, folds: list[tuple]) -> dict:
    """The comparison that decides it: model vs baseline at matched operating points."""
    m_matched = scr.nested_calls_matched_specificity(
        model["_score"], truth, folds, base["_score"])
    m_at_matched = scr.screening_metrics(truth, m_matched["call"])
    d_sens = scr.paired_difference_ci(truth, m_matched["call"], base["_call"],
                                      "sensitivity")

    # Symmetric test: hold SENSITIVITY at the baseline's train level and compare
    # specificity. (An earlier version of this function matched specificity in both
    # branches, which made the specificity comparison vacuous - both were matched by
    # construction. Fixed before any number here was reported.)
    m_matched_sens = scr.nested_calls_matched_sensitivity(
        model["_score"], truth, folds, base["_score"])
    m_at_matched_sens = scr.screening_metrics(truth, m_matched_sens["call"])
    d_spec = scr.paired_difference_ci(truth, m_matched_sens["call"], base["_call"],
                                      "specificity")

    d_auroc = scr.bootstrap_ci(
        truth, np.stack([model["_score"], base["_score"]], 1),
        lambda t, s: (scr.ranking_metrics(t, s[:, 0])["auroc"]
                      - scr.ranking_metrics(t, s[:, 1])["auroc"]))
    auroc_diff = model["auroc"] - base["auroc"]

    v = scr.verdict(model["screening_point"]["sensitivity"],
                    model["screening_point"]["specificity"],
                    d_sens["diff"], d_sens["lo"], d_spec["diff"], d_spec["lo"])
    return {
        "model": model["name"], "baseline": base["name"],
        "matched_specificity": {
            "target_train_specificity": m_matched["matched_train_specificity"],
            "model_sensitivity": m_at_matched["sensitivity"],
            "model_specificity": m_at_matched["specificity"],
            "model_n_anaemic_flagged": m_at_matched["n_anaemic_flagged"],
            "baseline_sensitivity": base["screening_point"]["sensitivity"],
            "baseline_specificity": base["screening_point"]["specificity"],
            "baseline_n_anaemic_flagged": base["screening_point"]["n_anaemic_flagged"],
            "sensitivity_difference": d_sens["diff"],
            "sensitivity_difference_ci": [d_sens["lo"], d_sens["hi"]],
            "ci_excludes_zero": d_sens["excludes_zero"],
            "margin_required": scr.MARGIN,
            "margin_reached": bool(np.isfinite(d_sens["diff"])
                                   and d_sens["diff"] >= scr.MARGIN),
            "margin_reached_with_ci_above_zero": bool(
                np.isfinite(d_sens["diff"]) and d_sens["diff"] >= scr.MARGIN
                and np.isfinite(d_sens["lo"]) and d_sens["lo"] > 0)},
        "matched_sensitivity": {
            "target_train_sensitivity": m_matched_sens["matched_train_sensitivity"],
            "model_sensitivity": m_at_matched_sens["sensitivity"],
            "model_specificity": m_at_matched_sens["specificity"],
            "model_referral_rate": m_at_matched_sens["referral_rate"],
            "baseline_sensitivity": base["screening_point"]["sensitivity"],
            "baseline_specificity": base["screening_point"]["specificity"],
            "baseline_referral_rate": base["screening_point"]["referral_rate"],
            "specificity_difference": d_spec["diff"],
            "specificity_difference_ci": [d_spec["lo"], d_spec["hi"]],
            "ci_excludes_zero": d_spec["excludes_zero"],
            "margin_reached_with_ci_above_zero": bool(
                np.isfinite(d_spec["diff"]) and d_spec["diff"] >= scr.MARGIN
                and np.isfinite(d_spec["lo"]) and d_spec["lo"] > 0)},
        "auroc_difference": auroc_diff,
        "auroc_difference_ci": [d_auroc["lo"], d_auroc["hi"]],
        "auroc_ci_excludes_zero": bool(d_auroc["lo"] > 0 or d_auroc["hi"] < 0),
        "screening_verdict": v,
        "how_near_the_boundary": {
            "sensitivity_floor_margin":
                float(model["screening_point"]["sensitivity"] - scr.TARGET_SENS),
            "specificity_floor_margin":
                float(model["screening_point"]["specificity"] - scr.SPEC_FLOOR),
            "matched_spec_margin_shortfall": float(d_sens["diff"] - scr.MARGIN),
            "matched_sens_margin_shortfall": float(d_spec["diff"] - scr.MARGIN),
            "either_margin_cleared": bool(
                scr.margin_cleared(d_sens["diff"], d_sens["lo"])
                or scr.margin_cleared(d_spec["diff"], d_spec["lo"]))},
    }


def strip(d: dict) -> dict:
    return {k: v for k, v in d.items() if not k.startswith("_")}


def refer_everybody(truth: np.ndarray) -> dict:
    return scr.screening_metrics(truth, np.ones(len(truth), dtype=bool))


def _phone_matrix(feat: pd.DataFrame, conds: dict) -> np.ndarray:
    """The simulated phone-RGB feature matrix. `build_conditions` adds its phone_*
    columns to the frame it is given, so it is called on a copy and the columns are
    read back from that copy."""
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from ppg_hb_estimation_gate_phase4 import build_conditions          # noqa: E402
    tmp = feat.copy()
    c = build_conditions(tmp)
    return tmp[c["3_phone_rgb_simulated"]].to_numpy(float)


# ------------------------------------------------------------------ imaging arm
def imaging() -> dict:
    d = pd.read_csv(IMG_PRED)
    z = np.load(IMG_CROPS, allow_pickle=False)
    assert list(d["subject_id"]) == list(z["subject"]), "prediction/crop order differs"
    y = d["y_true"].to_numpy(float)
    male = (d["sex"].astype(str).str.strip().str.upper() == "M").to_numpy()
    age = d["age"].to_numpy(float)
    site = d["site"].to_numpy(str)
    lab = z["lab"]
    thr = scr.who_threshold(male, age)
    truth = y < thr
    folds = folds_for(len(y))

    is_italy = (site == "eyes_defy:Italy").astype(float)
    demo3 = np.stack([is_italy, age, male.astype(float)], 1)
    cnn = d["y_pred"].to_numpy(float)

    scores = {
        "population_mean": mean_cv(y, folds),
        "sex_only": ridge_cv(male.astype(float)[:, None], y, folds),
        "demographics_age_sex": ridge_cv(np.stack([age, male.astype(float)], 1), y, folds),
        "site_only": ridge_cv(is_italy[:, None], y, folds),
        "demographics_site_sex_age": ridge_cv(demo3, y, folds),
        "colour_features_lab": ridge_cv(lab, y, folds),
        "colour_features_lab_plus_site_sex_age":
            ridge_cv(np.concatenate([lab, demo3], 1), y, folds),
        "image_cnn": cnn,
        "image_cnn_plus_site_sex_age":
            ridge_cv(np.stack([cnn, is_italy, age, male.astype(float)], 1), y, folds),
    }
    models = {k: evaluate_model(k, v, y, truth, thr, folds) for k, v in scores.items()}

    demo_only = ["population_mean", "sex_only", "demographics_age_sex", "site_only",
                 "demographics_site_sex_age"]
    best_demo = max(demo_only, key=lambda k: (models[k]["auroc"]
                                              if np.isfinite(models[k]["auroc"]) else -1))
    best_demo_mae = min(demo_only, key=lambda k: models[k]["mae_g_dl"])

    comparisons = {k: compare(models[k], models[best_demo], truth, folds)
                   for k in ("image_cnn", "colour_features_lab",
                             "image_cnn_plus_site_sex_age",
                             "colour_features_lab_plus_site_sex_age")}
    if best_demo != best_demo_mae:
        comparisons["image_cnn__vs_mae_best_demographic"] = compare(
            models["image_cnn"], models[best_demo_mae], truth, folds)

    # ---- within-site: the recorded 0.875 is POOLED across two sites whose mean Hb
    # differs by 2.4 g/dL, so a site-blind ranking scores partly on site separation.
    per_site = {}
    for s in sorted(set(site)):
        m = site == s
        if len(np.unique(truth[m].astype(int))) < 2:
            per_site[s] = {"n": int(m.sum()), "note": "one class only; AUROC undefined"}
            continue
        sf = folds_for(int(m.sum()))
        row = {"n": int(m.sum()), "n_anaemic": int(truth[m].sum()),
               "prevalence": float(truth[m].mean()),
               "refer_everybody": refer_everybody(truth[m]),
               "comparator_note":
                   "Within a single site the site indicator is constant and carries no "
                   "information, so the within-site demographic comparator is age+sex."}
        subs = {}
        for k in ("image_cnn", "colour_features_lab", "demographics_site_sex_age",
                  "sex_only", "demographics_age_sex"):
            sub = evaluate_model(k, scores[k][m], y[m], truth[m], thr[m], sf)
            subs[k] = sub
            row[k] = {"auroc": sub["auroc"], "auroc_ci": sub["auroc_ci"],
                      "auprc": sub["auprc"], "auprc_ci": sub["auprc_ci"],
                      "auprc_baseline_prevalence": sub["auprc_baseline_prevalence"],
                      "sensitivity": sub["screening_point"]["sensitivity"],
                      "sensitivity_ci": sub["screening_point"]["sensitivity_ci"],
                      "specificity": sub["screening_point"]["specificity"],
                      "specificity_ci": sub["screening_point"]["specificity_ci"],
                      "ppv": sub["screening_point"]["ppv"],
                      "npv": sub["screening_point"]["npv"],
                      "false_referral_rate": sub["screening_point"]["false_referral_rate"],
                      "n_anaemic_flagged": sub["screening_point"]["n_anaemic_flagged"],
                      "referral_rate": sub["screening_point"]["referral_rate"],
                      "number_needed_to_screen":
                          sub["screening_point"]["number_needed_to_screen"],
                      "mae_g_dl": sub["mae_g_dl"]}
        row["comparisons"] = {
            k: compare(subs[k], subs["demographics_age_sex"], truth[m], sf)
            for k in ("image_cnn", "colour_features_lab")}
        per_site[s] = row

    return {"n": int(len(y)), "n_anaemic": int(truth.sum()),
            "prevalence": float(truth.mean()),
            "thresholds": {"male_g_dl": scr.MALE_THRESHOLD,
                           "female_g_dl": scr.FEMALE_THRESHOLD,
                           "age_min": float(age.min()), "age_max": float(age.max()),
                           "n_under_15": 0,
                           "pregnancy_status": "NOT RECORDED; non-pregnant threshold "
                                               "applied to all women (see CLAUDE.md)"},
            "refer_everybody": refer_everybody(truth),
            "best_demographic_baseline_by_auroc": best_demo,
            "best_demographic_baseline_by_mae": best_demo_mae,
            "models": {k: strip(v) for k, v in models.items()},
            "comparisons": comparisons,
            "within_site": per_site}


def imaging_cross_site() -> dict:
    if not XS_PRED.exists():
        return {"status": "MISSING - run scripts/cross_site_cnn_predictions_phase9a.py"}
    d = pd.read_csv(XS_PRED)
    rec = json.loads(IMG_JSON.read_text(encoding="utf-8"))["cross_site"]
    out = {"regeneration_note":
           "Phase 6.5 saved only summary MAE for the cross-site arm, so these "
           "per-subject predictions were regenerated with the recorded construction "
           "(3 seeds, 30 epochs, seed 20260911). See the reproducibility block.",
           "directions": {}}
    for tag in ("italy_to_india", "india_to_italy"):
        te = d[(d.direction == tag) & (d.split == "test")].reset_index(drop=True)
        tr = d[(d.direction == tag) & (d.split == "train")].reset_index(drop=True)
        for part in (te, tr):
            part["male"] = (part["sex"].astype(str).str.strip().str.upper() == "M")
        y_te = te["y_true"].to_numpy(float)
        thr_te = scr.who_threshold(te["male"].to_numpy(), te["age"].to_numpy(float))
        truth_te = y_te < thr_te
        y_tr = tr["y_true"].to_numpy(float)
        thr_tr = scr.who_threshold(tr["male"].to_numpy(), tr["age"].to_numpy(float))
        truth_tr = y_tr < thr_tr

        s_te, s_tr = te["y_pred"].to_numpy(float), tr["y_pred"].to_numpy(float)
        # Operating point chosen on the TRAIN SITE only, applied to the held-out site.
        cut, reached = scr.choose_cut_for_sensitivity(s_tr, truth_tr)
        call = s_te < cut
        m = scr.screening_metrics(truth_te, call)
        rank = scr.ranking_metrics(truth_te, s_te)
        auroc_ci = scr.bootstrap_ci(truth_te, s_te,
                                    lambda t, s: scr.ranking_metrics(t, s)["auroc"])
        sens_ci = scr.bootstrap_ci(truth_te, call,
                                   lambda t, c: scr.screening_metrics(t, c)["sensitivity"])

        # demographic baseline, trained on the train site, applied to the test site
        def demo_matrix(part):
            return np.stack([part["age"].to_numpy(float),
                             part["male"].to_numpy().astype(float)], 1)
        mdl = make_pipeline(SimpleImputer(strategy="median"), StandardScaler(),
                            RidgeCV(alphas=np.logspace(-3, 3, 25)))
        mdl.fit(demo_matrix(tr), y_tr)
        b_te, b_tr = mdl.predict(demo_matrix(te)), mdl.predict(demo_matrix(tr))
        bcut, _ = scr.choose_cut_for_sensitivity(b_tr, truth_tr)
        bcall = b_te < bcut
        bm = scr.screening_metrics(truth_te, bcall)
        brank = scr.ranking_metrics(truth_te, b_te)
        # site-mean constant predictor: the train site's mean Hb for everyone
        cm = scr.screening_metrics(truth_te, np.full(len(y_te), y_tr.mean()) < thr_te)
        d_sens = scr.paired_difference_ci(truth_te, call, bcall, "sensitivity")

        out["directions"][tag] = {
            "n_test": int(len(y_te)), "n_train": int(len(y_tr)),
            "n_anaemic_test": int(truth_te.sum()),
            "prevalence_test": float(truth_te.mean()),
            "prevalence_train": float(truth_tr.mean()),
            "refer_everybody": refer_everybody(truth_te),
            "cnn": {"mae_g_dl": float(np.mean(np.abs(s_te - y_te))),
                    "mae_recorded": float(rec[tag]["cnn"]["mae_g_dl"]),
                    "bias_g_dl": float(np.mean(s_te - y_te)),
                    "auroc": rank["auroc"], "auroc_ci": [auroc_ci["lo"], auroc_ci["hi"]],
                    "auprc": rank["auprc"],
                    "cut_chosen_on_train_site_g_dl": float(cut),
                    "train_site_reached_target_sensitivity": bool(reached),
                    **m,
                    "sensitivity_ci": [sens_ci["lo"], sens_ci["hi"]]},
            "demographics_age_sex": {"mae_g_dl": float(np.mean(np.abs(b_te - y_te))),
                                     "auroc": brank["auroc"], **bm},
            "train_site_mean_constant": cm,
            "cnn_minus_demographics_sensitivity": d_sens["diff"],
            "cnn_minus_demographics_sensitivity_ci": [d_sens["lo"], d_sens["hi"]],
            "ci_excludes_zero": d_sens["excludes_zero"],
            "screening_verdict": scr.verdict(m["sensitivity"], m["specificity"],
                                             d_sens["diff"], d_sens["lo"])}
    return out


# ---------------------------------------------------------------------- PPG arm
def ppg() -> dict:
    deep = pd.read_csv(PPG_DEEP)
    feat = pd.read_csv(PPG_FEAT)
    feat = feat[np.isfinite(feat.hb_g_dl)].reset_index(drop=True)
    assert list(deep.subject_id) == list(feat.subject_id), "PPG subject order differs"
    y = deep["y_true"].to_numpy(float)
    assert np.allclose(y, feat.hb_g_dl.to_numpy(float)), "PPG labels differ"
    male = (deep["sex"].astype(str).str.strip().str.upper() == "M").to_numpy()
    age = deep["age"].to_numpy(float)
    thr = scr.who_threshold(male, age)
    truth = y < thr
    folds = folds_for(len(y))

    # gate_b.json stripped its `preds` key, but the Phase 6 known-truth CSVs carry the
    # four-wavelength and four-wavelength+demographics predictions and reproduce the
    # recorded MAEs to 0.0000. The other two conditions are regenerated here from the
    # recorded column definitions (`build_conditions`) on the identical folds.
    gate = json.loads(PPG_GATEB.read_text(encoding="utf-8"))
    kt = paths.INTERIM / "phase6" / "known_truth"
    ppg_feat_pred = pd.read_csv(kt / "phase4_ppg_features_only.csv")["y_pred"].to_numpy(float)
    plusdemo = pd.read_csv(kt / "phase4_ppg_plus_demographics.csv")["y_pred"].to_numpy(float)
    for nm, pr, rec in (("four_wavelength", ppg_feat_pred,
                         gate["conditions"]["1_four_wavelength"]["mae_g_dl"]),
                        ("four_wavelength_plus_demographics", plusdemo,
                         gate["conditions"]["1_four_wavelength_plus_demographics"]["mae_g_dl"])):
        got = float(np.mean(np.abs(pr - y)))
        assert abs(got - rec) < 1e-3, f"{nm}: reused preds give {got}, recorded {rec}"

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from ppg_hb_estimation_gate_phase4 import build_conditions          # noqa: E402
    conds = build_conditions(feat.copy())

    demo_cols = ["age", "sex", "height", "weight"]
    scores = {
        "population_mean": mean_cv(y, folds),
        "sex_only": ridge_cv(feat[["sex"]].to_numpy(float), y, folds),
        "demographics_age_sex_height_weight":
            ridge_cv(feat[demo_cols].to_numpy(float), y, folds),
        "ppg_features_four_wavelength": ppg_feat_pred,
        "ppg_features_660nm_only":
            ridge_cv(feat[conds["2_660nm_only"]].to_numpy(float), y, folds),
        "ppg_features_phone_rgb_simulated":
            ridge_cv(_phone_matrix(feat, conds), y, folds),
        "ppg_features_plus_demographics": plusdemo,
        "ppg_deep_speccnn_660_selected": deep["y_pred"].to_numpy(float),
        "ppg_deep_speccnn_660_seed0": deep["y_pred_seed__0"].to_numpy(float),
    }
    models = {k: evaluate_model(k, v, y, truth, thr, folds) for k, v in scores.items()}
    demo_only = ["population_mean", "sex_only", "demographics_age_sex_height_weight"]
    best_demo = max(demo_only, key=lambda k: (models[k]["auroc"]
                                              if np.isfinite(models[k]["auroc"]) else -1))
    best_demo_mae = min(demo_only, key=lambda k: models[k]["mae_g_dl"])
    comparisons = {k: compare(models[k], models[best_demo], truth, folds)
                   for k in ("ppg_deep_speccnn_660_selected",
                             "ppg_features_four_wavelength",
                             "ppg_features_plus_demographics")}
    return {"n": int(len(y)), "n_anaemic": int(truth.sum()),
            "prevalence": float(truth.mean()),
            "thresholds": {"male_g_dl": scr.MALE_THRESHOLD,
                           "female_g_dl": scr.FEMALE_THRESHOLD,
                           "age_min": float(age.min()), "age_max": float(age.max()),
                           "n_under_15": 0,
                           "pregnancy_status": "NOT RECORDED; non-pregnant threshold "
                                               "applied to all women"},
            "refer_everybody": refer_everybody(truth),
            "single_site": "Hb_PPG_Dataset is one site and one device; there is no "
                           "cross-site or cross-device axis for this arm.",
            "best_demographic_baseline_by_auroc": best_demo,
            "best_demographic_baseline_by_mae": best_demo_mae,
            "models": {k: strip(v) for k, v in models.items()},
            "comparisons": comparisons}


def main() -> int:
    t0 = time.time()
    OUT.mkdir(parents=True, exist_ok=True)
    res = {
        "pre_declared": {
            "source": "CLAUDE.md section 6, Phase 9A, committed 755da9b before this ran",
            "who_thresholds": "adults only: men <13.0, non-pregnant women <12.0 g/dL",
            "operating_point": "highest specificity subject to sensitivity >= 0.90, "
                               "chosen on TRAIN folds only, applied to held-out",
            "target_sensitivity": scr.TARGET_SENS,
            "specificity_floor_for_useful": scr.SPEC_FLOOR,
            "clinically_meaningful_margin": scr.MARGIN,
            "margin_rule": "sensitivity gain >= 0.10 at matched specificity AND "
                           "bootstrap CI lower bound > 0",
            "bootstrap": {"n": scr.N_BOOT, "seed": scr.SEED, "kind": "subject-level "
                          "percentile; paired for differences"}},
        "regenerated_because_never_saved": [
            "per-subject baseline predictions for both arms (Phase 4 Gate B and Phase "
            "6.5 Task 2 stored only summary metrics) - same estimators, same folds",
            "cross-site image-CNN per-subject predictions - scripts/"
            "cross_site_cnn_predictions_phase9a.py, recorded construction"],
    }
    print("=== imaging arm: pooled site-mixed CV ===")
    res["imaging"] = imaging()
    print("=== imaging arm: cross-site ===")
    res["imaging_cross_site"] = imaging_cross_site()
    print("=== PPG arm ===")
    res["ppg"] = ppg()
    res["elapsed_s"] = time.time() - t0

    (OUT / "screening.json").write_text(json.dumps(res, indent=2, default=float),
                                        encoding="utf-8")
    print(f"\nwrote {OUT / 'screening.json'}  ({res['elapsed_s']:.0f}s)")

    # ------------------------------------------------------------- console summary
    for arm, key in (("IMAGING (pooled, site-mixed CV)", "imaging"), ("PPG", "ppg")):
        a = res[key]
        print(f"\n### {arm}: n={a['n']} anaemic={a['n_anaemic']} "
              f"prevalence={a['prevalence']:.3f}")
        re_ = a["refer_everybody"]
        print(f"  refer-everybody: sens {re_['sensitivity']:.3f} spec "
              f"{re_['specificity']:.3f} referral {re_['referral_rate']:.3f} "
              f"NNS {re_['number_needed_to_screen']:.1f}")
        print(f"  best demographic baseline by AUROC: {a['best_demographic_baseline_by_auroc']}")
        print(f"  {'model':42s} {'MAE':>5s} {'AUROC':>6s} {'AUPRC':>6s} "
              f"{'sens':>5s} {'spec':>5s} {'flag':>5s} {'refer':>6s} {'NNS':>6s} {'plugSn':>6s}")
        for k, m in a["models"].items():
            sp = m["screening_point"]
            print(f"  {k:42s} {m['mae_g_dl']:5.3f} {m['auroc']:6.3f} {m['auprc']:6.3f} "
                  f"{sp['sensitivity']:5.3f} {sp['specificity']:5.3f} "
                  f"{sp['n_anaemic_flagged']:3d}/{sp['n_anaemic']:<3d} "
                  f"{sp['referral_rate']:6.3f} "
                  f"{sp['number_needed_to_screen']:6.1f} "
                  f"{m['plugin_point']['sensitivity']:6.3f}")
        for k, c in a["comparisons"].items():
            ms = c["matched_specificity"]
            print(f"  -- {k} vs {c['baseline']}: at matched spec "
                  f"{ms['target_train_specificity']:.3f} -> sens {ms['model_sensitivity']:.3f} "
                  f"vs {ms['baseline_sensitivity']:.3f}, diff {ms['sensitivity_difference']:+.3f} "
                  f"CI [{ms['sensitivity_difference_ci'][0]:+.3f},"
                  f"{ms['sensitivity_difference_ci'][1]:+.3f}] "
                  f"margin>={scr.MARGIN} reached={ms['margin_reached_with_ci_above_zero']} "
                  f"=> {c['screening_verdict']}")

    print("\n### IMAGING within-site (the recorded 0.875 is POOLED across sites)")
    for s, v in res["imaging"]["within_site"].items():
        if "note" in v:
            print(f"  {s}: {v['note']}")
            continue
        print(f"  {s}: n={v['n']} anaemic={v['n_anaemic']} prev={v['prevalence']:.3f}")
        for k in ("image_cnn", "colour_features_lab", "demographics_site_sex_age",
                  "sex_only"):
            m = v[k]
            print(f"    {k:36s} AUROC {m['auroc']:.3f} "
                  f"[{m['auroc_ci'][0]:.3f},{m['auroc_ci'][1]:.3f}] "
                  f"sens {m['sensitivity']:.3f} spec {m['specificity']:.3f}")

    print("\n### IMAGING cross-site")
    for tag, v in res["imaging_cross_site"].get("directions", {}).items():
        c = v["cnn"]
        print(f"  {tag}: n={v['n_test']} anaemic={v['n_anaemic_test']} "
              f"prev={v['prevalence_test']:.3f} | CNN MAE {c['mae_g_dl']:.3f} "
              f"(recorded {c['mae_recorded']:.3f}) bias {c['bias_g_dl']:+.3f}")
        print(f"    AUROC {c['auroc']:.3f} [{c['auroc_ci'][0]:.3f},{c['auroc_ci'][1]:.3f}] "
              f"sens {c['sensitivity']:.3f} spec {c['specificity']:.3f} "
              f"flags {c['n_anaemic_flagged']}/{c['n_anaemic']} "
              f"referral {c['referral_rate']:.3f} => {v['screening_verdict']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
